[ENG-804, ENG-802, ENG-800] Minor UI Fixes
spacedriveapp/spacedrive pull request #1016
Opened 2023-06-24 13:54 UTC by ameer2468

- Files now have a tooltip to show file extension
- maxLength set for creating tag names and indexer rule names
- Max width and truncation set for location names in the topbar
- Hex code regex validation for tags

<img width="253" alt="Screenshot 2023-06-24 at 4 49 13 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/949e6d2b-5c31-4886-a30d-47b823186796">

<img width="162" alt="Screenshot 2023-06-24 at 4 49 35 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/87ead3e7-089f-4ce6-a582-e4caba396d51">

<img width="585" alt="Screenshot 2023-06-24 at 4 49 45 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/2c228892-e377-46e0-a7c7-fbe88f8c4476">

<img width="148" alt="Screenshot 2023-06-24 at 4 50 28 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/9cadcb27-fb9b-4ef6-810a-6f0f3d9f3c4d">

2023-06-24 14:17 UTC, utkubakir requested changes

2023-06-24 14:17 UTC, utkubakir commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +					maxLength={24}
Let's also put this restriction with zod too. `.max(24)` and `min(1)` should do it. Also no whitespace etc. Actually, we should remove it from here and let zod handle the validation

2023-06-24 14:17 UTC, utkubakir commented on interface/app/$libraryId/settings/library/tags/EditForm.tsx
>  	name: z.string().nullable(),
zod validation too

2023-06-24 14:17 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +					maxLength={18}
let's use zod instead

2023-06-24 14:17 UTC, utkubakir commented on interface/app/$libraryId/settings/library/tags/EditForm.tsx
> +						maxLength={7}
zod

2023-06-24 14:22 UTC, ameer2468 commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +					maxLength={24}
Doesn't work

2023-06-24 16:11 UTC, utkubakir commented on interface/app/$libraryId/Explorer/File/RenameTextBox.tsx
> +				{extension ? <Tooltip label={extension}>{text}</Tooltip> : text}
We should show the tooltip when the text gets truncated, not when the object has an extension.

2023-06-24 16:15 UTC, ameer2468 commented on interface/app/$libraryId/Explorer/File/RenameTextBox.tsx
> +				{extension ? <Tooltip label={extension}>{text}</Tooltip> : text}
This was done to check whether its a folder or a file, thats why I added extension as a prop. This component is being used for files and folders.

2023-06-24 17:07 UTC, utkubakir commented on interface/app/$libraryId/Explorer/File/RenameTextBox.tsx
> +				{extension ? <Tooltip label={extension}>{text}</Tooltip> : text}
![image](https://github.com/spacedriveapp/spacedrive/assets/74243531/02739dab-fbab-4890-90c3-a9dfc5ed5577)

James explained perfectly here

2023-06-25 16:19 UTC, utkubakir submitted a review, later dismissed

2023-06-25 16:23 UTC, utkubakir approved these changes

2023-06-25 16:31 UTC, merged