[ENG-803] Set date upon tag creation
spacedriveapp/spacedrive pull request #1021
Opened 2023-06-24 16:53 UTC by gedeondoescode

This PR intends to solve an issue with `date_created` and `date_modified` returning `NULL` inside main library database. As of now, this is partially functioning, but has a few issues such as the time being stored is in UNIX time and that when attempting to create a new tag, it fails to execute. At the moment this PR exists as a draft as I continue to make changes and improve it.

Closes #1020

2023-06-24 17:14 UTC, utkubakir commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +	date_created: z.string()
the core should handle this, no need to pass it from frontend

2023-06-24 17:24 UTC, gedeondoescode commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +	date_created: z.string()
I've already attempted this from the start. Because it's generated as a required argument for `data`, it has to be there. If there's a way to omit that from being sent through that'd be great.

2023-06-24 18:01 UTC, utkubakir commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +	date_created: z.string()
hmm @brxken128

2023-06-24 18:05 UTC, brxken128 commented on interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
> +	date_created: z.string()
On it

2023-06-24 21:02 UTC, brxken128 commented
This is essentially finished, tested, and working great. Nice start btw @gedeondoescode, I hope the additional code helps to clear things up. Feel free to ping me in the Discord (same usename) if you need any future advice!

2023-06-25 04:57 UTC, utkubakir approved these changes

2023-06-25 06:08 UTC, Brendonovich requested changes

2023-06-25 06:08 UTC, Brendonovich commented on core/src/object/tag/seed.rs
> +		.await?;
`date_created` is already set inside `exec`, no need to do it here

2023-06-25 06:08 UTC, Brendonovich commented on core/src/object/tag/seed.rs
> +	for tag in tags.clone() {
`clone` isn't necessary since `tags` only has to be used in this loop

2023-06-25 13:34 UTC, Brendonovich approved these changes

2023-06-25 13:47 UTC, merged