[ENG-828] Fix corrupt videos force crashing the app
spacedriveapp/spacedrive pull request #1028
Opened 2023-06-26 20:27 UTC by brxken128

If the FFmpeg lib ran into a video that was corrupt, the app would force close without warning. This resolves that.

2023-06-26 21:39 UTC, brxken128 commented
Seems to work great now, but please may someone else test on a large library? Preferably one without subtitles as those are not fixed yet.

2023-06-26 21:46 UTC, jamiepine submitted a review, later dismissed

2023-06-27 04:04 UTC, oscartbeaumont approved these changes

2023-06-27 05:07 UTC, HeavenVolkoff requested changes

2023-06-27 05:07 UTC, HeavenVolkoff commented on crates/ffmpeg/src/movie_decoder.rs
> +			if (*decoder.format_context).subtitle_codec_id == AVCodecID::AV_CODEC_ID_NONE {
I am also skeptical this does anything. According to ffmpeg docs, the `*_code_id` attributes are used to force FFmpeg to use a specific decoder, and should be set by the user:
https://ffmpeg.org/doxygen/6.0/structAVFormatContext.html#acca61846d663b15e5a56b35c903e4d3b

Maybe we could set this to `AV_CODEC_ID_NONE` and ffmpeg will probably ignore subtitles in video files (not 100% sure, but from a quick read of ffmpeg source files, this will maybe work)

2023-06-27 05:08 UTC, merged

2023-06-27 09:18 UTC, brxken128 commented on crates/ffmpeg/src/movie_decoder.rs
> +			if (*decoder.format_context).probe_score == 100 {
Try it out - change this value from 100 to anything else. If FFMpeg isn't **certain** that the video file is correct and not corrupt, the app will force crash with no warning. It needs to remain how it is, but yes I will use the constant mentioned.

2023-06-27 09:18 UTC, brxken128 commented on crates/ffmpeg/src/movie_decoder.rs
> +			if (*decoder.format_context).probe_score == 100 {
This has no adverse effects either - real, normal video files always return 100 as they aren't corrupt.

2023-06-27 09:32 UTC, brxken128 commented on crates/ffmpeg/src/movie_decoder.rs
> +			if (*decoder.format_context).subtitle_codec_id == AVCodecID::AV_CODEC_ID_NONE {
You're right, this did nothing so it was dropped. `AV_CODEC_ID_NONE` shows up on **_every_** file I tested, subtitles or not. I spent hours debugging that.