[ENG-807] List view improvements
spacedriveapp/spacedrive pull request #1065
Opened 2023-07-01 00:56 UTC by niikeec

2023-07-02 03:00 UTC, Brendonovich requested changes
all da contexts

2023-07-02 03:00 UTC, Brendonovich commented on interface/hooks/useIsTextTruncated.ts
> +	}, [element, determineIsTruncated, text]);
Ik this was here before you changed it but could the state + callback + effect be combined into a memo?

2023-07-02 19:51 UTC, niikeec commented on interface/hooks/useIsTextTruncated.ts
> +	}, [element, determineIsTruncated, text]);
If you prefer this
```ts
export const useIsTextTruncated = (element: RefObject<HTMLElement>, text: string | null) => {
    const { width } = useResizeObserver({ ref: element });

    return useMemo(() => {
        if (!element.current) return false;
        return element.current.scrollWidth > element.current.clientWidth;
    }, [element, width, text]);
};
```

2023-07-02 21:58 UTC, Brendonovich commented on interface/hooks/useIsTextTruncated.ts
> +	}, [element, determineIsTruncated, text]);
Ye that should do it

2023-07-03 07:12 UTC, Brendonovich approved these changes

2023-07-03 07:15 UTC, merged