[ENG-862] Non-indexed locations
spacedriveapp/spacedrive pull request #1092
Opened 2023-07-12 04:40 UTC by fogodev

Currently a first draft on how non-indexed locations should work. Need some frontend guys support to the approve the provided Core API for listing files, directories and locations on a given path.

2023-08-02 08:11 UTC, HeavenVolkoff requested changes
- [ ] Fix indexed Locations sometimes selecting other folder/files in Ephemeral location besides it, due to conflicting IDs

2023-08-02 08:58 UTC, HeavenVolkoff requested changes
- [x] Fix Empty context menu sometimes (Ephemeral and indexed locations)
- [x] Fix loading an ephemeral path containing a file without read permissions breaks UI
- [x] ListView flashes EmptyNotice when changing file sorting

2023-08-10 00:57 UTC, Brendonovich commented on apps/desktop/crates/macos/src-swift/env.swift
> +}
We can use Tauri's JS API to do this: https://tauri.app/v1/api/js/path/#homedir

2023-08-14 14:51 UTC, HeavenVolkoff commented on apps/desktop/crates/macos/src-swift/env.swift
> +}
Yeah, but I am not a fan of the lib tauri is using for this:
https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/path/desktop.rs#L123C1-L132
https://github.com/xdg-rs/dirs/blob/master/dirs-sys/src/lib.rs#L28-L61

And while `$HOME` is defined in macOS, I think getting the path from the native swift api to be a bit better, and in *nix there is no fallback for missing HOME envvar (not common, but can happen), which I implemented in our code. (For windows the api we are using is the same that tauri is using, but it was so little code that I just copied to our windows crate)

2023-08-21 14:36 UTC, niikeec submitted a review, later dismissed

2023-08-21 14:36 UTC, niikeec commented on interface/app/$libraryId/Explorer/ViewContext.ts
> +export type ExplorerViewSelection = string | string[];
Can be removed

2023-08-21 14:36 UTC, niikeec commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +						type !== ThumbType.Icon && thumbs.length > 1
imo it should be kept as a string

2023-08-21 14:36 UTC, niikeec commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +				)}
this should be always rendered imo

2023-08-21 14:36 UTC, niikeec commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +				)}
this should be always rendered imo

2023-08-21 14:36 UTC, niikeec commented on interface/app/$libraryId/Explorer/View/ListView.tsx
> +			: explorerView.padding?.y) || 12;
Don't think this is necessary

2023-08-21 23:09 UTC, brxken128 commented on apps/desktop/crates/macos/src-swift/env.swift
> +}
In all fairness I've never came across a *nix system configuration that had no `$HOME` var, even if it was set to `/var/empty` or `/nonexistent` (TrueNAS uses the latter).

2023-08-22 06:42 UTC, Brendonovich commented on apps/desktop/crates/macos/src-swift/env.swift
> +}
I reckon if it's good enough for Tauri it's good enough for us, unless you reeeealy think it's worth it

2023-08-22 08:05 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +				)}
Should we leave these fields showing up without a value? Because items from ephemeral locations will never have this info due to not be indexed

2023-08-22 08:15 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +						type !== ThumbType.Icon && thumbs.length > 1
Why? This seems like such a by the book use case for enum. Using strings here just loose on type safety and code clarity without any meaninful gain from what I can see, unless I am missing something here

2023-08-22 08:15 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +				)}
same as above

2023-08-22 08:18 UTC, niikeec commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +				)}
Can we make it so they only don't show in ephemeral locations?

2023-08-22 08:24 UTC, niikeec commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +						type !== ThumbType.Icon && thumbs.length > 1
Not a big fan of enums, but I guess we can keep it.

2023-08-22 09:59 UTC, HeavenVolkoff commented on apps/desktop/crates/macos/src-swift/env.swift
> +}
Ok, I changed to use the tauri API, the Linux $HOME is being solved anyway due to an environment normalization step I introduced some time ago:
https://github.com/spacedriveapp/spacedrive/blob/7d2136627cb1c8ac3e5fd38a8fd121b1f02aa773/apps/desktop/crates/linux/src/env.rs#L120-L178

2023-08-22 10:53 UTC, niikeec commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +}
Can we change back to const?

2023-08-22 11:22 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +}
enums are read-only by default, or you mean re-writing this into a const object?

2023-08-22 11:27 UTC, niikeec commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +}
back to const object as it was before

2023-08-23 13:19 UTC, utkubakir approved these changes

2023-08-23 17:29 UTC, merged