[ENG-288] Media data extraction
spacedriveapp/spacedrive pull request #1099
Opened 2023-07-14 11:52 UTC by brxken128

2023-07-16 05:10 UTC, utkubakir commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
is this correct? Why is it `now()`?

2023-07-16 05:12 UTC, utkubakir commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
And don't we have this field on Object? What's the difference between this and that one?

2023-07-16 10:40 UTC, brxken128 commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
Because that's the date the _field_ was created, not the date from the image, in order to keep consistency with the rest of the schema. The line directly beneath defines when the image was taken.

2023-07-16 10:44 UTC, brxken128 commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
And the difference is that media data won't always be extracted at the same time an object is created.

Test it out - index a location, find an object and copy the `date_created` field, and then search for it in the `media_data` table - it won't be there as the fields are created at different times.

2023-07-16 10:47 UTC, brxken128 commented
Reverting to draft again as it turns out there's a LOT more we can improve upon to ensure coverage for the most amount of images.

2023-07-16 11:07 UTC, utkubakir commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
I reckon just remove it or rename it to `date_extracted` then. "// filesystem creation time" is also not really a comment I understand to tbh

Also about schema consistency, it's fine to have a modal without some fields, no need to worry about it.

2023-07-20 19:45 UTC, jamiepine commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
Swaying side to side with my opinion for a minute I think `date_extracted` makes a lot of sense, I'm in favour of communicating the purpose of the field accurately over consistency of having `date_created` exist on every model. Reality is not all models have timestamps so it would never be consistent anyway.

2023-07-26 18:42 UTC, brxken128 commented
It worked, until I merged main and @Brendonovich's sync stuff completely broke it. I'm unsure where to go from here.

2023-07-26 19:13 UTC, brxken128 commented on core/src/object/file_identifier/mod.rs
> +									media_data::date_created::set(Some(Utc::now().into())),
I settled for an enum, that is either: the local time from the image, UTC (via `chrono::DateTime<FixedOffset>`) or undefined if it was undefined within the image.

2023-07-29 00:24 UTC, brxken128 commented
Converting to a draft once again as we need to integrate the `MediaDataImage` struct (and the nested structs) within the frontend, but I'm not too sure how.

2023-08-09 04:10 UTC, Brendonovich commented on core/prisma/schema.prisma
>      object Object? @relation(fields: [id], references: [id], onDelete: Cascade)
@jamiepine Just wanted to confirm that we do want to store media data on objects and not file paths? Seeing as multiple video/image files with different media data could be stored under the same object, I'm not sure this will work like we want it to.

2023-08-09 04:26 UTC, Brendonovich commented on crates/media-data/src/flash/values.rs
> +impl Display for FlashValue {
What's the purpose of this impl?

2023-08-11 14:39 UTC, jamiepine commented on core/prisma/schema.prisma
>      object Object? @relation(fields: [id], references: [id], onDelete: Cascade)
Thinking about this, it would be correct to do this unless we had a mechanism to handle cases where an object has varying `cas_ids`, it shouldn't happen often and when it does we could handle it. For now, lets leave it on the Object for the sake of saving engineering hours and preventing data duplication. We'll come back to this and create a system that solves the problem while also avoiding data duplication.

2023-08-15 19:39 UTC, brxken128 commented on crates/media-data/src/flash/values.rs
> +impl Display for FlashValue {
So we can explain in-depth how the flash fired?

2023-08-24 15:01 UTC, Brendonovich requested changes
Seems like migrations are still a bit messed up. I'll go in and fix them.

2023-08-25 04:24 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    exif_version   Bytes?
These all need to be optional

2023-08-28 08:02 UTC, Brendonovich submitted a review, later dismissed

2023-08-29 10:47 UTC, utkubakir commented
let's fix types and merge this pls

2023-08-29 13:22 UTC, Brendonovich requested changes

2023-08-29 13:22 UTC, Brendonovich commented on core/src/api/files.rs
> +				pub id: i32,
use `object::id::Type`

2023-08-29 13:22 UTC, Brendonovich commented on core/src/api/files.rs
> +			}
This is redundant - you already fetch `object`, so the type can be inferred from it.

2023-08-29 13:22 UTC, Brendonovich commented on core/src/api/files.rs
> +						.include(object::include!({ media_data }))
`select` would be nicer here
```suggestion
						.select(object::select!({ id kind media_data }))
```

2023-08-29 13:23 UTC, brxken128 commented on core/src/api/files.rs
> +						.include(object::include!({ media_data }))
oh good catch, bit redundant selecting media data when we're querying media data

2023-08-29 13:25 UTC, brxken128 commented on core/src/api/files.rs
> +			}
i was on the fence about this, will remove it as yeah it's pretty pointless

2023-08-29 14:27 UTC, brxken128 commented
This should be ready to go, there's no/minimal UI work but that can come in another PR as this one is quite large already.

2023-08-29 17:02 UTC, Brendonovich approved these changes

2023-08-29 17:08 UTC, merged