[ENG-847] implement Display Full Path in inspector
spacedriveapp/spacedrive pull request #1155
Opened 2023-08-01 17:01 UTC by Raghav-45

Hey @utkubakir ! :wave:

I've successfully implemented the requested feature to display the full path in the inspector window. Now, users will have a clearer view of the file details when using Spacedrive. :file_folder:

:handshake: I've thoroughly tested the implementation, and everything seems to be working smoothly.

Closes #1151

2023-08-02 09:29 UTC, utkubakir requested changes

2023-08-02 09:29 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ContextMenu/FilePath/index.tsx
> +import { useLibraryQuery } from '../../../../../../packages/client/src';
This can be imported from `@sd/client`

2023-08-02 09:29 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ContextMenu/Object/index.tsx
> +import { useLibraryQuery } from '../../../../../../packages/client/src';
This can be imported from `@sd/client`

2023-08-02 11:55 UTC, Raghav-45 reviewed
Hey @utkubakir ! 👋

I've fixed the problems and the the requested feature is working. Now, users will able to see file path inside inspector when using Spacedrive. :raised_hands:

2023-08-03 07:51 UTC, jamiepine approved these changes
amazing, thanks so much for the PR

2023-08-03 10:18 UTC, utkubakir commented
Let's do the changes we did here too (https://github.com/spacedriveapp/spacedrive/pull/1139) and also fix typescript

2023-08-03 10:23 UTC, Raghav-45 commented
> Let's do the changes we did here too (#1139) and also fix typescript

I am currently working on it, and my approach is to use the getPath procedure to get the file path, which @HeavenVolkoff implemented in (#1139). This way, both of them will use the same function from the Rust rspc library. it will make it future proof.

2023-08-04 11:31 UTC, utkubakir approved these changes
LGTM

2023-08-04 11:37 UTC, merged