[ENG-960] pause inspector thumbnail while quick preview is open
spacedriveapp/spacedrive pull request #1186
Opened 2023-08-07 16:17 UTC by luckydye

Hi!
I gave this a try, let me know what you think :) 

A new "paused" prop on the FileThumb is used to pause and unpause when the quick-view is opened and closed.

Closes #1177

2023-08-08 09:51 UTC, utkubakir requested changes

2023-08-08 09:51 UTC, utkubakir commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +	paused?: boolean;
`pauseVideo?` sounds a bit more informative, other than that everything looks good!

2023-08-08 10:59 UTC, Brendonovich submitted a review, later dismissed

2023-08-08 10:59 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +	}, [props.pauseVideo]);
Would you mind moving this and the `<video>` element to a new `Video` component at the bottom of the file? Would be a bit cleaner imo.

2023-08-08 17:40 UTC, luckydye commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +	}, [props.pauseVideo]);
Done. 
I noticed the "Thumbnail" component is on top of the file, maybe it would make sense to move that down too?

2023-08-09 08:43 UTC, utkubakir approved these changes
lgtm

2023-08-09 08:53 UTC, merged