[ENG-971] More File Icons (code extensions)
spacedriveapp/spacedrive pull request #1217
Opened 2023-08-14 10:05 UTC by Raghav-45

Hey @utkubakir,

I've been working on implementing the `bearded-icons` library as per the recommendation from @jamiepine on Discord. To achieve this, I've created a new component called `LayeredFileIcon`. Here are screenshots showcasing the current status of the implementation:

![Screenshot (112)](https://github.com/spacedriveapp/spacedrive/assets/77260113/bfd14614-0d31-4959-8e1d-7762e835a333)
![Screenshot (110)](https://github.com/spacedriveapp/spacedrive/assets/77260113/de7a4c55-a07c-475d-a90a-2c6ae62f5229)
![Screenshot (109)](https://github.com/spacedriveapp/spacedrive/assets/77260113/b7cea9e7-7c85-45de-bccd-0df2090e3ea0)
![Screenshot (108)](https://github.com/spacedriveapp/spacedrive/assets/77260113/3984bfcf-784b-44c2-aa9b-c22f34b2a092)

I'd like to highlight that the implementation is not yet complete, I would greatly appreciate any feedback, suggestions, or tips to enhance it further.

Additionally, I've noticed the file i've created [`packages\assets\icons\ext\bearded-icons\icons\index.tsx`](https://github.com/spacedriveapp/spacedrive/blob/f099c50c1ab6533e8c191722ce9f7dc5d643e961/packages/assets/icons/ext/bearded-icons/icons/index.tsx) might be unnecessary. I would appreciate guidance on how I can avoid using it and directly import the SVGs.

Moreover, I'm planning to remove all the icons from the `packages\assets\icons\ext\bearded-icons` folder and implement a functionality similar to the automatic cloning we do with `test-files`. Although I'm unsure about the implementation details for the auto-cloning feature, I believe it would greatly improve our setup. Any assistance in implementing this feature would be invaluable.

Thank you for your time and support. Looking forward to your insights and suggestions.

Best regards,
Aditya

Closes #1207

2023-08-14 11:12 UTC, jamiepine commented
Amazing PR. I've wanted this for a while.

2023-08-14 12:20 UTC, HeavenVolkoff requested changes

2023-08-14 12:20 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +							src !== '/@fs/mnt/r/Development/Contributions/spacedrive/packages/assets/icons/Document.png' ?
Please do `kind !== Document` instead of this, as it will only work on your machine

2023-08-14 12:20 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +		// console.log(svgMapping.html)
Do not define a component inside another, either define this as a separate component, or put this markup in the parent component directly

2023-08-14 12:20 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +		// console.log(svgMapping.html)
Also, some of the these attributes are not used anywhere

2023-08-14 12:29 UTC, HeavenVolkoff commented
@Raghav-45 where did you get all those icons from? If they are from an icon library it would be better to simply add it as a dependency instead of adding 300+ icons directly to the project, as that may bring licensing issues (depending on where these came from)

2023-08-14 12:46 UTC, utkubakir commented
> @Raghav-45 where did you get all those icons from? If they are from an icon library it would be better to simply add it as a dependency instead of adding 300+ icons directly to the project, as that may bring licensing issues (depending on where these came from)

We use Bearded before and the designer of those icons hangs around in Jamie's stream and our discord from time to time. He is okay with us using it so that should be good.

In addition to Vitor's changes;

- the code icon should look like Document_pdf.png. Not take up all the space.
- No need for a separated bearded-icons/icons folder, just put them directly into the ../ext folder
- As mentioned in the issue, you should modify our generator script to generate the index file.
- ^ Also leveraging something like getIcon (under util) would be also great and very clean here

2023-08-14 16:53 UTC, utkubakir commented
> > I've been working on implementing the `bearded-icons` library as per the recommendation from @jamiepine on Discord.
> 
> > We use Bearded before and the designer of those icons hangs around in Jamie's stream and our discord from time to time. He is okay with us using it so that should be good.
> 
> I am blind, swear I didn't see the name in @Raghav-45's message. Anyway, the [repo](https://github.com/BeardedBear/bearded-icons) is GPL-3.0, so it should be fine. @utkubakir you prefer to add these icons directly to our repo? Because I think we could just add them as a deps to `@sd/interface`:
> 
> ```
> pnpm interface add BeardedBear/bearded-icons#0c6fc83
> ```
> 
> And then we can import the icons like we do with our `@sd/assets` ones.

I rather have it on assets so we can change/add more stuff in the future (+ mobile will use it too)

2023-08-14 18:55 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +				</img> */}
done!

2023-08-14 18:55 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +		// console.log(svgMapping.html)
done!

2023-08-14 18:56 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +import { svgMapping } from '../../../../../packages/assets/icons/ext/bearded-icons/icons/index';
done!

2023-08-14 19:01 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +								<LayeredFileIcon src={src} className={clsx(childClassName, props.className)} />
Creating an additional component would be beneficial, as we will need to add more functionalities and customizations in near future.

2023-08-14 19:04 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +							src !== '/@fs/mnt/r/Development/Contributions/spacedrive/packages/assets/icons/Document.png' ?
it is inside `default` return of `switch` so we dont have access to `kind` variable i added `!src.endsWith('Document.png')` temporarily

2023-08-14 19:16 UTC, Raghav-45 reviewed
Hey @utkubakir and @HeavenVolkoff 

I wanted to inform you that I've implemented the necessary modifications to the `generate.mjs` script, as per the suggestions in the issue. The script can now generate the `index` file automatically.

I also made a separate component for `LayeredFileIcon`

and regarding the directory you mentioned, could you please provide more clarity about the specific directory you are referring to? This will ensure that I accurately place the bearded icons in the correct location.

TODO:
- The code icon should resemble "Document_pdf.png," without taking up excessive space.

If you have any further inquiries or would like to review the changes, please don't hesitate to reach out

2023-08-15 07:34 UTC, Raghav-45 reviewed
Hey @utkubakir, How everything is looking i've did some modifications. I also copied a pdf file to see if it resembles it or not.

Here are some attached screenshots.

![Screenshot (120)](https://github.com/spacedriveapp/spacedrive/assets/77260113/bb23cb5b-844a-4710-bcec-bc2ad6edbfc7)
![Screenshot (119)](https://github.com/spacedriveapp/spacedrive/assets/77260113/f01087fd-243b-45d0-873b-884a9516ad99)
![Screenshot (118)](https://github.com/spacedriveapp/spacedrive/assets/77260113/89d58278-4458-4327-b8c0-03c88d54026e)

2023-08-15 08:28 UTC, jamiepine commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +								<LayeredFileIcon src={src} className={clsx(childClassName, props.className)} />
Well I guess so long as we can layer other icon packs or individual icons alongside Bearded Icons in the future, then great. Would imagine we will increase the amount of icons we display in this format as we support more kinds.

2023-08-15 08:31 UTC, jamiepine commented
Yes, I like it justified to the right.

2023-08-15 08:37 UTC, Raghav-45 commented
> Yes, I like it justified to the right.

thanks, so now the only thing remaining is conditionally rendering icons depending on its file extention, and to acheive this we will have to make a iconMap

`const iconMapping = {`
                `rust: <Icons.rust viewBox='0 0 16 16' height='40%' width='40%' />,`
                `go: <Icons.go viewBox='0 0 16 16' height='40%' width='40%' />`
`}`

2023-08-15 09:58 UTC, Raghav-45 reviewed
Hey Developers @jamiepine @utkubakir @HeavenVolkoff,

I'm thrilled to share screenshot of our current implementations with all of you. From my perspective, the progress we've made looks absolutely superb! 🚀

![Screenshot (121)](https://github.com/spacedriveapp/spacedrive/assets/77260113/bd99354e-89cb-4b5d-b053-c405f0685dcb)

Looking forward to your feedback and thoughts on the advancements we've achieved.

Also, today holds special significance as it's India's Independence Day!

Best regards,
Aditya

2023-08-15 10:25 UTC, Brendonovich requested changes

2023-08-15 10:25 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	};
- `IconMapping` should be located outside of the component, as it doesn't depend on anything inside the component and will currently get re-created on every render.
- Instead of repeating `viewBox`, `height`, etc. just use the `Icons.*` item as the value for each key, and render it as JSX with the attributes further down
- Add an explicit type of `Record<string, {whatever the type of 'Icons.*' is}>` so that doing `IconMapping[extension]` doesn't make typescript angry

2023-08-15 10:25 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +			{IconMapping.hasOwnProperty(extension) && (
Use a check like `IconMapping[extension] !== undefined` instead of `hasOwnProperty` to avoid doing `as keyof typeof ...` further down. The exact implementation is up to you, just use type narrowing to ensure the icon exists rather than a cast.

2023-08-15 10:25 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	const IconComponent = ({ extension }: { extension: keyof typeof IconMapping }) => {
This works but it'd be nicer if a dedicated component wasn't needed.

2023-08-15 10:31 UTC, utkubakir commented
Oh sorry for noticing this a bit late but if they are all svgs, you can move them to `assets/svgs` under a folder named "ext". That should clean things up quite a bit with the script as well. You wouldn't need to do `fileName !== "ext"` everywhere.

2023-08-15 11:16 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	};
done! and sapecially this comment helped me alot.

2023-08-15 11:17 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +			{IconMapping.hasOwnProperty(extension) && (
done!

2023-08-15 11:29 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	const IconComponent = ({ extension }: { extension: keyof typeof IconMapping }) => {
So, should delete separate component `LayeredFileIcon` and integrate it into `Thumb.tsx` ?

2023-08-15 11:38 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	const IconComponent = ({ extension }: { extension: keyof typeof IconMapping }) => {
Nah `LayeredFileIcon` is fine, I just meant `IconComponent` shouldn't have to be a dedicated component. Now that it's just a `const` this isn't relevant.

2023-08-15 11:47 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +							src !== '/@fs/mnt/r/Development/Contributions/spacedrive/packages/assets/icons/Document.png' ?
`kind` comes from outside the switch statement, you can still use it inside the `default` case

2023-08-15 12:05 UTC, Raghav-45 reviewed
Hey @utkubakir @Brendonovich,

I've made the requested changes and The code is now ready for your review.
- moved icons to `assets/svgs/ext`
- made seperate file for `IconMapping`
- fixed typescripts

If there are any further adjustments needed, please feel free to let me know.

2023-08-15 12:21 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
> +	const IconComponent = ({ extension }: { extension: keyof typeof IconMapping }) => {
> Nah `LayeredFileIcon` is fine, I just meant `IconComponent` shouldn't have to be a dedicated component. Now that it's just a `const` this isn't relevant.

Oh got it, DONE 🔥

2023-08-15 12:45 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +							src !== '/@fs/mnt/r/Development/Contributions/spacedrive/packages/assets/icons/Document.png' ?
Done, it now uses `kins !== 'Code'`

2023-08-16 01:40 UTC, HeavenVolkoff requested changes

2023-08-16 03:34 UTC, Raghav-45 commented
Hey @HeavenVolkoff, I was going to do that, but I was unable to do it due to our time zone differences. Anyway, thanks for contributing. I woke up and saw that you came and fixed alot of the things, and I also love the changes you made. 🤝

2023-08-16 03:36 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
In my openion You're Right 🦾

2023-08-16 07:58 UTC, utkubakir commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
Agree with @HeavenVolkoff, let's add it progressively, also why do we need a mapping? Just rename the files and rerun the generator if it doesn't fit the Icons[extension] format.

2023-08-16 08:01 UTC, utkubakir commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
It would be better to use our name formatting for extensions anywhere also, we don't need to follow Bearded's naming conventions

2023-08-16 19:58 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
We could move the icons to `assets/layered/Code/[ext].svg` and create a new utility function like `getIcon` (`getLayeredIcon` maybe) that retrieves the correct layer icon given a `kind` and `extension`.

2023-08-17 09:39 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
if we import Icons directly in this and do this `const IconComponent = extension ? Icons['python'] : null;` ( I typed `python` as an example )

then we can achieve that.

but i also think using IconsMapping is Cleaner Approach, what you think let me know.

2023-08-17 18:23 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
The idea behind also depending on `kind` is to better allow using layered icons with other files types beside code extensions. E.g. PDF and DOCX files would likely also receive a layered icon. And while extensions work mostly ok for discerning between file types, there are some edge cases (e.g. `.ts` for Typescript and `.ts` for Transport Stream video) that the `kind` attribute would allow us to differentiate between. Also, the `IconMapping` idea works fine for the current quantity of icons we are referencing, but when this grows beyond the dozens, this would start becoming a maintenance burden, due to it requiring repeating any changes made to the file structure into the mapping (e.g.: if any icon were renamed the mapping would also need to be renamed) which could lead to subtle bugs and a brittle architecture for this part of the code. IMHO, leaving all the mapping embedded into the file structure, and letting the `generate` script and the utility function automatically handle the importing of the icons would be better

2023-08-18 12:11 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
Hey @HeavenVolkoff,

Instead of using `assets/icons/layered/[kind]/[extension].svg`, wouldn't it be better to directly add exceptions?
exceptions like (e.g. `.ts` for Typescript and `.ts` for Transport Stream video), i also agree on the point of yours that the `IconMapping` idea works fine for the current quantity

I've created a simple utility called `getLayeredIcon` here is fancy Screenshot of it:
![image](https://github.com/spacedriveapp/spacedrive/assets/77260113/3d1cb5e5-b748-4ce8-af10-ddb55b820c1d)

here, the `kind` parameter is unused currently, Additionally, the icons which is Imported here are sourced from the index.ts file, which is generated by our generator.

let me know your suggestions.

2023-08-18 15:09 UTC, utkubakir commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
Let's ignore the exceptions for now and merge this PR, we can work on those at a later date.

2023-08-19 16:23 UTC, Raghav-45 reviewed
Hey @utkubakir and @HeavenVolkoff,

I hope you're doing well. I wanted to let you know that I've completed the implementation of the `getLayeredIcon` utility function, as we discussed earlier. The code is now aligned with our folder structure `assets/svgs/ext/[kind]/[extension].svg`, This modification has several advantages for our workflow.

Firstly, this new structure facilitates direct categorization of icons into folders, making it much easier to add icons based on their categories, This will allow us to use naming conventions for our icons.

In the code snippet, we perform the following steps to retrieve the icon:
1. We check the extension and attempt to retrieve the icon using `iconKind?.[extension]`
2. If the icon kind is available in `LayeredIcons` then `iconKind` gets the value of it.
3. However, if the icon is not available (i.e., it's undefined or null), we then try to fetch an icon from `LayeredIcons['Extras']?.[extension]`.
4. This approach ensures that if the initial icon retrieval is unsuccessful, we can fall back to the 'Extras' category to obtain the desired icon.

Means we have some extra icons which dosent belongs to any kind but they are there for idk they are just Extra icons we can also delete them.

Additionally, I've have currently placed all icons inside the `Extras` Folder.

It would be great to get your thoughts on this implementation and discuss any further adjustments before we proceed, Additionally, I would like to request your assistance in resolving a TypeScript issue. It seems that my `VS Code` is unable to provide accurate autocompletions, possibly due to `WSL`.

2023-08-19 16:23 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +		sh: Icons.shell
I think its Done!, you can take a look

2023-08-19 16:48 UTC, utkubakir commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +};
why do we have this file if it's not used

2023-08-19 16:49 UTC, utkubakir commented on packages/assets/util/index.ts
> +import { LayeredIcons } from '../../../packages/assets/svgs/ext/index';
lets fix this

2023-08-19 16:51 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/IconMapping.tsx
> +};
Done !

2023-08-19 16:57 UTC, Raghav-45 commented on packages/assets/util/index.ts
> +import { LayeredIcons } from '../../../packages/assets/svgs/ext/index';
![WhatsApp Image 2023-08-19 at 10 25 47 PM](https://github.com/spacedriveapp/spacedrive/assets/77260113/1582032a-cb21-424f-a803-c91a2a6a50b0)

getting this error when adding `@sd/assets/svgs/ext/index`

2023-08-19 17:24 UTC, Raghav-45 commented on packages/assets/util/index.ts
> +import { LayeredIcons } from '../../../packages/assets/svgs/ext/index';
Done!

2023-08-21 08:54 UTC, Raghav-45 commented on packages/assets/svgs/ext/index.ts
Hey @utkubakir 
I think using `ObjectKindKey` instead of string is better, whats your opinion?

2023-08-21 09:01 UTC, Raghav-45 commented on packages/assets/svgs/ext/index.ts
> +	Record<string, Record<string, FunctionComponent<SVGProps<SVGSVGElement>>>>
Hey @utkubakir 
I think using `ObjectKindKey` instead of `string` is better, whats your opinion?

2023-08-21 10:22 UTC, utkubakir commented on packages/assets/svgs/ext/index.ts
> +	Record<string, Record<string, FunctionComponent<SVGProps<SVGSVGElement>>>>
you can't import `@sd/client` here, it's just an assets folder that doesn't and shouldn't have any packages.

2023-08-21 10:53 UTC, Raghav-45 commented on packages/assets/svgs/ext/index.ts
> +	Record<string, Record<string, FunctionComponent<SVGProps<SVGSVGElement>>>>
Oh i got it 🤝

2023-08-22 14:38 UTC, utkubakir approved these changes

2023-08-22 14:45 UTC, utkubakir commented
Great job @Raghav-45

2023-08-22 14:49 UTC, merged

2023-08-22 14:49 UTC, Raghav-45 commented
> Great job @Raghav-45

Thank you for your kind words @utkubakir, Your encouragement means a lot.