[ENG-904] Thumbnail for `svg`
spacedriveapp/spacedrive pull request #1220
Opened 2023-08-14 18:04 UTC by HeavenVolkoff

WIP

2023-08-23 19:44 UTC, fogodev requested changes

2023-08-23 19:44 UTC, fogodev commented on crates/svg/src/lib.rs
> +	Io(#[from] std::io::Error),
Please don't LMAO

I've been trying to abolish this kind of direct conversion from `io::Error` which doesn't tell what file the error comes from. On Core I've been using `FileIOError`, but for subcrates I'm doing.

```rust
#[error("io error on {}: {0}", .1.display())]
Io(std::io::Error, Box<Path>),
```

Then using `.map_err(|e| SvgError::Io(e, path.to_path_buf().into_boxed_path())?` for error handling. This way, whenever a `io::Error` pops out, we know on which file it happened.

2023-08-23 19:44 UTC, fogodev commented on crates/svg/src/lib.rs
> +pub async fn svg_to_dynamic_image(path: &Path) -> SvgResult<DynamicImage> {
As this function is exposed in the public API, change it to receive `(path: impl AsRef<Path>)` instead of a `&Path` please.

2023-08-23 19:44 UTC, fogodev commented on crates/svg/src/lib.rs
> +	fontdb.load_system_fonts();
Do this function call perform any kind of I/O internally consulting some OS files? If so it need to runs in a `block_in_place` to avoid blocking the runtime.

2023-08-23 19:44 UTC, fogodev commented on core/src/object/preview/thumbnail/mod.rs
> +			img
If the file is an SVG, we don't even need this `block_in_place` call here, you can merge the above if let to already get webp data from svg or trying to process with heif or `image` lib otherwise in the `block_in_place`

2023-08-31 22:06 UTC, brxken128 commented on core/Cargo.toml
> +sd-svg = { path = "../crates/svg" }
I'll leave this in place, but I'll move the code to my `sd-images` WIP crate to unify everything

2023-08-31 22:07 UTC, brxken128 commented on core/src/object/media/thumbnail/mod.rs
> +		)?,
All of this will be cleaned up by my snazzy image handler too, as eventually we're going to have too many of these "exotic" formats to deal with and matching like this will be very cumbersome and unsightly.

2023-08-31 22:09 UTC, brxken128 commented on core/src/object/media/thumbnail/mod.rs
> +			Err(e) => warn!("Unable to extract EXIF: {:?}", e),
I disagree here. Not all images have EXIF data, and if they don't that's perfectly okay - we shouldn't be erroring if it's not present, there's multiple other types of image metadata and we currently only check for the one. Some people even strip this metadata completely, so this would always bring up a warning.

2023-08-31 22:14 UTC, brxken128 commented on crates/heif/src/lib.rs
I'm not particularly happy with these changes - they were going to be revamped in my next PR anyway but doing it this way makes it harder for us to support non-interleaved HEIF images (which do exist, they are rare but ENG-984 was made to address this issue.

2023-08-31 22:17 UTC, brxken128 approved these changes

2023-08-31 23:01 UTC, brxken128 approved these changes
Works great for me, the code is solid, we can get this merged into a single `sd-image` handling crate now! Nice job man, keep up the great work - you're killing it 🙏🏻

2023-08-31 23:03 UTC, brxken128 commented on crates/svg/src/lib.rs
> +pub async fn svg_to_dynamic_image(path: &Path) -> SvgResult<DynamicImage> {
^I would like to note that with clippy 1.72.0 this causes a lot of missing `Send` errors, whereas `&Path` doesn't from my experience

2023-08-31 23:05 UTC, merged