Extending `QuickPreview` functionality with additional filetype support
spacedriveapp/spacedrive pull request #1231
Opened 2023-08-18 13:06 UTC by Raghav-45

Hey @utkubakir,

I wanted to let you know that I've added **`QuickPreview`** support for the following file types:

- [x] .js
- [x] .php
- [x] .sh
- [x] .py
- [x] .css
- [x] .html
- [ ] .ts
- [ ] .tsx
- [ ] .jsx

Here are screenshots showcasing the current status of the implementation:
![Screenshot (146)](https://github.com/spacedriveapp/spacedrive/assets/77260113/ef6efd89-77bf-4d73-8d84-ca39d8d57c8c)

I've used the `TEXTViewer` Component which we made in (#1184) in that pull request we made **QuickPreview** for Text Files

Additionally, I haven't touched some of these files because there was a confusion regarding the mime type of these files, Although we can just simply use `non-standard mime types` or `text/plain` to achieve this functionality to open these files in Quick Preview.

Best Regards,
Aditya

2023-08-18 14:58 UTC, utkubakir commented
Can we highlight syntax with [prism](https://github.com/PrismJS/prism) or something?

2023-08-19 12:11 UTC, niikeec submitted a review, later dismissed

2023-08-19 12:11 UTC, niikeec commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +
No need for a second `TEXTViewer`, you could use the same one using case fallthrough

2023-08-19 13:50 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +
Done!

2023-08-22 14:51 UTC, utkubakir commented
Looks awesome! Let's use `atom` styles for prism if possible. Should be one of the popular ones.

2023-08-23 12:55 UTC, HeavenVolkoff requested changes

2023-08-23 12:55 UTC, HeavenVolkoff commented on interface/components/CODEViewer.tsx
> +		return link ? (
This whole Link preload hack is not necessary here at all. This is only used in `PDFViewer` because we need to use a native `embed` or `iframe` element that don't support onLoad/onError event listeners. Here you can just do error handling of the `fetch` call and execute the component's onLoad/onError accordingly

2023-08-23 12:55 UTC, HeavenVolkoff commented on interface/components/TEXTViewer.tsx
>  				{quickPreviewContent}
Same here as above, please remove the link preload hack

2023-08-23 12:55 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +									<CODEViewer
Is another component really necessary? Couldn't the code theme's logic be handled inside the `TextViewer` and triggered by a property? Like `code={true}` or `colorTheme={true}` or smth...?

2023-08-23 14:24 UTC, utkubakir commented on interface/components/TEXTViewer.tsx
>  export const TEXTViewer = memo(
Can we rename this and the file to "TextViewer" instead

2023-08-23 14:25 UTC, utkubakir commented on interface/components/TEXTViewer.tsx
> +		}, [quickPreviewContent]);
We shouldn't highlight normal text files, just code files if possible

2023-08-23 14:31 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
> +									<CODEViewer
Done! @PineappleRind  did it!

2023-08-23 14:31 UTC, Raghav-45 commented on interface/components/TEXTViewer.tsx
>  				{quickPreviewContent}
done!

2023-08-23 14:31 UTC, Raghav-45 commented on interface/components/CODEViewer.tsx
> +		return link ? (
Done!

2023-08-23 14:39 UTC, utkubakir commented on apps/web/package.json
> +		"prismjs": "^1.29.0",
This should be in interface

2023-08-23 14:41 UTC, HeavenVolkoff requested changes

2023-08-23 14:41 UTC, HeavenVolkoff commented on interface/components/TextViewer.tsx
> +export interface TEXTViewerProps {
Rename to `TextViewerProps`

2023-08-23 14:41 UTC, HeavenVolkoff commented on interface/components/TextViewer.tsx
> +export const TEXTViewer = memo(
Rename to `TextViewer`

2023-08-23 14:41 UTC, HeavenVolkoff commented on interface/components/TextViewer.tsx
> +			syntaxHighlight && Prism.highlightAll();
Not really a fan of this outside JSX or assignments, please use an `if`

2023-08-23 14:41 UTC, HeavenVolkoff commented on interface/components/TextViewer.tsx
> +				style={{ wordWrap: 'break-word', whiteSpace: 'pre-wrap', colorScheme: 'dark' }}
Please use Tailwind classes instead of directly editing the component style

2023-08-23 14:41 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
>  									<TEXTViewer
Rename to TextViewer

2023-08-23 14:41 UTC, Raghav-45 commented on interface/components/TextViewer.tsx
> +		}, [quickPreviewContent]);
i think using `useeffect` is unnecessary

2023-08-23 14:44 UTC, Raghav-45 commented on interface/components/TextViewer.tsx
> +export interface TEXTViewerProps {
did it

2023-08-23 14:45 UTC, Raghav-45 commented on interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
>  									<TEXTViewer
did it

2023-08-23 15:06 UTC, Raghav-45 commented on apps/web/package.json
> +		"prismjs": "^1.29.0",
did it correctly.

2023-08-26 04:31 UTC, Raghav-45 commented
Huge Respect to @HeavenVolkoff, as Iam New to Rust Language, This Contributions which he is doing seems magical to me. 🤍

2023-08-29 08:20 UTC, utkubakir commented on .prettierrc.js
> -	pluginSearchDirs: false,
why is this removed? @HeavenVolkoff I think it was needed for some plugin if I'm not mistaken

2023-08-29 08:36 UTC, utkubakir commented on .prettierrc.js
> -	pluginSearchDirs: false,
nvm it's been removed on the new prettier versions anyway

2023-08-29 08:36 UTC, utkubakir approved these changes

2023-08-29 10:50 UTC, merged