Disable updater + add feature gate
spacedriveapp/spacedrive pull request #1268
Opened 2023-08-29 16:57 UTC by Brendonovich

Hopefully resolves the release build issues
https://github.com/spacedriveapp/spacedrive/actions/runs/6015255188

2023-08-29 18:29 UTC, HeavenVolkoff requested changes

2023-08-29 18:29 UTC, HeavenVolkoff commented on packages/client/src/core.ts
> +export type MediaData = { id: number; dimensions: number[] | null; media_date: number[] | null; media_location: number[] | null; camera_data: number[] | null; artist: string | null; description: stri
This is an old version of `core.ts`

2023-08-29 18:29 UTC, HeavenVolkoff commented on apps/desktop/src-tauri/scripts/tauri.js
> +    });
We are currently using tabs for all files, no? Should `js` files use spaces instead?

2023-08-30 02:53 UTC, Brendonovich commented on apps/desktop/src-tauri/scripts/tauri.js
> +    });
misconfigured editor moment

2023-08-30 03:25 UTC, HeavenVolkoff approved these changes
LGTM

2023-08-30 03:29 UTC, merged