[ENG-1039] Apply hard `clippy` lints to the entire `ffmpeg` crate
spacedriveapp/spacedrive pull request #1281
Opened 2023-08-31 05:22 UTC by brxken128

This was done in hopes of making it both safer, and slighty more performant (and easier to use in external crates, such as the metadata one!).

We don't have `miri` in CI yet, so a lot of `unsafe` issues may go unnoticed, and this aims to hopefully solve any (if there are/were any to begin with)

2023-08-31 05:31 UTC, oscartbeaumont commented on crates/ffmpeg/src/movie_decoder.rs
> +		// SAFETY: these should always be positive, so clippy doesn't need to alert om them
```suggestion
		// SAFETY: these should always be positive, so clippy doesn't need to alert on them
```

2023-08-31 05:32 UTC, oscartbeaumont commented on crates/ffmpeg/src/movie_decoder.rs
> +	// SAFETY: this should always be positive, so clippy doesn't need to alert om them
```suggestion
	// SAFETY: this should always be positive, so clippy doesn't need to alert on them
```

2023-08-31 05:34 UTC, oscartbeaumont commented on crates/ffmpeg/src/thumbnailer.rs
> +	#[must_use]
I feel like a `#[must_use]` on the new method is a bit pointless.

2023-08-31 05:38 UTC, oscartbeaumont commented on crates/ffmpeg/src/thumbnailer.rs
> +	#[must_use]
That being said I don't like the type implementating `Default` and all of the settings being `#[must_use]` cause all of the methods being `#[must_use]` implies it doesn't have a default.

2023-08-31 05:40 UTC, oscartbeaumont submitted a review, later dismissed
Looks great!

I left a couple of comments but they are all nitpicks so they don't really *need* to block merge.

2023-08-31 06:39 UTC, brxken128 commented on crates/ffmpeg/src/thumbnailer.rs
> +	#[must_use]
I agree, I was just following clippy in this instance but we can probably alter it to require not so many `#[must_use]`s. I myself don't dislike them and use them where possible/practical (or whenever clippy tells me to, really), but I can see where you're coming from and I'll try to clean some of that up.

2023-08-31 06:52 UTC, brxken128 commented on crates/ffmpeg/src/thumbnailer.rs
> +	#[must_use]
I think that should do it - I just marked the whole type as `#[must_use]` instead, so all of the sub-functions don't need to worry about it.

2023-08-31 06:54 UTC, oscartbeaumont commented on crates/ffmpeg/src/thumbnailer.rs
> +	#[must_use]
I think I am wrong here about the combination of `Default` and `#[must_use]` being a problem. I thought `#[must_use]` applied to the function (e.g. you must call all the functions) but actually, it applies to the return values (Eg. must use return type) which makes sense.

```rust
ThumbnailerBuilder::default().some_method(); // Would warn about must_use.

ThumbnailerBuilder::default().some_method().build(); // Would be valid.

2023-09-04 15:08 UTC, Brendonovich requested changes

2023-09-04 15:12 UTC, brxken128 commented on core/src/object/media/thumbnail/mod.rs
> +#[cfg(all(feature = "heif", not(target_os = "linux")))]
Yeah we should probably just make them always available instead of splitting them up like this.

My next PR entirely cleans this up, so we can fix it now or just wait for that to be merged (which won't be too long).

2023-09-05 07:35 UTC, Brendonovich approved these changes

2023-09-05 07:40 UTC, merged