Cleanup classNames
spacedriveapp/spacedrive pull request #1334
Opened 2023-09-11 17:07 UTC by tomheaton

- remove redundant brackets
- use `clsx`
- matching quotes type

2023-09-11 18:07 UTC, utkubakir requested changes

2023-09-11 18:07 UTC, utkubakir commented on interface/app/$libraryId/TopBar/TopBarOptions.tsx
> +				)}
clsx is not required here

2023-09-11 18:07 UTC, utkubakir commented on interface/app/$libraryId/overview/index.tsx
> +					)}
clsx is not required here

2023-09-11 18:07 UTC, utkubakir commented on interface/app/$libraryId/TopBar/TopBarOptions.tsx
> +										: 'none';
does prettier respect this? I feel like it will just format it back to how it is.

2023-09-11 18:25 UTC, tomheaton commented
changes made!

2023-09-12 03:24 UTC, oscartbeaumont approved these changes

2023-09-14 14:05 UTC, utkubakir approved these changes

2023-09-14 14:12 UTC, utkubakir commented
Can we fix types?

2023-09-14 14:30 UTC, tomheaton commented
where is this?

2023-09-14 14:32 UTC, utkubakir commented
> where is this?

https://github.com/spacedriveapp/spacedrive/actions/runs/6186597174/job/16794620365?pr=1334
https://github.com/spacedriveapp/spacedrive/actions/runs/6186597174/job/16794619516?pr=1334

2023-09-15 13:44 UTC, utkubakir approved these changes

2023-09-15 18:48 UTC, utkubakir approved these changes

2023-09-18 19:45 UTC, utkubakir commented
is this even worth it anymore 😆

2023-09-18 19:45 UTC, closed without merging

2023-09-18 21:19 UTC, tomheaton commented
Aha yeah, sorry I merged main using web and missed the duplicate imports.