New functions to open ephemeral files
spacedriveapp/spacedrive pull request #1401
Opened 2023-09-29 04:47 UTC by fogodev

Closes #(issue)

2023-10-04 06:35 UTC, HeavenVolkoff commented on CONTRIBUTING.md
> +  If necessary, the webview devtools can be opened by pressing Ctrl + Shift + I in the desktop app:
Nitpick, but can you remove the dangling `:`?

2023-10-04 06:43 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/ContextMenu/SharedItems.tsx
> +import type {} from '@sd/client'; // tsc requires this import due to global types defined on it
Nitpick, can you put the comment on top of the import?

2023-10-04 07:06 UTC, HeavenVolkoff requested changes

2023-10-04 08:39 UTC, utkubakir commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +	if (filePathData !== null) {
or just `!filePathData`

2023-10-04 23:44 UTC, fogodev commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +						<MetaData icon={Snowflake} label="Content ID" value={casId} />
Above this part has a check for `objectData`. I removed the `isNonIndexed` check because it was redundant as this whole block is exclusive for `objectData` info

2023-10-04 23:49 UTC, fogodev commented on interface/app/$libraryId/Explorer/Inspector/index.tsx
> +	if (filePathData !== null) {
I fucking hate implicit conversions, lol :v 
This is why I removed some `!!` existing somewhere in this code. But I agree with the `null` vs `undefined` duality and will change `!==` to `!=`

2023-10-05 07:21 UTC, HeavenVolkoff approved these changes

2023-10-05 07:24 UTC, merged