[ENG-1175] File named " " in Finder renders name incorrectly
spacedriveapp/spacedrive pull request #1429
Opened 2023-10-04 04:08 UTC by oscartbeaumont

Changes:
 - [ ] Fix styling of " " file name
 - [ ] Don't trim when renaming

2023-10-04 07:12 UTC, HeavenVolkoff requested changes

2023-10-04 07:12 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx
> +			if (newName === undefined || newName === '') {
`ref.current` can be null, which would propagate to `newName` due to the `.?`, better to change `newName === undefined` to `newName == null` or simply do `if (!newName)` as that will catch all falsy values

2023-10-04 08:11 UTC, niikeec requested changes

2023-10-04 08:11 UTC, niikeec commented on interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx
> +			if (!newName || newName === '') {
`!newName` should be enough here

2023-10-06 08:51 UTC, oscartbeaumont commented
@niikeec said these change was copied onto another PR so closing this.

2023-10-06 08:51 UTC, closed without merging