[ENG-1196] Allow `WEBUI_PORT` to be specified for host-networked containers
spacedriveapp/spacedrive pull request #1444
Opened 2023-10-08 19:39 UTC by brxken128

This also changes the Dockerfile to follow some more of the best practices (it's missing a few but it's a lot better, although I may have broke something along the way).

I also cleaned up the other CI files, as `trunk` was emitting quite a few lint warnings - I'm not sure what effects my changes will have, we will have to see.

**Please don't merge or approve this yet, it's experimental but not a draft so CI still runs**

2023-10-08 21:02 UTC, HeavenVolkoff requested changes

2023-10-08 21:02 UTC, HeavenVolkoff commented on apps/server/docker/entrypoint.sh
> -if [ -n "${TZ:-}" ]; then
The colon here is required, as it means substitute when unset or null, without a color it only substitutes when unset.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02
<img width="1512" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/9082460/c90cd3a1-f6b6-4aa1-87dd-5225d36b9595">

2023-10-08 21:02 UTC, HeavenVolkoff commented on apps/server/docker/entrypoint.sh
> -if [ -n "${1:-}" ] && [ "${1#-}" = "${1}" ] \
The colon here is required, as it means substitute when unset or null, without a color it only substitutes when unset.

2023-10-09 13:36 UTC, brxken128 commented on apps/server/docker/Dockerfile
> +RUN ["/bin/bash", "-c", "set -o pipefail && wget -qO- https://sh.rustup.rs | sh -s -- -yq --profile minimal"]
https://docs.docker.com/develop/develop-images/instructions/#using-pipes

2023-10-09 13:37 UTC, brxken128 commented on apps/server/docker/Dockerfile
> +HEALTHCHECK NONE
Best practices recommend at least defining a `HEALTHCHECK` per layer.

2023-10-09 13:38 UTC, brxken128 commented on apps/server/docker/entrypoint.sh
> -if [ -n "${TZ:-}" ]; then
I don't recall touching this line, maybe auto-formatting

2023-10-09 13:38 UTC, closed without merging

2023-10-09 13:42 UTC, brxken128 commented
Just going to close this, all I was trying to do was allow exposing the WEBUI on a different port for people who use host networking so their container can see other nodes wtithout having to worry about ports, and so that 8080 doesn't clash with another container (which will almost 100% happen).

Was very clearly a WIP as I'd mentioned at the start, only reason it wasn't a draft is because I wanted CI to keep running.

2023-10-09 21:25 UTC, HeavenVolkoff commented
> Just going to close this, all I was trying to do was allow exposing the WEBUI on a different port for people who use host networking so their container can see other nodes wtithout having to worry about ports, and so that 8080 doesn't clash with another container (which will almost 100% happen).

I think this is a valid addition, as almost all images have a similar option exposed. Could we re-open this?