Update README.md
spacedriveapp/spacedrive pull request #1521
Opened 2023-10-12 02:26 UTC by Adamkaram

adding links for available realses

2023-10-12 02:49 UTC, brxken128 submitted a review, later dismissed
The formatting is pretty inconsistent, in both tabs and OS names. I do agree that the download links should be added to the README now though.

2023-10-12 02:49 UTC, brxken128 commented on README.md
> +   <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/x86_64" >macOSIntel</a> ·
MacOS has both ARMv8 (Aarch64, also known as Apple Silicon) and x86_64 builds, and the formatting is incorrect. You could use something such as this:

```markdown
<details>
    <summary>MacOS</summary>
    · <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/aarch64">Apple Silicon</a>
    <br />
    · <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/x86_64">Intel</a>
</details>
```

Or you could have two separate links, one for each, but using a different delimiter than `·`.

```markdown
MacOS - <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/aarch64">Apple Silicon</a> | <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/x86_64">Intel</a> ·
```

I think the second option would be preferable.

2023-10-12 02:49 UTC, brxken128 commented on README.md
> +		 <a href="" >Android</a> ·
These shouldn't be clickable as no releases are available.

2023-10-12 02:49 UTC, brxken128 commented on README.md
> +    <i>~ Links for (IOS · watchOS · Android ) will be added once a release is available. ~</i>
`IOS` should be formatted as `iOS`, and `watchOS` as `WatchOS`.

2023-10-12 02:51 UTC, mmattbtw requested changes

2023-10-12 02:51 UTC, mmattbtw commented on README.md
> +     <a href="" >IOS</a> ·
```suggestion
     <a href="" >iOS</a> ·
```

correct capitalization :-)

2023-10-12 02:51 UTC, mmattbtw commented on README.md
> +   <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/x86_64" >macOSIntel</a> ·
imo do 
> macOS ([Intel]()/[Apple Silicon]()]

2023-10-12 02:51 UTC, mmattbtw commented on README.md
> +	 <p align="center">
useless indentation change?

2023-10-12 02:51 UTC, mmattbtw commented on README.md
> +    <i>~ Links for (IOS · watchOS · Android ) will be added once a release is available. ~</i>
```suggestion
    <i>~ Links for (iOS · watchOS · Android ) will be added once a release is available. ~</i>
```
correct capitalization :-)

2023-10-12 02:52 UTC, brxken128 commented
@mmattbtw I got you beat by just a second there LMAO

2023-10-17 09:09 UTC, Adamkaram commented on README.md
> +   <a href="https://www.spacedrive.com/api/releases/desktop/stable/darwin/x86_64" >macOSIntel</a> ·
done

2023-10-17 09:10 UTC, Adamkaram commented on README.md
> +		 <a href="" >Android</a> ·
done

2023-10-17 09:12 UTC, Adamkaram reviewed
everything is done now

2023-10-17 09:12 UTC, Adamkaram commented on README.md
> +    <i>~ Links for (IOS · watchOS · Android ) will be added once a release is available. ~</i>
yes i didn't notice that sorry

2023-10-18 05:56 UTC, Brendonovich approved these changes

2023-10-18 06:03 UTC, merged