Smarter release workflow
spacedriveapp/spacedrive pull request #1525
Opened 2023-10-12 04:32 UTC by Brendonovich

This PR introduces a new publish action written in JS that will for now run alongside the existing one. It should take care of renaming assets to those expected by the Download & Update APIs, and can automatically upload assets to a new/existing release if the workflow was started for a tag.

2023-10-12 05:29 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts-new/tsconfig.json
Nitpick: remove the commented props, no real gain in leaving them, TS docs is a better place to read about what each one does anyway

2023-10-12 05:30 UTC, Brendonovich commented on .github/actions/publish-artifacts-new/tsconfig.json
yeah can do, they're just included from `pnpm tsc --init`

2023-10-12 05:34 UTC, HeavenVolkoff commented on .github/workflows/release.yml
>            profile: release
I think we can just drop this, the newer one is better

2023-10-12 05:35 UTC, HeavenVolkoff commented
LGTM, just want to do a test release before merging to make sure it works fine

2023-10-12 05:49 UTC, Brendonovich commented on .github/workflows/release.yml
>            profile: release
I'd rather we keep both around just to make sure, means we can test it in prod

2023-10-12 06:57 UTC, HeavenVolkoff requested changes

2023-10-12 06:57 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts/action.yml
The build failed, I think the action was replaced by mistake with the workflow content

2023-10-12 06:59 UTC, Brendonovich commented on .github/actions/publish-artifacts/action.yml
lol

2023-10-12 19:13 UTC, HeavenVolkoff commented on .github/workflows/release.yml
> +      - name: Publish Artifcats
🤣

2023-10-12 22:10 UTC, HeavenVolkoff requested changes

2023-10-12 22:10 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts/index.ts
> +			await client.uploadArtifact(artifactName, [`Spacedrive-Updater-*`], ARTIFACTS_DIR);
I think this is failing to find the updater file, according to the logs in the last 2 test relases runs. We can get better logs, but we need to se the following envvar in the repo settings: `ACTIONS_STEP_DEBUG=true`

2023-10-13 01:55 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts/index.ts
> +			await client.uploadArtifact(artifactName, [`Spacedrive-Updater-*`], ARTIFACTS_DIR);
![image](https://github.com/spacedriveapp/spacedrive/assets/9082460/16cc4258-8aaf-44dc-96f5-401a46ff9986)

2023-10-13 01:56 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts/index.ts
> +			await client.uploadArtifact(artifactName, [`Spacedrive-Updater-*`], ARTIFACTS_DIR);
`client.uploadArtifact` doesn't accept globs as paths

2023-10-13 02:33 UTC, Brendonovich commented on .github/workflows/release.yml
> +      - name: Publish Artifcats
🐈

2023-10-13 02:36 UTC, HeavenVolkoff requested changes

2023-10-13 02:36 UTC, HeavenVolkoff commented on .github/actions/publish-artifacts/index.ts
> +		await client.uploadArtifact(ARTIFACT_NAME, [artifactPath], './');
If I understood the API correctly, `rootDirectory`  defines how the structure of the zip will be, so putting `'.'` here would mean the whole `artifactPath` will be included in the zip, no?

https://github.com/actions/toolkit/tree/@actions/artifact@1.1.1/packages/artifact#upload-an-artifact

2023-10-13 04:15 UTC, Brendonovich commented on .github/actions/publish-artifacts/index.ts
> +		await client.uploadArtifact(ARTIFACT_NAME, [artifactPath], './');
Yep seems like that's the case

2023-10-13 08:55 UTC, utkubakir approved these changes

2023-10-13 08:55 UTC, jamiepine approved these changes

2023-10-13 08:59 UTC, merged