Enable thumbnail support for webp images
spacedriveapp/spacedrive pull request #1634
Opened 2023-10-19 19:32 UTC by HeavenVolkoff

Closes #1614

2023-10-19 21:50 UTC, brxken128 requested changes
Easy fix for sure, just needs the `webp` crate removing from the `Cargo.toml` file as it's entirely unused iirc.

2023-10-19 21:50 UTC, brxken128 commented on crates/images/src/consts.rs
> +	Webp,
This is fine for now, but when the image conversion stuff is fixed then it'll need to be blacklisted, unless we also use the external `webp` crate (but then the extension should be removed from `GENERIC_EXTENSIONS` and into its own thing). The `webp` crate can be removed from the `Cargo.toml` here as we're only decoding - I had planned to add full encode/decode support with it so we can convert to and from `webp` but this gets thumbnails working.

The image conversion UI stuff also builds on top of this, and implements rules for certain images (e.g. they can be converted to another format, but not the other way around).

2023-10-19 21:56 UTC, fogodev submitted a review, later dismissed

2023-10-20 03:32 UTC, brxken128 approved these changes

2023-10-20 03:39 UTC, merged