Clarify error that occurs when getting the hash of an on-demand file
spacedriveapp/spacedrive pull request #1722
Opened 2023-11-02 14:55 UTC by Carterpersall

- Clarifies error that occurs when attempting to read the metadata from an on-demand file
  - Involves issue #1721 but does not solve it

Current Error:
```
2023-11-01T19:29:02.533749Z ERROR sd_core::object::file_identifier: Failed to extract file metadata: FileIOError {
    path: "C:\\Users\\xxxxx\\OneDrive\\Document.docx",
    source: Os {
        code: 362,
        kind: Uncategorized,
        message: "The cloud file provider is not running.",
    },
    maybe_context: None,
}
```
New Error:
```
2023-11-01T15:58:27.994181Z ERROR sd_core::object::file_identifier: Failed to extract metadata from on-demand file: FileIOError {
    path: "C:\\Users\\xxxxx\\OneDrive\\Document.docx",
    source: Os {
        code: 362,
        kind: Uncategorized,
        message: "The cloud file provider is not running.",
    },
    maybe_context: None,
}
```

2023-11-12 19:32 UTC, fogodev requested changes
Sorry for the delay reviewing this one, went totally under my radar.

2023-11-12 19:32 UTC, fogodev commented on core/src/object/file_identifier/mod.rs
> +						}
As this is a specific windows error, can you put this part in a conditional compilation section. Something like 

```rust
#[cfg(target_os = "windows")]
{
    if e.source
        .raw_os_error()
        .map_or(false, |code| code == 362)
    {
        error!("Failed to extract metadata from on-demand file: {e:#?}");
    } else {
        error!("Failed to extract file metadata: {e:#?}");
    }
}

#[cfg(not(target_os = "windows"))]
{
    error!("Failed to extract file metadata: {e:#?}");
}
```

The `map` and `unwrap_or` can also be simplified on a `map_or`

2023-11-13 16:22 UTC, Carterpersall commented on core/src/object/file_identifier/mod.rs
> +						}
>can you put this part in a conditional compilation section
Sure, I'm not sure why I didn't do this in the first place.

>The `map` and `unwrap_or` can also be simplified on a `map_or`
I have no idea why I didn't know `map_or` was a thing, that's much better than what I had

2023-11-13 17:39 UTC, fogodev approved these changes

2023-11-13 17:43 UTC, merged