added it locale, added it entry
spacedriveapp/spacedrive pull request #2066
Opened 2024-02-07 17:03 UTC by gekoxyz

added the italian translation by adding the /interface/locales/it/common.json file and the entry in settings.json and general.tsx

this helps More languages support #1820

2024-02-07 17:26 UTC, utkubakir commented
There should be 424 keys total, you might wanna update your branch

2024-02-08 20:34 UTC, mercxry requested changes
I think that the json is missing 57 keys that are committed in the main branch as mentioned by Utku, would you be able to merge those here?

A simple git merge won't do it since the "en" and "it" json files are different 🙃

Per il resto buon lavoro 👏

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"library_name": "Nome della Libreria",
```suggestion
	"library_name": "Nome Libreria",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"local_locations": "Locations Locali",
```suggestion
	"local_locations": "Posizioni Locali",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"location_is_already_linked": "La Location è già linkata",
```suggestion
	"location_is_already_linked": "La Posizione è già collegata",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"location_offline_tooltip": "La Location è offline, puoi comunque navigare e organizzare.",
```suggestion
	"location_offline_tooltip": "La Posizione è offline, puoi comunque navigare e organizzare.",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"location_type": "Location Type",
```suggestion
	"location_type": "Tipo Posizione",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"locations": "Locations",
```suggestion
	"locations": "Posizioni",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"log_in_with_browser": "Log in con il browser",
```suggestion
	"log_in_with_browser": "Accedi con il browser",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"media_view_notice_description": "Scopri facilmente foto e video, Media View mostrerà i risultati a partire dalla posizione corrente, comprese le sottodirectory.",
```suggestion
	"media_view_notice_description": "Scopri facilmente foto e video, Media View mostrerà i risultati a partire dalla posizione corrente, comprese le sottocartelle.",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"navigate_back": "Naviga all'indietro",
```suggestion
	"navigate_back": "Naviga indietro",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"rescan_directory": "Scansiona di nuovo la Directory",
```suggestion
	"rescan_directory": "Scansiona di nuovo la Cartella",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"secure_delete": "Cancellazione sicura",
```suggestion
	"secure_delete": "Eliminazione sicura",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"show_details": "Mostra i dettagli",
```suggestion
	"show_details": "Mostra dettagli",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"show_hidden_files": "Mostra i file nascosti",
```suggestion
	"show_hidden_files": "Mostra file nascosti",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"spacedrop_a_file": "Spacedroppa un file",
🇮🇹  Bella questa!!! 👏 😂

---

🇺🇸 Nice one!!! 👏 😂

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"thumbnailer_cpu_usage_description": "Limita la quantità di CPU che può essere usata per l'elaborazione di miniature in background.",
```suggestion
	"thumbnailer_cpu_usage_description": "Limita la quantità di CPU che può essere usata per l'elaborazione delle anteprime in background.",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"unnamed_location": "Posizioni senza nome",
```suggestion
	"unnamed_location": "Posizione senza nome",
```

2024-02-08 20:34 UTC, mercxry commented on interface/locales/it/common.json
> +	"want_to_do_this_later": "Vuoi vederlo dopo?",
```suggestion
	"want_to_do_this_later": "Vuoi farlo più tardi?",
```

2024-02-08 20:34 UTC, mercxry commented on project.inlang/settings.json
> +	"languageTags": ["en", "de", "tr", "es", "fr", "nl", "zh-CN", "zh-TW", "it"],
📈 
```suggestion
	"languageTags": ["en", "de", "es", "fr", "it", "tr", "nl", "zh-CN", "zh-TW"],
```

2024-02-08 20:34 UTC, mercxry commented on interface/app/$libraryId/settings/client/general.tsx
> +	{ value: 'it', label: "Italiano"}
Move this up with the other European languages?
I would put it above Turkish, since Italian has more speakers worldwide :)

2024-02-08 20:40 UTC, utkubakir commented on interface/app/$libraryId/settings/client/general.tsx
> +	{ value: 'it', label: "Italiano"}
Pretty sure, turkish is more popular :) Implemented sorting (by label) on #2071 anyway so it doesn't really matter where it is

2024-02-08 22:27 UTC, gekoxyz commented
in my opinion @mercxry suggestions seem really good, they improve a lot of wording and add the keys which were added while i was finishing the translation.

2024-02-09 02:56 UTC, utkubakir commented on interface/locales/it/common.json
> +	"spacedrop_a_file": "Spacedroppa un file",
🤞

2024-02-09 02:57 UTC, utkubakir commented
@gekoxyz I committed the suggestions in, I believe there are still some keys missing. Can we add those too so we can merge this pr?

2024-02-26 15:18 UTC, utkubakir approved these changes

2024-02-26 15:23 UTC, merged