[MOB-70] Update Folder Names when Renamed on iOS
spacedriveapp/spacedrive pull request #2225
Opened 2024-03-20 18:49 UTC by Rocky43007

If a folder has been renamed externally on iOS, the core has no idea how to handle this event, throwing errors and disappearing the folder. 

Looks like it's due to iOS sending a Create Event with the new Folder instead of sending it as a Rename Event.

2024-03-21 23:39 UTC, fogodev requested changes

2024-03-21 23:39 UTC, fogodev commented on core/src/location/manager/watcher/ios.rs
> +			self.rename_event_queue.remove(&key.clone());
Shouldn't here be just `self.rename_event_queue.remove(key);` as `key` is already a reference?

2024-03-21 23:39 UTC, fogodev commented on core/src/location/manager/watcher/ios.rs
> +			let new_path_name = Path::new(key).file_name().unwrap();
`key` is a `&PathBuf` here, so `key.file_name()` should do, if I'm not mistaken.

2024-03-21 23:39 UTC, fogodev commented on core/src/location/manager/watcher/ios.rs
> +			let new_path_name_string = Some(new_path_name.to_str().unwrap().to_string());
Also try to avoid these `unwrap`s if possible, yon can put a `NonUtf8PathError` variant on `LocationManagerError` and return this error here. I don't know if paths on iOS as guaranteed to always be valid UTF-8. If they are, then you can put it written on a `expect(...)` message.

2024-03-21 23:59 UTC, Rocky43007 commented on core/src/location/manager/watcher/ios.rs
> +			self.rename_event_queue.remove(&key.clone());
No, because with `key`, we get the error:

```
cannot borrow `self.rename_event_queue` as mutable because it is also borrowed as immutable
mutable borrow occurs here
ios.rs(319, 27): immutable borrow occurs here
ios.rs(335, 28): immutable borrow later used by call
```

And with `&key`, it's:
```
the trait bound `std::path::PathBuf: std::borrow::Borrow<&std::path::PathBuf>` is not satisfied
the trait `std::borrow::Borrow<std::path::Path>` is implemented for `std::path::PathBuf`
for that trait implementation, expected `std::path::Path`, found `&std::path::PathBuf`
ios.rs(335, 28): required by a bound introduced by this call
map.rs(1157, 12): required by a bound in `std::collections::HashMap::<K, V, S>::remove`
```

2024-03-22 00:00 UTC, Rocky43007 commented on core/src/location/manager/watcher/ios.rs
> +			let new_path_name = Path::new(key).file_name().unwrap();
Huh, that does work.

2024-03-22 00:01 UTC, Rocky43007 commented on core/src/location/manager/watcher/ios.rs
> +			let new_path_name_string = Some(new_path_name.to_str().unwrap().to_string());
It looks like iOS paths are always UTF-8, so I'll add `expect()` instead of `unwrap()`.

2024-03-22 02:09 UTC, fogodev commented on core/src/location/manager/watcher/ios.rs
> +			self.rename_event_queue.remove(&key.clone());
I think that [this](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.as_path) will do the trick perhaps?

2024-03-22 02:26 UTC, fogodev commented on core/src/location/manager/watcher/ios.rs
> +			self.rename_event_queue.remove(&key.clone());
Never mind lol, it seems we can't use a reference from inside a hashmap to remove the element in the hashmap

2024-03-22 18:12 UTC, Rocky43007 commented
Working on a fix to multiple rename events being set at the same time because otherwise, it's broken and crashes.

2024-10-31 01:47 UTC, closed without merging