[ENG-1483] Right Click -> New File
spacedriveapp/spacedrive pull request #2276
Opened 2024-04-03 01:13 UTC by Rocky43007

Creates an empty file called `Untitled` and adds `(1) -> (n)` for n number of files with the same `Untitled` name.

![Screenshot 2024-04-02 at 9 09 08 PM](https://github.com/spacedriveapp/spacedrive/assets/11457760/1ac0be18-d8a4-48cf-882b-c55d25207276)

2024-04-03 02:48 UTC, utkubakir commented
Let's merge new folder and new file as a dropdown, can reference Windows as the experience. Would be nice to have Notepad too

2024-04-03 16:35 UTC, utkubakir commented
<img width="561" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/74243531/aa18668a-d2cf-4af3-87b1-1ccb60de82bf">
Can't create files

2024-04-03 16:38 UTC, Rocky43007 commented
> Also what's the difference between file and empty file?

That should have been `Text File`, sorry.



> Can't create files

Looks like I messed up on a type check. I'm looking into why.

2024-04-03 17:02 UTC, utkubakir requested changes

2024-04-03 17:02 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ParentContextMenu.tsx
> +			toast.error({ title: 'Error creating file', body: `Error: ${e}.` });
Don't need Error: here as we already have it

2024-04-03 17:02 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ParentContextMenu.tsx
> +			toast.success({ title: `Created new file "${file}"` });
i18n

2024-04-03 17:02 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ParentContextMenu.tsx
> +			toast.error({ title: 'Error creating file', body: `Error: ${e}.` });
Don't need Error: here as we already have it

2024-04-03 17:02 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ParentContextMenu.tsx
> +			toast.success({ title: `Created new file "${folder}"` });
i18n

2024-04-03 17:02 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ParentContextMenu.tsx
> +							label={t('new_file')}
new_note_file or new_text_file

2024-04-03 17:02 UTC, utkubakir commented on interface/locales/en/common.json
> +  "new_folder": "Folder",
just folder if you are not gonna add "New" to front. (Same issue with others. i18n keys should be descriptive)

2024-04-04 04:18 UTC, utkubakir approved these changes

2024-04-04 04:23 UTC, merged