Media metadata extraction
spacedriveapp/spacedrive pull request #2285
Opened 2024-04-05 00:24 UTC by HeavenVolkoff

Extract media (video/audio) metadata with ffmpeg and present on frontend

WIP: Right now this only includes a POC in C for extracting metadata with ffmpeg, I am working rn in porting the code to Rust and integrating with the frontend

2024-05-08 16:19 UTC, fogodev requested changes

2024-05-08 16:19 UTC, fogodev commented on crates/ffmpeg/Cargo.toml
> +rust-version = "1.77"
The same I mentioned about core's `Cargo.toml`

2024-05-08 16:19 UTC, fogodev commented on crates/prisma/src/lib.rs
> +#![recursion_limit = "256"]
Same as the other ones

2024-05-08 18:23 UTC, HeavenVolkoff commented on core/crates/prisma-helpers/src/lib.rs
> +#![recursion_limit = "256"]
Yes, running tests and building the server breaks if these higher recursion limits are not defined

2024-05-08 18:23 UTC, HeavenVolkoff commented on core/src/lib.rs
> +#![recursion_limit = "256"]
Yes, running tests and building the server breaks if these higher recursion limits are not defined

2024-05-08 18:23 UTC, HeavenVolkoff commented on core/crates/heavy-lifting/src/job_system/job.rs
> +use tokio_stream::StreamExt;
Probably a merge mistake, will revert

2024-05-08 18:24 UTC, HeavenVolkoff commented on crates/prisma/src/lib.rs
> +#![recursion_limit = "256"]
Yes, running tests and building the server breaks if these higher recursion limits are not defined

2024-05-08 22:13 UTC, fogodev approved these changes

2024-05-09 02:01 UTC, fogodev approved these changes
LGTM

2024-05-09 02:27 UTC, merged