Docs update
spacedriveapp/spacedrive pull request #2317
Opened 2024-04-12 04:40 UTC by jamiepine

Closes #(issue)

2024-04-12 18:17 UTC, utkubakir requested changes

2024-04-12 18:17 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/sections/Library/index.tsx
> +			</SidebarLink>
disable or add a coming soon icon or toast pls

2024-04-12 18:17 UTC, utkubakir commented on apps/landing/src/app/roadmap/items.ts
> +		subtext: 'March 2024',
bump date

2024-04-18 11:28 UTC, artsiom-voitas commented
![image](https://github.com/spacedriveapp/spacedrive/assets/85301789/d395d406-6740-4ad0-9fd6-ebbd0c7c95fa)
Check "Mobile app TestFlight" duplicate.

2024-04-19 14:47 UTC, utkubakir commented on packages/test-files
let's remove this

2024-04-23 10:20 UTC, 0xBA5E64 reviewed
Here are some general suggestions as well as spelling corrections. I tried to keep things as close as possible to what'd been written before, but admittedly took liberty with some.

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/importing-photos.mdx
> +Currently you can add the SD card as a location and copy the files to a specific folder, in an upcoming release we will ship a dedicated interface for importing media, with option to exclude already
```suggestion
Currently you can add the SD card as a location and copy the files to a specific folder. In an upcoming release we will ship a dedicated interface for importing media, with option to exclude already imported media. It will also use your preference for photo storage and place the new media in the designated folder.
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/interface.mdx
> +The explorer is comprised of different views, List, Grid and Media View, with column and tree views on the way. The explorer can be used to navigate Locations, Tags, Local drives, Network drives, and
```suggestion
The explorer is comprised of different views; List, Grid and Media View, with column and tree views on the way. The explorer can be used to navigate Locations, Tags, Local drives, Network drives, and even peer Spacedrive nodes.
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/jobs.mdx
> +Up to 3 jobs can run simultaneously, this might be configurable in the future. Certain jobs like thumbnailing and labeling have slider control for CPU usage in the general settings page.
```suggestion
Up to 3 jobs can run simultaneously, although this may be configurable in the future. More CPU-intensive jobs like thumbnailing and labelling have an upper limit for CPU usage set in the General settings page.
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/library-setup.mdx
> +_\*Locking and encyrption coming in a later update._
```suggestion
_\*Locking and encryption coming in a later update._
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/locations.mdx
> +When a Location is added it is immediately scanned. The scan happens via several phases as [Jobs](/docs/product/guides/jobs).
```suggestion
When a Location is added it is immediately scanned. The scan happens in several phases as [Jobs](/docs/product/guides/jobs).
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/quick-preview.mdx
> +Quick Preview allows you to quickly preview a file in Spacedrive, it supports a wide range of formats and growing.
```suggestion
Quick Preview allows you to quickly preview a file in Spacedrive, it supports a wide and growing range of formats.
```

2024-04-23 10:20 UTC, 0xBA5E64 commented on docs/product/guides/quick-preview.mdx
> +It can be accessed by pressing the spacebar while selected on a file, a native behaviour for macOS users.
```suggestion
It can be accessed by pressing the spacebar while selected on a file, as per native behaviour for macOS.
```

2024-04-23 11:19 UTC, jamiepine commented on docs/developers/architecture/spaces.mdx
> +Objects can be added to a Space manually, or by matching a defined ruleset, similar to Tags. This mechanism is also used for the default Spaces such as favorites, photos, videos, documents and screen
It's a little confusing, I'll try to reword!

2024-04-23 11:23 UTC, jamiepine commented on docs/product/guides/importing-photos.mdx
> +Spacedrive is designed to be a central location for all your media. This means you can import photos from a variety of sources, including your local hard drive, Apple Photos, Google Photos and more.
local storage could be confused with localStorage, no?

2024-04-23 11:52 UTC, 0xBA5E64 commented on docs/product/guides/importing-photos.mdx
> +Spacedrive is designed to be a central location for all your media. This means you can import photos from a variety of sources, including your local hard drive, Apple Photos, Google Photos and more.
Hm, not sure what you're referring to by `localStorage` in this context, the Web API? I suppose that _might_ be a concern, but as this is a user-facing guide I think most people would understand the meaning of "local storage" in this context, perhaps even better than "hard drives", to refer to data stored locally on their machine.

I mostly meant to move away from "hard drive" as that usually refers to mechanical drives, which are less and less common nowadays. I suppose simply "drive" could be used instead too but that might also conflict with Google Drive.

Decisions, decisions...

2024-04-23 12:14 UTC, jamiepine commented on docs/product/guides/importing-photos.mdx
> +Spacedrive is designed to be a central location for all your media. This means you can import photos from a variety of sources, including your local hard drive, Apple Photos, Google Photos and more.
Turns out while merging I already replaced this paragraph anyway, I agree on the term "hard drive", very dated and somewhat incorrect.

2024-04-23 13:06 UTC, 0xBA5E64 commented on docs/product/guides/clouds.mdx
> +Connecting cloud services with your Spacedrive library will allow you to create [Cloud Locations](). This will allow you not only to search your clouds while offline, but also ensure you have local c
```suggestion
Connecting cloud services with your Spacedrive library will allow you to create [Cloud Locations](). This will allow you to not only search your cloud storage while offline, but also ensure you have local copies of your cloud files, or offload them if space is an issue.
```

2024-04-23 13:17 UTC, 0xBA5E64 commented on docs/product/guides/importing-photos.mdx
> +Spacedrive is designed to be a central location for all your media, with [Media View](), viewing and managing your photos easy, with a variety of filters and sorting options just like traditional pho
This segment in general is a bit weird, I think, and so we might be better off rephrasing it to:
```suggestion
Spacedrive is designed to be a central location for all your media. The [Media View]() makes viewing and managing your photos easy with a variety of filtering and sorting options. To compliment this we also have (and are working on) a variety of ways to import your photos.
```

2024-05-14 21:41 UTC, myung03 approved these changes

2024-05-15 00:50 UTC, merged