[ENG-293] Tag assign mode
spacedriveapp/spacedrive pull request #2462
Opened 2024-05-08 05:04 UTC by iLynxcat

This PR introduces **tag assign mode** to Spacedrive.

Details to come.

Closes #2350

2024-06-06 00:07 UTC, myung03 requested changes
really cool functionality! just some styling issues and visual updates. lmk if you have any questions about any of my suggestions/if you disagree with any of them, would love to learn more about your thought process or explain any confusion :))

2024-06-06 00:07 UTC, myung03 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +const TagItem = ({
this should be refactored to another file since this file is already huge

2024-06-06 00:07 UTC, myung03 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
the italics look a bit strange, maybe just normal text is fine. But on that note I think this should be a tool tip instead, since it makes the tag bar unnecessarily large. Maybe putting a tooltip on the right hand side of the bar, or somewhere else that makes sense.

2024-06-06 00:07 UTC, myung03 commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
this wording is rather misleading because it only allows you to assign number keys 1-9 to tags, so it might be beneficial to specify that

2024-06-06 00:07 UTC, myung03 commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
I didn't test with more than 9 tags though so I definitely may be wrong here!

2024-06-06 15:04 UTC, utkubakir commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
curious what does this part translates to: `$t(file, { \"count\": {{file_count}} })`. Looks weird to have it on i18n

2024-06-07 06:11 UTC, iLynxcat commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
changes to the proper singular/plural form of "file"/"files" based on the file_count number

2024-06-16 03:08 UTC, iLynxcat commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
I just think a bar of tags appearing mysteriously at the bottom with no upfront text is going to be very confusing for users who aren't familiar with the feature. I'd be open to adding an option to _hide_ the hint text or other ideas.

2024-06-16 03:39 UTC, iLynxcat commented on interface/app/$libraryId/Explorer/TopBarOptions.tsx
> -			toolTipLabel: t('key_manager'),
I have no clue what happened here! Might have been a merge issue

2024-06-17 08:18 UTC, ameer2468 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
I think the text for now is fine - altho I do vision in another iteration we can improve otherwise.

My last commit has made visual improvements that I think were needed.

<img width="1512" alt="Screenshot 2024-06-17 at 11 18 07 AM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/165baa8e-e315-4291-8778-db049ea978f3">

2024-06-17 08:24 UTC, ameer2468 commented on interface/app/$libraryId/Explorer/ExplorerPathBar.tsx
I do like this, but i'm against this due to native experiences not performing animations for these features.

Meaning when you toggle path bar, it just appears/disappears, and it should be the same or consistent with tag bar too.

We can always challenge native experiences and do things our own way, atleast for this. Let's give it some thought in a separate PR.

2024-06-17 10:09 UTC, iLynxcat commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
I worry about visual balance here, having centred content in the tag bar and left-aligned content in the path bar looks odd. Curious what @jamiepine's vision on this is, but we can iterate while waiting on his response

2024-06-17 10:20 UTC, iLynxcat commented on interface/app/$libraryId/Explorer/ExplorerPathBar.tsx
Worth noting that I do plan on reworking the style of this bottom bar area to allow for quick animations, but as it stands it would be janky and not work too well given the main explorer list depends on fixed heights to offset content — this will not only mess with animations (which would be fine to work around with small changes) but also cause a large accessibility issue if users wish to use much larger text size within the UI. It's not something that is considered well in the current UI but will be important toward the release stage

2024-06-17 10:21 UTC, iLynxcat commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +const TagItem = ({
Agreed, and I will move this off to another file — I should note that I want to do some restructuring of this area of the codebase as the Explorer directory is a total mess without any organization

2024-06-17 10:25 UTC, iLynxcat commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
@myung03 I agree with you but I can't think of a way that looks/feels good to communicate that explicitly right now. I think this is something that causes very little friction one single time to a user who may not realize it. Once they try any key other than 1-9 and it fails, then they try a key 1-9 and it succeeds, it'll be easily understood.

I do agree we chould communicate it better when we revise the help text design overall. Maybe an info icon popup appended to the help text?

2024-06-17 10:51 UTC, ameer2468 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
> I worry about visual balance here, having centred content in the tag bar and left-aligned content in the path bar looks odd. Curious what @jamiepine's vision on this is, but we can iterate while waiting on his response

Valid point - i'm gonna play with it and see what better can be done.

2024-06-17 13:18 UTC, ameer2468 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
I've experimented with the layout a bit - i see potential in this. So i'm gonna leave it and see what other ideas can be shared.

<img width="1468" alt="Screenshot 2024-06-17 at 4 14 45 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/f375cdd5-445c-4670-b827-82419fb1681d">

2024-06-17 21:43 UTC, myung03 commented on interface/locales/en/common.json
> +  "tags_bulk_instructions": "Select one or more files and press a key to assign the corresponding tag.",
Totally agree - not sure if this is sufficient, but I would probably just change it to "Select one or more files, and press a number key to assign to the corresponding tag." 

0 not being an option makes a marginal difference and I think just adding that extra bit of wording makes it a lot clearer (instead of having the user have to press a random key and trial + error until they realize that only number keys work). This is a bit of a personal preference thing though so lmk if you disagree :))

2024-06-17 21:45 UTC, myung03 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
i like this layout, but i can see it becoming an issue once the user has 8 or more tags as it will overlap with the text. can we have some kind of side scroller logic for tags if there are more than X amount?

2024-06-17 21:53 UTC, myung03 commented on interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
> +			<em className="text-sm tracking-wide">{t('tags_bulk_instructions')}</em>
also I know we said the text was fine, but would it be possible to make it a dismissible component (similar to the "Meet Grid View" thing when you open up a folder). I feel like this would be the best of both worlds so the tags dont appear with no text but once the user closes the text there will be more space for the tags.

2024-06-18 10:50 UTC, ameer2468 approved these changes

2024-06-18 10:55 UTC, merged