Update common.json
spacedriveapp/spacedrive pull request #2490
Opened 2024-05-15 17:17 UTC by Phedona

updated german lanuage again

2024-05-16 22:22 UTC, Phippe requested changes
Copilot would've done a better job :/

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "ipv4_listeners_error": "Fehler beim Erstellen der IPv4 Lauscher. Bitte prüfe deine Firewall einstellung!",
```suggestion
  "ipv4_listeners_error": "Fehler beim Erstellen der IPv4-Lauscher. Bitte prüfe deine Firewall-Einstellungen!",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "ipv4_ipv6_listeners_error": "Fehler beim Erstellen der IPv6 und IPv4 Lauscher. Bitte prüfe deine Firewall einstellung!",
```suggestion
  "ipv4_ipv6_listeners_error": "Fehler beim Erstellen der IPv6- und IPv4-Lauscher. Bitte prüfe deine Firewall-Einstellungen!",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "ipv6_listeners_error": "Fehler beim Erstellen der IPv6 Lauscher. Bitte prüfe deine Firewall einstellung!",
```suggestion
  "ipv6_listeners_error": "Fehler beim Erstellen der IPv6-Lauscher. Bitte prüfe deine Firewall-Einstellungen!",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "delete_rule_confirmation": "Bist du Sicher, das du diese Regel Löschen willst?",
```suggestion
  "delete_rule_confirmation": "Bist du sicher, dass du diese Regel löschen willst?",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "directories": "Verzichnisse",
```suggestion
  "directories": "Verzeichnisse",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "do_the_thing": "Mach dein Ding",
Not sure if this is correct, but I don't know the specific context this is used in

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "dont_have_any": "Scheint so als hättest du keine!",
```suggestion
  "dont_have_any": "Scheint so, als hättest du keine!",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "failed_to_add_location": "Fehler beim Hinzufügen der Location",
```suggestion
  "failed_to_add_location": "Fehler beim Hinzufügen des Standorts",
```

Keeping it consistent

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "failed_to_open_file_body": "Konnte die Datei aufgrund des Fehlers nicht Öffnen: {{error}}",
```suggestion
  "failed_to_open_file_body": "Konnte die Datei aufgrund des Fehlers nicht öffnen: {{error}}",
```

What's up with these random capitalisations all over the place

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "file_picker_not_supported": "Dateiselektor auf dieser Plattform nicht Unterstützt",
```suggestion
  "file_picker_not_supported": "Dateiselektor auf dieser Plattform nicht unterstützt",
```
Like why??

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "indexed_new_files": "Neue dateien Indiziert {{name}}",
```suggestion
  "indexed_new_files": "Neue Dateien indiziert {{name}}",
```
I'm losing my mind

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "indexer_rules_error": "Fehler bei holen der Indexierungsregel",
```suggestion
  "indexer_rules_error": "Fehler beim Abrufen der Indexierungsregeln",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "my_sick_location": "Meine kranke Location",
```suggestion
  "my_sick_location": "Mein kranker Standort",
```
Consistency again

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "networking_error": "Starten des Netzwerks Fehlgeschlagen!",
```suggestion
  "networking_error": "Starten des Netzwerks fehlgeschlagen!",
```
It's a verb ffs

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "no_apps_available": "Keine apps Verfügbar",
```suggestion
  "no_apps_available": "Keine Apps verfügbar",
```
...

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "open_logs": "Öffne Logs",
```suggestion
  "open_logs": "Logs öffnen",
```
Consistency

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "opening_trash": "Öffne Mülleimer",
```suggestion
  "opening_trash": "Mülleimer öffnen",
```
Again consistency

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "path_to_save_do_the_thing": "Pfad zum Speichern wenn klicke auf 'Do the Thing':",
Nah man, what is this??

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "quick_rescan_started": "Schnellsuche Gestartet",
```suggestion
  "quick_rescan_started": "Schnellsuche gestartet",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "reject_files": "Dateien Ablehnen",
```suggestion
  "reject_files": "Dateien ablehnen",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "reset_warning": "DU VERLIERST ALLE BESTEHENDEN SPACEDRIVE DATEN!",
```suggestion
  "reset_and_quit": "Zurücksetzen & App Verlassen",
  "reset_confirmation": "Bist du sicher, dass du Spacedrive zurücksetzen willst? Deine Datenbank wird gelöscht.",
  "reset_to_continue": "Es wurde festgestellt, dass du deine Bibliothek mit einer älteren Version von Spacedrive erstellt hast. Bitte zurücksetzen, um die App weiterhin zu verwenden.!",
  "reset_warning": "DU VERLIERST ALLE BESTEHENDEN SPACEDRIVE-DATEN!",
```
Verbs aren't capitalised, but there are some words that are indeed capitalised in the English version

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "save_search": "Suche Speichern",
Hmm... I guess the English version capitalises this one? Why...?

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "uploaded_file": "Datei Hochgeladen!",
```suggestion
  "uploaded_file": "Datei hochgeladen!",
```

2024-05-16 22:22 UTC, Phippe commented on interface/locales/de/common.json
> +  "see_less": "Zeige weniger",
```suggestion
  "see_more": "Mehr anzeigen",
  "see_less": "Weniger anzeigen",
```

2024-05-17 03:04 UTC, utkubakir commented on interface/locales/de/common.json
> +  "save_search": "Suche Speichern",
could be a title somewhere

2024-05-17 08:15 UTC, Phippe commented on interface/locales/de/common.json
> +  "save_search": "Suche Speichern",
That makes sense. In that case we could capitalise previous translations like on line 519 or keep using sentence case for the translation and adjust this line here. I personally find to latter option to look better, but it would deviate from the original

2024-07-17 23:16 UTC, closed without merging