More P2P docs
spacedriveapp/spacedrive pull request #2492
Opened 2024-05-16 04:30 UTC by oscartbeaumont

2024-05-27 18:06 UTC, myung03 requested changes

2024-05-27 18:06 UTC, myung03 commented on docs/developers/p2p/relay.mdx
> +You will need a ensure port `7373` is exposed through your firewall for this to work.
```suggestion
1. Set up the server using the following command:

    ```bash
    cargo run -p sd-p2p-relay init
    # You will be prompted to enter the p2p secret.
    # It can be found in the `spacedrive-api` Vercel project as the `P2P_SECRET` environment variable.
    ```

2. Now that you have set up the server, you can run the relay server using the following command:

    ```bash
    cargo run -p sd-p2p-relay
    ```

*Note that you will need to ensure port `7373` is exposed through your firewall for this to work.*

```

2024-05-28 08:39 UTC, oscartbeaumont commented on interface/locales/en/common.json
> +	"manual_peers_description": "Add peers manually by entering their IP address and port.\nThis is useful when automatic discovery is not possible.",
Prettier seems to not be formatting this file which is weird.

2024-05-28 08:40 UTC, oscartbeaumont commented on docs/developers/p2p/local-network-discovery.mdx
> +To integrate with Spacedrive's account system, TODO
The PR description states the documentation is still incomplete so yeah.

2024-05-28 09:21 UTC, oscartbeaumont commented
@myung03 Thank you very much for this thorough review you brought up a lot of good points.

Any `TODO` across the docs is a marker for me to come back to it before I finish at SD on Friday. I opened this PR up for review because it contains some breaking changes to the Cloud pairing process and I was trying not to block Brendan although I noticed a couple of mistakes in the code so changed it back to a draft.

The first-person language definitely not great on the docs but I've also tried to include information about the rational or alternative perspectives which are ultimately subjective and I wanted to convey it's a personal opinion not an opinion of Spacedrive. Although, I think you're completely right it is not necessary in many places.

2024-05-30 13:45 UTC, utkubakir approved these changes

2024-05-30 13:48 UTC, merged