added feedback for delete
spacedriveapp/spacedrive pull request #2507
Opened 2024-05-25 02:47 UTC by myung03

Added feedback for when user deletes a location

2024-05-25 04:58 UTC, utkubakir requested changes

2024-05-25 04:58 UTC, utkubakir commented on interface/locales/en/common.json
> +  "Location added successfully": "Location added successfully.",
missed this

2024-05-25 04:58 UTC, utkubakir commented on interface/locales/en/common.json
> +  "location_added_successfully": "Location added successfully. ",
extra space

2024-05-25 05:47 UTC, myung03 commented on interface/locales/en/common.json
> +  "Location added successfully": "Location added successfully.",
having issues with adding the toast to location actually - trying to add the toast.success in the try part of the try catch but not working? any idea why

2024-05-25 13:26 UTC, utkubakir commented on interface/locales/en/common.json
> +  "Location added successfully": "Location added successfully.",
not sure where. happy to move this discussion to slack with more information on where in the code

2024-05-27 17:28 UTC, utkubakir approved these changes

2024-05-27 17:32 UTC, merged