[ENG-1794] Overview Rework
spacedriveapp/spacedrive pull request #2555
Opened 2024-06-18 19:32 UTC by myung03

This PR reworks the overview section, reorganizing current information into a more visually appealing format for users. 
- LibraryStats has been reworked into a storage bar 
- FileKindStats has been reworked into a bar graph 
- NodeGraph commented out and placed in Network for future use. This component is planned to showcase active nodes for a library. 
- minor refactor for previous library stats to clean up component, and overview index component (previously had a lot pointless dummy data commented out, removed for clarity).

2024-06-18 22:53 UTC, iLynxcat requested changes
Lots of small suggestions here, overall good looking as we discussed during our review session with @ameer2468 :)

**Only big issue:** Lots of lines here are not formatted per our Prettier config. Please make sure to use the Prettier vscode plugin or run `pnpm prettier --write .` before pushing changes!

2024-06-18 22:53 UTC, iLynxcat commented on core/src/api/libraries.rs
> +				let total_identified_files = library.db.object().count(vec![]).exec().await?;
tiny change, I think this whitespace isn't necessary

```suggestion
				let total_unidentified_files = library.db.file_path().count(vec![]).exec().await?;
				let total_identified_files = library.db.object().count(vec![]).exec().await?;
```

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/network.tsx
> +// so placing it here for now!
Can we put this component in its own file?

Is there any reason it wouldn't compile if uncommented, or can we uncomment it?

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +const UNIDENTIFIED_FILES_CLASS = "relative flex items-center text-xs text-ink-faint";
We should be a little more explicit that this is a 'list' of classes

```suggestion
const INFO_ICON_CLASSLIST = "inline size-3 text-ink-faint opacity-0";
const TOTAL_FILES_CLASSLIST = "flex items-center justify-between whitespace-nowrap text-sm font-medium text-ink-dull mt-2 px-1";
const UNIDENTIFIED_FILES_CLASSLIST = "relative flex items-center text-xs text-ink-faint";
```

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +  }, []);
I think we can ship an alpha release with this right now, but we should revise later use flexbox to automatically handle sizing as needed. Is there a particular reason that wouldn't work and we'd need to keep this in JS, or do you think we can work toward that later on? 

I specifically make this comment because we have some very unperformant views in the UI as-is and I'd like to make everything as natively styled as possible when it comes to layout.

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +  const getPercentage = (value: number) => `${((value / maxFileCount) * BARHEIGHT).toFixed(2)}px`;
This should be moved out of the component and refactored to take in maxFileCount and BARHEIGHT as parameters. The function should also be given a more explicit name even if it's longer — maybe we call the function `getBarHeightPixels`, and rename `BARHEIGHT` to `STAT_BAR_MAX_HEIGHT` or similar.

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/LibraryStats.tsx
> +  info?: string;
Please make sure formatting with Prettier is on in your editor or double check it before each commit — these lines should start with a tab (`\t`) and not two spaces

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/StorageBar.tsx
> +// Function to lighten color
This comment is redundant given the function name is `lightenColor`

```suggestion
```

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/StorageBar.tsx
> +  )
I always love to see bitwise logic 😋

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/StorageBar.tsx
> +  )
I always love to see bitwise logic 😋

2024-06-18 22:53 UTC, iLynxcat commented on interface/app/$libraryId/overview/index.tsx
> +
Extraneous whitespace should not have been added

```suggestion
```

2024-06-18 23:02 UTC, myung03 commented on interface/app/$libraryId/overview/StorageBar.tsx
> +  )
imagine me getting a 4 year computer science degree to learn some mf bitwise logic 😞

2024-06-18 23:06 UTC, myung03 commented on interface/app/$libraryId/network.tsx
> +// so placing it here for now!
you are totally right I did not think of that - any suggestions for where to put it?

2024-06-18 23:19 UTC, myung03 commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +  }, []);
There are a number of reasons I chose to this approach initially, but open to refactoring: 
- the gap is directly dependent on the width of the bars, as well as the number of bars. I thought it would be a better idea to manually calculate the bar width/other related css qualities and it would provide more control over the spacing and stuff, but this design decision may be poor as I just didn't really have any other good ideas of how to accomplish this 
- the number of bars is variable, and I wasn't sure if flexbox would be effective in cases where we had 20+ bars or other edge cases.

2024-06-18 23:26 UTC, myung03 commented on interface/app/$libraryId/overview/LibraryStats.tsx
> +  info?: string;
fixed - prettier is enable though so im not sure why this doesn't work?

2024-06-18 23:30 UTC, myung03 commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +  const getPercentage = (value: number) => `${((value / maxFileCount) * BARHEIGHT).toFixed(2)}px`;
I think if I abstract out maxFileCount/bar height I would have to move the entire useEffect out into the index file, which might obfuscate the code a bit (since its all related to the file). Any suggestions on how to best achieve the refactor? 
- also opting to simply remove bar height variable since its just in 1 place, so doesn't really make sense imo to use a global variable for that

2024-06-18 23:59 UTC, HeavenVolkoff commented on interface/app/$libraryId/overview/LibraryStats.tsx
> +  info?: string;
Also make sure to install the [EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension to autoconfigure vscode to respect our project spacing configurations defined in [.editorconfig](https://github.com/spacedriveapp/spacedrive/blob/main/.editorconfig)

2024-06-19 00:05 UTC, iLynxcat commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +  }, []);
it's doable with flexbox (or honestly maybe grid), happy to talk with you more in depth on layout options here!

2024-06-19 00:09 UTC, iLynxcat commented on interface/app/$libraryId/overview/LibraryStats.tsx
> +  info?: string;
> fixed - prettier is enable though so im not sure why this doesn't work?

you may have to manually configure it to autoformat on save. I can help you with checking your vscode config, gimme a slack message at some point if you want

2024-06-19 01:01 UTC, myung03 commented on interface/app/$libraryId/overview/LibraryStats.tsx
> +  info?: string;
yes remind me about this tmr please!

2024-06-19 17:14 UTC, ameer2468 commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +								className={`${isDark ? 'text-white' : 'text-black'} text-xl font-black`}
We use **clsx** for conditional styling, please use clsx instead.

2024-06-19 17:22 UTC, ameer2468 commented on interface/app/$libraryId/overview/StorageBar.tsx
> +	const num = parseInt(color.replace('#', ''), 16);
While this is a solution that works - why not instead use tailwind color classes? blue-400, blue-500 etc...

I think all this code to support a lighter color is un-necessary.

2024-06-19 18:41 UTC, iLynxcat commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +								className={`${isDark ? 'text-white' : 'text-black'} text-xl font-black`}
got this in my local working copy, will be included in a commit soon :)

2024-06-19 19:47 UTC, myung03 commented on interface/app/$libraryId/overview/FileKindStats.tsx
> +								className={`${isDark ? 'text-white' : 'text-black'} text-xl font-black`}
fixed by Haden!

2024-06-19 19:50 UTC, myung03 commented on interface/app/$libraryId/overview/StorageBar.tsx
> +	const num = parseInt(color.replace('#', ''), 16);
I wanted it to be dynamic so in the future we wouldn't have to change the hover colour everytime a colour needed to be changed. This was more impactful at first (i.e when light and dark mode had different colours) but less obvious now. I talked to Haden and he said it should be fine for now, but we can definitely refactor in the future. I've left a note in the code for future change (if thats okay)?

2024-06-19 20:59 UTC, ameer2468 commented on interface/app/$libraryId/overview/StorageBar.tsx
> +	const num = parseInt(color.replace('#', ''), 16);
> I wanted it to be dynamic so in the future we wouldn't have to change the hover colour everytime a colour needed to be changed. This was more impactful at first (i.e when light and dark mode had different colours) but less obvious now. I talked to Haden and he said it should be fine for now, but we can definitely refactor in the future. I've left a note in the code for future change (if thats okay)?

Yep that sounds great! and I understand your reason now.

2024-06-24 20:00 UTC, ameer2468 approved these changes

2024-06-24 20:18 UTC, merged