[ENG-1809] Make core more resilient to crashes
spacedriveapp/spacedrive pull request #2574
Opened 2024-06-27 19:10 UTC by fogodev

Catching panics when running tasks and jobs. Also introducing a `catch_unwind` when generating thumbnails as a quick workaround until https://github.com/image-rs/image/issues/2230 is fixed upstream.

2024-06-29 04:56 UTC, HeavenVolkoff requested changes

2024-06-29 04:56 UTC, HeavenVolkoff commented on core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs
> +				panic::catch_unwind(|| inner_generate_image_thumbnail(&file_path)).unwrap_or_else(
This doesn't seem to be working. I tested with the image in https://github.com/image-rs/image/issues/2230 and the app still crashes. Should we revert to image-rs 0.24?

![image](https://github.com/spacedriveapp/spacedrive/assets/9082460/f22e3515-0adc-4652-88d6-d38a5bbac320)

2024-06-29 05:15 UTC, fogodev commented on core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs
> +				panic::catch_unwind(|| inner_generate_image_thumbnail(&file_path)).unwrap_or_else(
Damn boy, but sure, let's revert then

2024-06-29 20:11 UTC, HeavenVolkoff requested changes

2024-06-29 20:11 UTC, HeavenVolkoff commented on core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs
> +				panic::catch_unwind(|| inner_generate_image_thumbnail(&file_path)).unwrap_or_else(
Now that we reverted image, should we keep this catch unwind?

2024-06-29 20:15 UTC, fogodev commented on core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs
> +				panic::catch_unwind(|| inner_generate_image_thumbnail(&file_path)).unwrap_or_else(
It didn't catch the bad assert, but hopefully it catches other panics, so I see no harm leaving it there, we don't want crashed nonetheless

2024-06-30 03:59 UTC, HeavenVolkoff approved these changes

2024-06-30 04:19 UTC, merged