Dim pure white text & increase keybind text size in keybind list
spacedriveapp/spacedrive pull request #2643
Opened 2024-07-28 14:12 UTC by PineappleRind

- Use rgb(235,235,235) for the brightest text color in dark mode (Closes #2417)

- Increase keybind text size in settings for better legibility (before/after):
  <img width="324" alt="before" src="https://github.com/user-attachments/assets/a5cb5184-b028-4a30-a370-f6781c43d7c9"> <img width="323" alt="after" src="https://github.com/user-attachments/assets/d8348c27-bde9-47d4-b131-4c30274d6fbe">

2024-07-28 21:39 UTC, iLynxcat commented
Thanks for contributing, will do a proper review on this tomorrow!

2024-07-31 21:03 UTC, iLynxcat commented
so sorry, I got caught up with some other issues, going to see how this looks locally today & make any needed tweaks so we can merge!

2024-07-31 23:39 UTC, myung03 reviewed
lgtm! thanks so much for contributing :) @iLynxcat is going to take a look at some tint colours as well so I will pass it off to them to approve.

2024-07-31 23:42 UTC, iLynxcat requested changes
I put some suggested tint changes in here but overall this is nice. I don't have a mini-LED or OLED display to test this on right now, so if we get more complaints we can revise again. Thank you for contributing!

2024-07-31 23:42 UTC, iLynxcat commented on packages/ui/style/colors.scss
> +	--color-menu-ink: var(--dark-hue), 10%, 92%;
```suggestion
	--color-menu-ink: var(--dark-hue), 25%, 92%;
```

2024-07-31 23:42 UTC, iLynxcat commented on packages/ui/style/colors.scss
> +	--color-sidebar-ink: var(--dark-hue), 0%, 92%;
```suggestion
	--color-sidebar-ink: var(--dark-hue), 15%, 92%;
```

2024-07-31 23:42 UTC, iLynxcat commented on packages/ui/style/colors.scss
> +	--color-ink: var(--dark-hue), 0%, 92%;
```suggestion
	--color-ink: var(--dark-hue), 35%, 92%;
```

2024-07-31 23:42 UTC, iLynxcat commented on interface/app/$libraryId/settings/client/keybindings.tsx
> +							<kbd className="ml-2 rounded-lg border border-app-line bg-app-box px-1.5 py-0.5 text-sm tracking-widest shadow">
I like the way this looks. We may revise it in the future as part of an upcoming planned change regarding keyboard shortcuts, but this is a nice inclusion!

2024-07-31 23:43 UTC, iLynxcat approved these changes

2024-08-02 21:41 UTC, merged