Small analytics revamp
spacedriveapp/spacedrive pull request #2740
Opened 2024-09-29 05:21 UTC by iLynxcat

This PR is primarily aimed at adding a "none" option for analytics which has been highly requested, with some other related changes to help improve clarity of some of our analytics functionality for people who may be reviewing the code for their own peace of mind.

2024-09-29 09:33 UTC, iLynxcat commented
Just need to polish UI for this and should be good to go after!

2024-09-29 09:38 UTC, HeavenVolkoff commented
Need to change cypress onboarding test here to add the new telemetry option and rename the element ids:

https://github.com/spacedriveapp/spacedrive/blob/a0173caccfbb18a02a1ccf56340ad7d9155ac7a7/apps/web/cypress/e2e/1-onboarding.spec.cy.ts#L133-L139

2024-09-29 12:26 UTC, iLynxcat commented
Also just remembered I need to figure out how to properly migrate the old telemetry preference to this new property format

2024-10-03 02:17 UTC, HeavenVolkoff requested changes

2024-10-03 02:17 UTC, HeavenVolkoff commented on packages/client/src/hooks/usePlausible.tsx
> +				// this should be discussed soon (if I don't forget™) and removed if we agree. ~ilynxcat
What is this about?

2024-10-03 02:17 UTC, HeavenVolkoff commented on packages/client/src/hooks/usePlausible.tsx
> +	// because a user having "none" teleemtry preference should mean Plausible never even initalizes
s/teleemtry/telemetry/

2024-10-03 02:17 UTC, HeavenVolkoff commented on apps/mobile/src/screens/onboarding/Privacy.tsx
> +									description="TODO: Write a proper description clarifying that this literally sends us no analytics data"
Sends absolutely no analytics data from the Spacedrive app.

2024-10-03 02:17 UTC, HeavenVolkoff commented on apps/mobile/src/screens/onboarding/Privacy.tsx
>  							</Pressable>
We are not using the localization function for the title and description of these buttons

2024-10-03 03:30 UTC, iLynxcat commented on packages/client/src/hooks/usePlausible.tsx
> +	// because a user having "none" teleemtry preference should mean Plausible never even initalizes
sorry had to make sure it's watermarked as not ai generated

2024-10-03 03:30 UTC, iLynxcat commented on packages/client/src/hooks/usePlausible.tsx
> +	// because a user having "none" teleemtry preference should mean Plausible never even initalizes
```suggestion
	// because a user having "none" telemetry preference should mean Plausible never even initalizes
```

2024-10-03 03:31 UTC, iLynxcat commented on apps/mobile/src/screens/onboarding/Privacy.tsx
> +									description="TODO: Write a proper description clarifying that this literally sends us no analytics data"
oops missed this since I updated the translation file and forgot that mobile is hard coded 

```suggestion
									description="Sends absolutely no analytics data from the Spacedrive app."
```

2024-10-03 03:32 UTC, iLynxcat commented on apps/mobile/src/screens/onboarding/Privacy.tsx
>  							</Pressable>
haven't seen any evidence of i18n in mobile app @Rocky43007 is there a reason?

2024-10-03 03:34 UTC, iLynxcat commented on packages/client/src/hooks/usePlausible.tsx
> +				// this should be discussed soon (if I don't forget™) and removed if we agree. ~ilynxcat
basically we have a telemetry override functionality implemented for some reason, it was explicitly commented as probably necessary for something in the future but I see zero reason whatsoever that this would be necessary and it should be removed. gonna send a link to this in Slack for discussion

2024-10-03 03:37 UTC, Rocky43007 commented on apps/mobile/src/screens/onboarding/Privacy.tsx
>  							</Pressable>
We never set it up because mobile wasn't that big of a priority back then. We can probably set it up and implement it into #2633 since i18next does support react-native: [Their docs](https://react.i18next.com/#what-is-react-i18next)

2024-10-03 03:48 UTC, HeavenVolkoff commented on packages/client/src/hooks/usePlausible.tsx
> +				// this should be discussed soon (if I don't forget™) and removed if we agree. ~ilynxcat
Hun... Yeah, I also don't see a reason for us to want to use this. I agree with removing it

2024-10-03 03:51 UTC, HeavenVolkoff commented on apps/mobile/src/screens/onboarding/Privacy.tsx
>  							</Pressable>
Ah, fair, I thought the mobile app already had that implemented, let's go ahead with just the english text for now.
I think implementing this feature should be a separate PR, #2633 is already too crowded

2024-10-05 13:34 UTC, HeavenVolkoff commented
The privacy setting screen on mobile is disabled for some reason:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/1c3bed0e-a99d-425c-ae3b-3eb4b91f6b4b">

<img width="364" alt="image" src="https://github.com/user-attachments/assets/eba56490-cd98-48ec-a060-51d1f5704181">

Also, a minor nitpick: the mobile onboarding page for telemetry seems to be missing some padding for the last entry:
<img width="368" alt="image" src="https://github.com/user-attachments/assets/6985bc29-30c2-4b7d-8d13-45075405eb13">

2024-10-05 13:34 UTC, HeavenVolkoff submitted a review, later dismissed

2024-10-05 14:14 UTC, iLynxcat commented
Enabling the page is out of scope of this PR but I'll fix the padding

2024-10-07 22:00 UTC, Rocky43007 approved these changes
Hopefully it merges this time?

2024-10-07 22:16 UTC, merged