Updated `CONTRIBUTING.md`
spacedriveapp/spacedrive pull request #2820
Opened 2024-11-27 20:48 UTC by 0xBA5E64

2024-11-27 21:16 UTC, iLynxcat reviewed
some small writing changes here

2024-11-27 21:16 UTC, iLynxcat commented on CONTRIBUTING.md
> +    Alternately, if you already have the repo cloned from previously, pull the latest changes to the code with: `git pull`
```suggestion
    Alternately, if you’ve already cloned the repo locally, pull the latest changes with: `git pull`
```

2024-11-27 21:16 UTC, iLynxcat commented on CONTRIBUTING.md
> +>  The test files will be located in a directory called `test-data` in the root of the spacedrive repo.
```suggestion
>  The test files will be located in a directory called `test-data` in the root of the Spacedrive repo.
```

2024-11-27 21:16 UTC, iLynxcat commented on CONTRIBUTING.md
> +To run the **Tauri desktop** app, run:
```suggestion
To run the **desktop** app, run:
```

2024-11-27 21:16 UTC, iLynxcat commented on CONTRIBUTING.md
> +> Also, the react-devtools can be launched using `pnpm dlx react-devtools`.
```suggestion
> [!TIP]
> If necessary, [DevTools](https://tauri.app/v1/guides/debugging/application/#webview-console) for the WebView can be opened by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> (Linux and Windows) or <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>I</kbd> (macOS) in the desktop app.
>
> Also, React DevTools can be launched using `pnpx react-devtools`.
```

2024-11-27 21:16 UTC, iLynxcat commented on CONTRIBUTING.md
> + - After cleaning out your build artifacts using `pnpm clean`, it is necessary to re-run the `./setup/setup.sh` script.
It’s necessary to rerun `prep`, but not the setup script

```suggestion
 - After cleaning out your build artifacts using `pnpm clean`, it's necessary to re-run `pnpm prep`.
```

2024-11-27 23:07 UTC, 0xBA5E64 commented on CONTRIBUTING.md
> +To run the **Tauri desktop** app, run:
I'm leaning towards including Tauri here since it's part of the command to build some mental connections for users.

Alternatively, perhaps we should just add another script to pnpm so we could run `pnpm desktop dev`, which might make more sense?

2024-11-29 03:22 UTC, Rocky43007 requested changes

2024-11-29 03:22 UTC, Rocky43007 commented on CONTRIBUTING.md
> +> https://github.com/spacedriveapp/spacedrive/blame/d180261ca5a93388486742e8f921e895e9ec26a4/apps/mobile/modules/sd-core/android/build.sh#L61
Hey, for some reason, this won't preview properly on GitHub. The other preview works great, though.

Once this is fixed, I'm good to let it merge.

2024-11-30 11:00 UTC, Phippe requested changes

2024-11-30 21:11 UTC, 0xBA5E64 commented on CONTRIBUTING.md
> +> https://github.com/spacedriveapp/spacedrive/blame/d180261ca5a93388486742e8f921e895e9ec26a4/apps/mobile/modules/sd-core/android/build.sh#L61
Seems like GitHub didn't like this line being linked from the blame view, switching it over fixed it (a2bb6e0fc68de8c9574c9faf1369a6aefdd431fc)

2024-11-30 21:24 UTC, Rocky43007 approved these changes
It looks fantastic now! Thank you for spending the time updating the docs!

2024-11-30 21:38 UTC, merged