Update Inspector.tsx
spacedriveapp/spacedrive pull request #304
Opened 2022-06-24 12:31 UTC by waydealphax

Updated this file so that file paths are correct on windows.

Added an if else statement to check if the system is Win32 and if so change the full path from x/x to x\\x to conform with windows file paths

2022-07-04 04:33 UTC, maxichrome requested changes
great looking out! — idk if it's just GitHub showing extraneous changes in the diff but there seem to be a lot of unrelated changes in here... 

requested a couple changes with suggestions for changes core to this PR's purpose though.

2022-07-04 04:33 UTC, maxichrome commented on packages/interface/src/components/file/Inspector.tsx
> +	if (window.navigator.platform === 'Win32') {
somewhere in the AppProps we take in a platform prop -- let's use that context instead here

2022-07-04 04:33 UTC, maxichrome commented on packages/interface/src/components/file/Inspector.tsx
> +	}
not a big fan of using `var` declarations anywhere, period. 

```suggestion
	const file_path = props.selectedFile,
	file_id = props.selectedFile?.file?.id || -1;
	
	let full_path: string;
	
	if (window.navigator.platform === 'Win32') {
		full_path = `${props.location?.path}\\${file_path?.materialized_path}`;
	} else {
		full_path = `${props.location?.path}/${file_path?.materialized_path}`;
	}
```

2022-07-04 04:33 UTC, maxichrome commented on packages/interface/src/components/file/Inspector.tsx
> +	}
use an array here instead, maybe:

```suggestion
	const pathSeparator = window.navigator.platform === 'Win32' ? '\\' : '/';

	full_path = [props.location?.path, file_path?.materialized_path].join(pathSeparator);
```

2022-07-04 04:33 UTC, maxichrome commented on packages/interface/src/components/file/Inspector.tsx
> +		// </Transition>
what does this massive diff have to do with path separators?

2022-07-04 04:33 UTC, maxichrome commented on core/src/sys/locations.rs
> +
does this help path separators display properly? I'm always glad to see updated functionality but this seems out-of-scope?

2022-07-04 04:56 UTC, waydealphax commented on packages/interface/src/components/file/Inspector.tsx
> +		// </Transition>
i was basing off of jamies eng branch because i saw he was working within the same area :p

2022-07-04 04:56 UTC, waydealphax commented on core/src/sys/locations.rs
> +
refer to prev. comment most like related to the basing off of jamies branch

2022-07-04 05:01 UTC, waydealphax commented
@maxichrome looks fine to me now, have a check and lmk

2022-07-04 07:10 UTC, maxichrome commented
> looks fine to me now, have a check and lmk

still includes lots of unrelated changes. any way you can base this on `main` / mark it as a draft PR until the related changes are merged in?

2022-08-30 06:15 UTC, oscartbeaumont commented
Thanks for the PR but I don't think in its current form we will want to merge it. To fix this issue work will need to be done on the Rust backend to properly understand the operating system the file was created on and return the correct path. The current fix in this PR will break when it comes to hooking the app up to the P2P sync layer because it uses the OS your running the app on (`appProps.platform`) to decide how to display the path instead of the operating system of the computer the file was created on.

2022-09-26 06:34 UTC, closed without merging