SearchBar Logo fix
spacedriveapp/spacedrive pull request #310
Opened 2022-06-25 22:05 UTC by misxki

The SearchBar shows now CTRL for the keybind on non-macOS systems.

Closes #295

2022-07-07 20:11 UTC, RockBacon9922 commented
Was this ever merged @misxki?

2022-07-08 00:53 UTC, xPolar commented
@RockBacon9922 misxki can't merge this PR, only the core team can, any ETA on review / merge @jamiepine @maxichrome

2022-07-08 01:19 UTC, maxichrome approved these changes
sick change! sorry for holding off so long — was waiting on license change!

2022-07-08 01:21 UTC, maxichrome requested changes
reverted approval for one requested change -- then I'm happy to merge :D

2022-07-08 01:21 UTC, maxichrome commented on packages/interface/src/components/layout/TopBar.tsx
> +				<Shortcut chars={ appProps?.platform === "macOS" ? "⌘K" : "CTRL+K" } />
I'd like to see detection for platform on web implemented as well -- this is probably more of an app-level architectural thing. until then, before merge, could we get the cmd-k visual to show on web as well?

2022-07-08 10:00 UTC, maxichrome approved these changes
tysm for following up with requested changes @misxki :)

once CI runs finish here I'd be happy to merge.

2022-07-12 11:33 UTC, merged