Implements focus on search bar when super+k is pressed.
spacedriveapp/spacedrive pull request #327
Opened 2022-07-07 20:54 UTC by RockBacon9922

Implements focus on search bar when super+k is pressed.
Hides the key combo hint when search bar is focused.

Closes #326

2022-07-08 03:46 UTC, maxichrome requested changes
Thank you for adding this!! I would like to see some of the requested changes made and then I'm happy to merge!

2022-07-08 03:46 UTC, maxichrome commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
this should be modified to use a keyboard shortcut in the desktop app's `menu.rs` — this code should only activate on the web client

you'll need to use a Tauri event to listen and run `focus()`

2022-07-08 03:46 UTC, maxichrome commented on packages/interface/src/components/layout/TopBar.tsx
> +	},[])
this useEffect should have a cleanup function to remove the event listener on derender

2022-07-08 03:46 UTC, maxichrome commented on packages/interface/src/components/layout/TopBar.tsx
> +						</div>}
I believe this should use a class to hide instead of entirely conditionally rendering. could use a tailwind `group` utility -- on `group-focus` then hide this

2022-07-08 07:19 UTC, RockBacon9922 commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
Surely running it through tauri would remove the feature from the web version?

2022-07-08 17:27 UTC, RockBacon9922 commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
@maxichrome I have done some looking around and come across this.
https://tauri.app/v1/api/js/modules/globalshortcut/
I am trying to implement it but I am getting a dependency warning when I try to import:
    import { register, unregister } from '@tauri-apps/api/globalShortcut'
Any ideas?

2022-07-08 17:29 UTC, RockBacon9922 commented on packages/interface/src/components/layout/TopBar.tsx
> +						</div>}
Resolved used tailwind peer class to control visibility of the element.

2022-07-11 02:01 UTC, jamiepine commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
Don't import any Tauri apis in the interface package, modify app props and import into Desktop and bind via prop

2022-07-13 12:50 UTC, RockBacon9922 commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
Unfortunately I still don't understand what you are requesting @jamiepine.

2022-07-14 04:47 UTC, maxichrome commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
I will work on solving this tonight

2022-07-14 07:37 UTC, Brendonovich commented
IMO `Super+K` is the wrong keybind for the search bar. It's usually used to access an app's command pallete, which Spacedrive doesn't have yet. Instead I propose two other options:
- `Super+L`: Common keybind to access the search bar on web browsers
- `/`: Common keybind to access search functions within websites. Works in GitHub, Google, YouTube, Linear and many other sites. I think this is the best one.

Also, I don't think it should be done in Rust. These keybinds are used by many applications, only detecting them when the app is focused is a pretty standard expectation. To go further and hijack them would be irresponsible.

2022-07-14 22:47 UTC, RockBacon9922 commented
> IMO `Super+K` is the wrong keybind for the search bar. It's usually used to access an app's command pallete, which Spacedrive doesn't have yet. Instead I propose two other options:
> 
> * `Super+L`: Common keybind to access the search bar on web browsers
> * `/`: Common keybind to access search functions within websites. Works in GitHub, Google, YouTube, Linear and many other sites. I think this is the best one.
> 
> Also, I don't think it should be done in Rust. These keybinds are used by many applications, only detecting them when the app is focused is a pretty standard expectation. To go further and hijack them would be irresponsible.

Ok I will happily make these changes if @maxichrome and or @Brendonovich is happy with this proposition.

2022-07-27 00:44 UTC, jamiepine commented
Happy to merge this, we will however most likely replace this code as soon as a keybind system is in place. Ideally we'd want a universal way to register and override keybinds rather than directly calling `document.addEventListener` in components

2022-07-27 00:46 UTC, jamiepine requested changes
Move code to SearchBar.tsx

2022-08-10 12:04 UTC, maxichrome commented
I'll resolve merge conflicts for this PR and make some necessary changes to the feature's working and should have this mergeable shortly

2022-08-30 04:43 UTC, oscartbeaumont commented on packages/interface/src/components/layout/TopBar.tsx
> +		})
I don't think this needs to be done through Tauri because we are targeting the interface at both the desktop app and web app (where we don't have Tauri). It definitely does need to be in the Tauri menu tho, so macOS is happy.

2022-08-30 04:58 UTC, oscartbeaumont commented
The way the keyboard shortcut was implemented it would preventing typing "/" anywhere in the app.

I fixed that, updated the keyboard shortcut hint on the search box and also made it so pressing `Esc` will unfocus the current input anywhere in the app. I also enabled `Cmd+A` for copy all because that's been bugging me a lot.

2022-08-30 05:11 UTC, oscartbeaumont approved these changes

2022-08-30 05:12 UTC, merged