[ENG-250] Crypto Library
spacedriveapp/spacedrive pull request #400
Opened 2022-10-05 16:22 UTC by brxken128

This implements the `crypto` library, the specifications of which can be found on Linear.

It does need further documentation writing, and tests, but I think it's good to go for now.

This should be ready to use within Spacedrive, and has been tested externally (it works very well).

2022-10-06 09:36 UTC, brxken128 commented
Temporarily converting to a draft while I make some last-minute API changes.

2022-10-06 09:36 UTC, Brendonovich requested changes
Will chuck in my 2c, can't comment on any of the subscription specifics though since idk what's going on lol

2022-10-06 09:36 UTC, Brendonovich commented on crates/crypto/Cargo.toml
> +name = "sd_crypto"
```suggestion
name = "sd-crypto"
```

2022-10-06 09:36 UTC, Brendonovich commented on crates/crypto/src/header/keyslot.rs
> +	pub fn serialize(&self) -> Vec<u8> {
Would be nice if ser/de was done with `serde` instead of manually. Not sure how nicely that could be done using a binary format though.

2022-10-06 09:36 UTC, Brendonovich commented on crates/crypto/src/keys/hashing.rs
> +	drop(password);
is this really necessary? `password` will always be dropped at the end of the function anyway.

2022-10-06 10:09 UTC, Brendonovich approved these changes

2022-10-07 07:23 UTC, brxken128 commented
I have some performance benchmarks:

```
2.03968GB/s, XChaCha20-Poly1305
1.47887GB/s, AES-256-GCM
```

I think this can only be improved upstream. We could stop `zeroize`ing the buffers, but then we'd possibly leak data (and the time it takes to zero out memory is negligible).

Most drives aren't able to read/write this fast, so performance for users will likely just be limited to the speed of the drive (+ the time it takes to hash their password).

2022-10-07 14:30 UTC, jamiepine submitted a review, later dismissed
just incredible work

2022-10-07 14:31 UTC, merged