[ENG-258] Key Manager and Crypto Crate Improvements
spacedriveapp/spacedrive pull request #423
Opened 2022-10-20 12:18 UTC by brxken128

This PR adds the entire `KeyManager`, which is an in-memory keystore for both mounted and stored keys.

It handles the mounting, unmounting, creating, retrieving, etc. of keys and will allow for extremely easy integration with other jobs/library mutations. It has been made accessible everywhere as it's included within the library context.

The Prisma schema has also been updated to accommodate these changes.

This PR also brings in a fix for metadata/preview media header objects. They used to be encrypted solely with the first key that was used to encrypt the file - now they inherit the master key from the keyslots. This, in conjunction with the key manager, grants us instant access to all encrypted data within a file (including metadata and preview media).

2022-10-20 12:42 UTC, Brendonovich requested changes
no idea if the crypto is good but the code looks good :)

2022-10-20 12:42 UTC, Brendonovich commented on core/src/library/library_manager.rs
> +		let key_manager = Arc::new(Mutex::new(KeyManager::new(Vec::<StoredKey>::new(), None)));
2 things here:
- Do the arc + mutex when you assign the value to `LibraryContext`, that way you can modify the key manager freely before handing it off
- Use `vec![]` to initialise the vec, it should infer the generic

2022-10-20 12:42 UTC, Brendonovich commented on core/src/util/seeder.rs
> +pub async fn keystore_seeder(client: &PrismaClient, key_manager: Arc<Mutex<KeyManager>>) -> Result<(), SeederError> {
I'm not sure this belongs in the `seeder` module. `seeder` is meant to populate data if none exists, but this is populating data from other existing data.
It might be better suited as a `create_key_manager` function in `library_manager.rs` that takes `&PrismaClient` and returns `KeyManager`.

2022-10-20 19:46 UTC, brxken128 commented on crates/crypto/src/header/keyslot.rs
>  		let hashed_password = hashing_algorithm.hash(password, salt).unwrap();
oh, not a clue how i missed that. thanks 😭

2022-10-23 10:46 UTC, jamiepine approved these changes

2022-10-23 10:47 UTC, merged