New color system & better UI components
spacedriveapp/spacedrive pull request #431
Opened 2022-10-22 11:30 UTC by jamiepine

- Light and dark themes now work and look decent
- UI elements are cleaner and more consistent  
- Began using `cva` and `tw` for cleaner Tailwind

This PR also ate two other PRs (#427 & #422)

2022-10-23 10:32 UTC, maxichrome commented on apps/desktop/src-tauri/src/main.rs
>  			}
Should we remove this entirely?

2022-10-23 15:17 UTC, jamiepine commented on apps/desktop/src-tauri/src/main.rs
>  			}
probably, can't tell what it would be useful for now we have working themes

2022-10-23 21:30 UTC, Brendonovich requested changes
Seems like main wasn't merged in well and some things need to be undone. Would be great if @oscartbeaumont could check to make sure.

Also CI isn't passing yet so fix that plz ❤️

2022-10-23 21:30 UTC, Brendonovich commented on apps/desktop/src/index.tsx
> +	links: [...(false ? [loggerLink()] : []), tauriLink()]
should this be undone?

2022-10-23 21:30 UTC, Brendonovich commented on docs/developers/architecture/sync.md
> +Spacedrive synchronizes library data in realtime across the distributed network of Nodes.
This all needs to be undone. Guessing it's a wrongly resolved merge?

2022-10-23 21:30 UTC, Brendonovich commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
Undo this, bad merge.

2022-10-23 21:30 UTC, Brendonovich commented on packages/interface/src/components/primitive/InputContainer.tsx
> +			<div className={clsx('flex flex-col w-full', !mini && 'pb-6', props.className)} {...props}>
Spread props before setting `className`, otherwise `className` will be overwritten.

2022-10-23 21:30 UTC, Brendonovich commented on packages/ui/src/Button.tsx
> +			forIcon: {
Not sure I agree with this. Variants shouldn't really overlap, and `forIcon` could definitely overlap with some other intent that needs different padding. I'm not a fan of `loading` and `noBorder` either. Maybe I'm nitpicking but I'd prefer `padding: { icon: '!px-1' }`.

2022-10-23 22:33 UTC, jamiepine commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
No this is an actual fix, loadable doesn't work with suspense.

2022-10-23 22:36 UTC, Brendonovich commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
Ohh ffs I can't read, nevermind

2022-10-23 22:38 UTC, oscartbeaumont commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
Odd. We originally had `lazy` but it was the cause of hot reload breaking. I will give this a look.

2022-10-23 22:39 UTC, Brendonovich commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
> Odd. We originally had `lazy` but it was the cause of hot reload breaking. I will give this a look.

Didn't we use `React.lazy` in the past? This is using `lazy` from `@loadable/components`, which I overlook initially.

2022-10-23 22:46 UTC, jamiepine commented on apps/desktop/src/index.tsx
> +	links: [...(false ? [loggerLink()] : []), tauriLink()]
yes, I disabled it cause log spam were making debugging hard

2022-10-23 22:52 UTC, jamiepine commented on packages/interface/src/components/primitive/InputContainer.tsx
> +			<div className={clsx('flex flex-col w-full', !mini && 'pb-6', props.className)} {...props}>
true, will fix

2022-10-23 22:54 UTC, jamiepine commented on packages/ui/src/Button.tsx
> +			forIcon: {
Even though I haven't needed to adjust the padding on any icon button yet, I see why it is bad. Will switch to `padding="icon"`, or make an `IconButton` component that takes care of overriding the padding.

2022-10-23 23:00 UTC, oscartbeaumont commented on packages/interface/src/AppRouter.tsx
> +const DebugScreen = lazy(() => import('./screens/Debug'));
Oh that should be alright. I'm on mobile so it didn't show the import.

2022-10-25 01:45 UTC, Brendonovich submitted a review, later dismissed

2022-10-25 02:40 UTC, oscartbeaumont approved these changes

2022-10-25 02:41 UTC, merged