[ENG-262] Key Manager Integration
spacedriveapp/spacedrive pull request #450
Opened 2022-10-31 14:58 UTC by brxken128

This PR is massive, please criticize it to shreds - it's important that we get this right.

The Key Manager now uses [DashMap](https://github.com/xacrimon/dashmap) in order to provide concurrency and better performance over `HashMap`.

There are a few known bugs/issues:

* The dropdown UI is pretty bad, and doesn't fit in too well with the rest of Spacedrive (and the TS formatting is bad too, I don't know how we format that though)
* The key numbering is volatile, and can/will be confusing
* We have no way to set key names within the UI
* We have no way to view the plaintext key within the UI
* Object/container stats are not attached (this isn't major, as they would all be 0 and therefore wouldn't show anyway)
* The UI offers no differentiation between the default key and normal keys
* There is a bug where you are unable to remove a key instantly while mounting another key
* We have no way to set the master password, and possibly no way to verify that it's correct until the user attempts to run an action. To verify it's correct, we could always attempt to decrypt a key from the keystore with it (if no keys are present, this is likely the user's first time using the key manager so we don't need to cryptographically verify it. We will need to make the user enters it twice on the front-end in this case, though).

Here is a preview of the current key manager (key mounting on dev builds isn't this fast, but they will be in prod):

https://user-images.githubusercontent.com/77554505/199038410-0d21c5c5-4ec6-48e3-aad8-2e139978c22f.mp4

2022-11-01 06:29 UTC, jamiepine commented
<img width="1221" alt="CleanShot 2022-10-31 at 23 29 03@2x" src="https://user-images.githubusercontent.com/32987599/199172755-0f94b14b-8460-4dce-a761-b46777f7eeba.png">
I'm getting a core crash when adding a key

2022-11-01 07:41 UTC, brxken128 commented
> <img width="1221" alt="CleanShot 2022-10-31 at 23 29 03@2x" src="https://user-images.githubusercontent.com/32987599/199172755-0f94b14b-8460-4dce-a761-b46777f7eeba.png">
> I'm getting a core crash when adding a key

That's pretty odd, I'll take a look into it

2022-11-01 07:55 UTC, brxken128 commented
Converted to draft for now, there's quite a few unwraps that I'm not happy with

2022-11-01 10:27 UTC, Brendonovich commented on core/src/api/keys.rs
> +				library.key_manager.mount(key_uuid).map_err(|_| {
It would be much better for these `Error` -> `rspc::Error` implementations to be done in an `Into<rspc::Error>` implementation. Repeating this code everywhere is not great haha.

2022-11-01 10:28 UTC, brxken128 commented on core/src/api/keys.rs
> +				library.key_manager.mount(key_uuid).map_err(|_| {
I did ask Oscar about this as I wasn't too confident or happy with it, but yeah I'll fix that. Thanks!

2022-11-01 12:44 UTC, brxken128 commented
Going to close this for now, after some thorough testing there's a few more bugs that I'm not happy with.

2022-11-02 09:10 UTC, brxken128 commented
Re-opening this as I believe the most critical issues/bugs have been solved. I am going to be adding a dedicated master password verification feature, but I think that needs a separate PR.

2022-11-02 09:54 UTC, Brendonovich requested changes

2022-11-02 09:54 UTC, Brendonovich commented on core/prisma/schema.prisma
> +  automount Boolean
Before this PR is merged a new migration must be generated

2022-11-02 09:54 UTC, Brendonovich commented on core/src/api/keys.rs
> +				let algorithm = match &args.algorithm as &str {
This and `hashing_algorithm` should be enums

2022-11-02 09:54 UTC, Brendonovich commented on packages/interface/src/components/key/Key.tsx
> +		<DropdownMenu.Portal forceMount>
formatting

2022-11-02 09:54 UTC, Brendonovich commented on packages/interface/src/components/key/Key.tsx
> +	const { mutate: mountKey } = useLibraryMutation('keys.mount');
Don't destructure mutations, just use `.mutate` without aliasing

2022-11-02 09:54 UTC, Brendonovich commented on packages/interface/src/components/key/KeyList.tsx
> +	const unmountedKeys: QueryKey[] = keys.data?.filter(key => !mounted_uuids.data?.includes(key.uuid)) ?? []
Might be worth putting these in `useMemo`

2022-11-02 09:54 UTC, Brendonovich commented on packages/interface/src/components/key/KeyMounter.tsx
> +	const { mutate: createKey } = useLibraryMutation('keys.add');
Said it earlier but don't destructure mutations. Might try get it in an eslint rule.

2022-11-02 11:14 UTC, brxken128 commented on core/src/api/keys.rs
> +				let algorithm = match &args.algorithm as &str {
I tried to do this, but `value=` within the `KeyMounter` is required to be a string AFAIK and I just couldn't get it to work.

2022-11-02 11:51 UTC, brxken128 commented on core/prisma/schema.prisma
> +  automount Boolean
Should be done in ed3e4ca58aadb7fb2e130a5cd0bf35d1499a00f6.

2022-11-02 12:49 UTC, brxken128 commented on core/src/api/keys.rs
> +				let algorithm = match &args.algorithm as &str {
Got it. It's not the cleanest, nor is it perfect, but it's better than giving Rust a String.

2022-11-05 07:33 UTC, jamiepine approved these changes

2022-11-05 09:43 UTC, utkubakir commented on packages/interface/src/components/key/KeyMounter.tsx
> +	const { mutate: createKey } = useLibraryMutation('keys.add');
Any reason for not destructuring? I guess it looks cleaner if the component has several mutations.

2022-11-05 09:50 UTC, Brendonovich submitted a review, later dismissed

2022-11-05 09:51 UTC, Brendonovich commented
Please rustfmt and should be good to go

2022-11-05 11:17 UTC, jamiepine approved these changes

2022-11-05 11:18 UTC, merged