Node version
spacedriveapp/spacedrive pull request #458
Opened 2022-11-03 05:22 UTC by PyRo1121

Updated .NPMRC to include `engine-strict=true` as per the pnpm docs listed in issue by putting the node version only in package.json it does not carry they requirement across the project. This also would allow future contributions to include dependencies that don't fall in line with the projects path and requirements.

[Issue #457 ]

Closes #(issue)
1

2022-11-05 13:35 UTC, maxichrome submitted a review, later dismissed
Thanks for the suggestion & the patch. A few notes in my review but overall I approve. Thanks PyRo!

2022-11-05 13:35 UTC, maxichrome commented on .npmrc
> +engine-strict=true
Good addition!

2022-11-05 13:35 UTC, maxichrome commented on package.json
> +		"pnpm": ">=7.0.0",
We might even consider bumping this to contain a minimum minor version, just in case bug fixes/additions were made which we utilize and don't realize are missing in older minor versions (unlikely but possible).

```suggestion
		"pnpm": ">=7.14.0",
```

2022-11-05 13:35 UTC, maxichrome commented on package.json
> +		"node": ">=17.0.0"
We might consider:

- adding a minimum Node version here
- adding a `.nvmrc` file so users using _nvm_ or _fnm_ can take advantage of those tools' easy Node version switching

2022-11-05 17:18 UTC, PyRo1121 commented on package.json
> +		"node": ">=17.0.0"
I thought about the .nvmrc as well but wasn't sure if y'all wanted to add more. I think it would be really beneficial as user myself of nvm

2022-11-05 17:36 UTC, PyRo1121 commented on package.json
> +		"node": ">=17.0.0"
I will say with adding `.nvmrc` I don't believe there is a way to set the version to be >= so I thought the best solution if we add that would be LTS/*

2022-11-05 17:58 UTC, PyRo1121 commented
Adding to this and I apologize I took your advice and didn't mean to dismiss it @maxichrome. We might want to update the `@type/node` on all 'package.json` as it is the type definitions for node.

2022-11-06 02:09 UTC, Brendonovich requested changes

2022-11-06 02:09 UTC, Brendonovich commented on .nvmrc
> +lts/*
The [contributing guide](https://github.com/spacedriveapp/spacedrive/blob/main/CONTRIBUTING.md) recommends Node v17, this should probably be enforced here.
```suggestion
v17
```

2022-11-06 02:11 UTC, Brendonovich commented
Turns out Vercel only support Node 16, guess we're using 16 instead of 17 then.

2022-11-06 09:05 UTC, maxichrome approved these changes
All looks good to me now

2022-11-06 09:07 UTC, merged