integrate keymanager with library creation flow
spacedriveapp/spacedrive pull request #491
Opened 2022-12-21 09:51 UTC by oscartbeaumont

2022-12-21 16:55 UTC, brxken128 reviewed
sorry for the delay with checking over it! things look great, i'll give it a build quickly and make sure everything is looking good there too. thank you :)

2022-12-21 16:55 UTC, brxken128 commented on crates/crypto/src/keys/keymanager.rs
> +		creds: PasswordAndSecret,
the credentials need to be generated in here, as we provide the master password and secret key to begin with (annoying, but extremely secure). the user is free to change it afterwards - i plan to revise this eventually.

2022-12-21 16:55 UTC, brxken128 commented on crates/crypto/src/keys/keymanager.rs
>  		// BRXKEN128: REMOVE THIS ONCE ONBOARDING HAS BEEN DONE
we can un `_` the variables above, and remove the statically set password/salt beneath (and the length check) as the master password/salt are generated in this function

2022-12-21 16:55 UTC, brxken128 commented on crates/crypto/src/keys/keymanager.rs
> +		creds: PasswordAndSecret,
we could keep it this way, i don't inherently have anything against it. maybe i should add a passphrase generation function to master password changing.

2022-12-21 16:55 UTC, brxken128 commented on crates/crypto/src/keys/keymanager.rs
>  		// BRXKEN128: REMOVE THIS ONCE ONBOARDING HAS BEEN DONE
^ closing this as it's related to the other comment

2023-01-03 14:46 UTC, brxken128 requested changes

2023-01-03 14:46 UTC, brxken128 commented on packages/interface/src/components/dialog/CreateLibraryDialog.tsx
> +				{/* TODO: Proper UI for this. Maybe checkbox for encrypted or not and then reveal these fields. Select encrypted by default. */}
Library encryption itself isn't supported yet, but the key manager shouldn't be restricted to encrypted libraries only

2023-01-03 14:46 UTC, brxken128 commented on packages/interface/src/components/dialog/CreateLibraryDialog.tsx
> +				<span className="text-sm">Make password and secret fields empty to skip key setup.</span>
Setup can't be skipped, the key manager *needs* a verification key created before it can ever be unlocked. There isn't support for adding one after the fact

2023-01-03 14:46 UTC, brxken128 commented on packages/interface/src/components/dialog/CreateLibraryDialog.tsx
> +					/>
The secret key *can't* be generated by the user - this is what the onboarding function did. If we allow the user to arbitrarily set a salt, security will be heavily lowered. Once we move the secret key to a pepper, we can remove the need for a secret key at all for users who don't like the functionality.

2023-01-03 14:46 UTC, brxken128 commented on packages/interface/src/components/dialog/CreateLibraryDialog.tsx
> +						placeholder="password"
I think the password here should be an autogenerated passphrase at first, so the user can either keep that or change it to one of their own that they like. That offers a nice balance between secure-by-default and not too annoying, imo. Maybe we could have a refresh icon to auto-generate a new passphrase too.

2023-01-03 14:46 UTC, brxken128 commented on core/src/library/library_manager.rs
>  	let mut default = Uuid::nil();
Not your fault, just an afterthought, but we can probably use an option for this. Not sure why I decided a nil-UUID would be suitable here.

2023-01-03 14:46 UTC, brxken128 commented on core/src/api/keys.rs
> -		})
We'll need this to some extent. Secret keys should be generated within Rust, and should **not** have the opportunity to be changed at all through JS, at least not yet.

2023-01-03 16:11 UTC, brxken128 approved these changes
Awesome work! Things are functioning great, and I'll open a PR to address the changes we discussed on Slack (optional secret key, optional key manager initialisation, etc).

2023-01-03 16:13 UTC, oscartbeaumont commented
Thanks, for the review and your help with this PR @brxken128!

2023-01-03 16:13 UTC, merged