[ENG-328] Keymanager mounting queue
spacedriveapp/spacedrive pull request #514
Opened 2023-01-11 16:12 UTC by brxken128

This PR adds a key manager mounting queue, and a few routes for checking the mount status of certain keys. It uses a Rust `DashSet` internally (for the hardcoded/externally immutable queue - this one will help protect us against malicious clients and DOS attacks due to memory-hard hashing algorithms).

The Rust queue is used for only one (external) route - checking if the key manager is currently being unlocked. This is used multiple times throughout the app, so a route will likely be best. The `set_master_password()` function also temporarily takes an `invalidate` closure, so we can invalidate the query correctly within the crypto crate. With this, users cannot attempt to unlock the key manager multiple times, no matter where in the app they are (or where they first started the unlock).

The Rust queue is used and updated heavily within the key manager, and protections have been added to relevant functions in order to protect against a malicious client (one where the React queue has been removed).

We also use a `const Set<string>` within React, so that the UI is reactive without cluttering RSPC. This `Set` is passed to each key individually, so they can view and update their status accordingly. Users won't be able to mount the same key multiple times. A "Mounting..." status was also added for keys that are in the process of being mounted, so that users stay informed.

I have tested these changes and didn't notice any oddities! Things work great.

2023-01-11 16:37 UTC, Brendonovich requested changes
defs need a review from @oscartbeaumont, idk what's going on with that frontend queue but if it's necessary then all good i guess

2023-01-11 16:37 UTC, Brendonovich commented on packages/interface/src/components/key/KeyList.tsx
> +const mountingQueue = new Set<string>();
put this in a `useRef` in the component and access it with `mountingQueue.current`. not a huge change but is more react-y

2023-01-11 16:49 UTC, oscartbeaumont commented
Just chatted with @Brendonovich and he thinks we can remove the `Set` and instead use optimistic UI with React Query. If this can be done it makes way more sense. I will give this a shot tomorrow.

2023-01-17 14:18 UTC, Brendonovich approved these changes

2023-01-17 14:19 UTC, merged