Desktop - Add more tooltips
spacedriveapp/spacedrive pull request #519
Opened 2023-01-12 18:59 UTC by JeremyMoeglich

This PR adds tooltips to many buttons that didn't have them before.
List of locations where tooltips were added in the format {location}: {tooltip}

1. Sidebar - Settings icon: "Settings"
2. Sidebar - Jobs icon next to Settings: "Recent Jobs"
3. ExplorerTopBar - Key Icon: "Unlock"
4. ExplorerTopBar - Three Lines: "File Display Options"
5. ExplorerTopBar - Inspector Toggle: Either "Show Inspector" or "Hide Inspector"
6. Library Settings - Database Icon: "TODO" What will this button do? It doesn't do anything currently
7. Library Settings - Edit Icon: "Edit Location"
8. Library Settings - Trash Can: "Delete Library"
9. Location Settings  - Trash Can: "Delete Location"
10. Location Settings - Retry Icon: "Rescan Location"
11. Tags Settings - Trash Can: "Delete Tag"

2023-01-13 14:20 UTC, brxken128 requested changes
looks pretty good! i'll give this a spin up when i can just to confirm they all work, iirc there were some oddities with the items in the top bar and getting tooltips to show correctly, but i may be misremembering.

thank you!

2023-01-13 14:20 UTC, brxken128 commented on packages/interface/src/components/explorer/ExplorerTopBar.tsx
> +						<Tooltip label="Unlock">
this should say "Key manager" :)

2023-01-13 17:46 UTC, JeremyMoeglich commented on packages/interface/src/components/explorer/ExplorerTopBar.tsx
> +						<Tooltip label="Unlock">
Done,
I'm still trying to understand many parts of the repo might try to make the add tag button in the inspector work next.
Certainly some of the best code Ive seen

2023-01-15 09:49 UTC, Brendonovich requested changes
very helpful, thanks for this!

2023-01-15 09:49 UTC, Brendonovich commented on packages/interface/src/components/explorer/FileItem.tsx
> +	const fullName = `${data.name ?? ''}${data.extension ? `.${data.extension}` : ''}`;
Not a fan of this, utilising JSX's ability to ignore `undefined` and `null` is much nicer than ternaries with empty strings imo

2023-01-15 10:37 UTC, JeremyMoeglich commented on packages/interface/src/components/explorer/FileItem.tsx
> +	const fullName = `${data.name ?? ''}${data.extension ? `.${data.extension}` : ''}`;
Changed it back to how it was before

2023-01-16 16:58 UTC, brxken128 approved these changes
thanks for the changes! finally got around to testing them and i'm happy with them - they all seem to be working great.

2023-01-17 01:31 UTC, Brendonovich approved these changes

2023-01-17 01:32 UTC, merged