Handle .spacedrive existing instead of throwing error
spacedriveapp/spacedrive pull request #521
Opened 2023-01-13 22:32 UTC by fogodev

Removing metadata files that failed to be deserialized, this can happen due to an older version of these `.spacedrive` metadata files, before this feature was actually implemented, or if the file was corrupted.

2023-01-15 09:38 UTC, Brendonovich commented on core/src/location/metadata.rs
> +						fs::remove_file(&metadata_file_name).await.map_err(|e| {
Might be worth doing this conditionally so that files aren't accidentally deleted in prod

2023-01-15 09:39 UTC, Brendonovich requested changes
Works fine for dev but we probs wanna be careful to not forget about this

2023-01-17 00:04 UTC, fogodev commented on core/src/location/metadata.rs
> +						fs::remove_file(&metadata_file_name).await.map_err(|e| {
You're totally right, this is an excellent point, I introduced back the deserialize error, but only for production builds. This way, if this problem happens again in the future, we can introduce some kind of versioning schema without the using losing important metadata.

2023-01-17 14:16 UTC, Brendonovich approved these changes

2023-01-17 14:17 UTC, merged