[ENG-345] Cut, copy and duplicate filesystem actions
spacedriveapp/spacedrive pull request #528
Opened 2023-01-18 15:02 UTC by brxken128

Well, I'd be lying if I said this task was fun. Things are fully working, but Windows may have some issues and will require further testing.

This isn't my best work, but Rust path handling clearly isn't too great (same with all lang's path handling, if I'm being honest).

Duplicating a file or directory will append ` - Clone` to the original name, but there is a caveat. Rust cannot detect `.tar.gz` as a whole (complete) extension, and instead the extension is denoted as `.gz` (which is technically correct, but not ideal). There's not much I can do here, so `important.tar.gz` becomes `important.tar - Clone.gz`. This issue isn't relevant for directory duplication. It was either this, or splitting from the first `.` (in this case, `3459.29854.2358.pdf` would become `3459 - Clone.29854.2358.pdf`). I heavily prefer the former, and I assume the majority of our userbase will too.

Duplication uses the same code as copy, there is just some output path wizardry going on beforehand.

No checks are currently in place to protect against copy/pasting to the same path, which according to the Rust docs, will end up with the files being truncated. It may be wise to add this before the PR gets merged. ~~(Things should probably become `async` too).~~

This PR will have to remain as a draft, as I pulled in `fs::delete` and `fs::erase` from my other branch - these will need cherry-picking out.

As an additional note, the file watcher/explorer has some trouble with a few things. Sometimes copied files aren't automatically shown in the explorer, and when you copy a directory such as `dir v1.0.0` it will show in the explorer as `dir v1.0`, as though it's trying to hide the "extension". A similar thing happens with duplication - `dir v1.0` will be shown instead of the correct `dir v1.0.0 - Clone`. Manually re-indexing solves both of these problems entirely.

We could also do with lowering the opacity/making cut file icons grey, so users can see what has been cut. Maybe showing the currently copied/cut file somewhere in the explorer would be cool too.

2023-01-20 21:32 UTC, fogodev requested changes
Also these new Jobs must be included at this match, so they are included in the resume job feature (we probably have to make this better in the future, remembering to include in this match sucks...). https://github.com/spacedriveapp/spacedrive/blob/e4e80fa603c283f240884a7c76c3e0e3badcf7b4/core/src/job/job_manager.rs#L199-L226

2023-01-20 21:32 UTC, fogodev commented on core/src/object/fs/copy.rs
>  					.map_or(Ok::<_, JobError>("".to_string()), |x| {
Just resolved these lol

2023-01-23 11:58 UTC, Brendonovich approved these changes

2023-01-23 12:29 UTC, fogodev approved these changes

2023-01-23 12:31 UTC, merged