[ENG 239] Onboarding Flow
spacedriveapp/spacedrive pull request #529
Opened 2023-01-18 19:12 UTC by jamiepine

This is a very basic implementation of onboarding. It is missing animated transitions, extra screens and better loading state during library creation.

https://user-images.githubusercontent.com/32987599/213265214-6289fa50-962f-4211-b882-ec5064bdc0c8.mov

2023-01-18 19:37 UTC, jamiepine commented
Okay I'm about to build the "creating library" screen, also means we can have skippable steps in the library creation process

2023-02-08 03:56 UTC, Brendonovich requested changes
make ci pass and answer questions and i'm happy

2023-02-08 03:56 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    pending Boolean @default(false)
Can you elaborate on this? I'm a little nervous creating owned data for a non-owner node.

2023-02-08 03:56 UTC, Brendonovich commented on core/src/api/libraries.rs
> +				tokenized_password: Option<String>,
Could this be an enum allowing for one or the other but not both?

2023-02-08 03:56 UTC, Brendonovich commented on core/src/api/locations.rs
> +					.include(indexer_rules_in_location::include!({ indexer_rule }))
This might work better as a query on `indexer_rules` with a filter of `indexer_rules::locations::some(vec![indexer_rules_in_location::location_id::equals(location_id)])`

2023-02-08 03:56 UTC, Brendonovich commented on core/src/location/mod.rs
> +		}
Personally I'd prefer this done as an array of `Option<SetParam>` which you `flatten` to get rid of `None` values, that way you can avoid most of the `if let Some` checks.

2023-02-08 03:56 UTC, Brendonovich commented on packages/client/src/stores/onboardingStore.ts
> +}
would rather a `const` than an `enum` but ehh

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingCreatingLibrary.tsx
> +		}
This could be moved into `create` if you use `mutateAsync`

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingMasterPassword.tsx
> +			});
`mutateAsync` would be nice here so that the form gets disabled until the operation completes + you can move `onSuccess` and `onError` in

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingNewLibrary.tsx
> +		return;
```suggestion
```

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingNewLibrary.tsx
> +							size="md"
this happens bc `InputProps` is an intersection of cva + regular props, doing `Omit<..., 'size'>` for the base props would fix this and only use cva's `size` prop.

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingPrivacy.tsx
> +	shareTelemetryDataWithDevelopers: z.string()
maybe use a literal union for added typesafety?

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingPrivacy.tsx
> +						render={({ field }) => (
ideally this would be a `useController` and be hidden away in `ui/src/forms/RadioGroup.tsx`, I can implement that if you want.

2023-02-08 03:56 UTC, Brendonovich commented on packages/interface/src/screens/settings/library/location/EditLocation.tsx
> +		});
i'm guessing you're not using `mutateAsync` so that the whole page isn't disabled?

2023-02-08 03:56 UTC, Brendonovich commented on packages/ui/src/RadioGroup.tsx
> +					'focus:outline-none focus:ring-0 focus:ring-offset-0 focus-visible:ring focus-visible:ring-accent focus-visible:ring-opacity-75 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-gray-80
i didn't think we use `dark:` since we do themes?

2023-02-08 05:33 UTC, jamiepine commented on core/prisma/schema.prisma
> +    pending Boolean @default(false)
Well as the app inherently allows you to browse locations that are offline, they would currently need to be read-only. I had always imagined that we would allow users to organize files for online and offline locations just the same. Changes to offline locations would happen optimistically and be applied later once the location comes online. This was one way I thought it could be accomplished.

2023-02-08 05:33 UTC, jamiepine commented on core/src/api/libraries.rs
> +				tokenized_password: Option<String>,
It very much should be an enum

2023-02-08 05:35 UTC, jamiepine commented on core/src/api/locations.rs
> +					.include(indexer_rules_in_location::include!({ indexer_rule }))
Yeah I let copilot do this one, I'm almost clueless when it comes to querying relations with PCR, might need a refresher crash course. I did notice the data was not returned ideally.

2023-02-08 05:36 UTC, jamiepine commented on core/src/location/mod.rs
> +		}
Not sure how to accomplish this one.

2023-02-08 05:36 UTC, jamiepine commented on packages/client/src/stores/onboardingStore.ts
> +}
Like an object? What would the const

2023-02-08 05:37 UTC, jamiepine commented on packages/interface/src/components/onboarding/OnboardingCreatingLibrary.tsx
> +		}
create?

2023-02-08 05:40 UTC, jamiepine commented on packages/interface/src/components/onboarding/OnboardingMasterPassword.tsx
> +			});
You might have to show me what you mean here cause I don't follow. I was under the impression mutateAsync went against the conventions of react hook form.

2023-02-08 05:40 UTC, jamiepine commented on packages/interface/src/components/onboarding/OnboardingNewLibrary.tsx
> +							size="md"
Where would the Omit type go?

2023-02-08 05:41 UTC, jamiepine commented on packages/interface/src/components/onboarding/OnboardingPrivacy.tsx
> +	shareTelemetryDataWithDevelopers: z.string()
Will look into how to do that.

2023-02-08 05:42 UTC, jamiepine commented on packages/interface/src/components/onboarding/OnboardingPrivacy.tsx
> +						render={({ field }) => (
Thought of doing this, figured I'd just do it later. You can if you want.

2023-02-08 05:42 UTC, Brendonovich commented on packages/client/src/stores/onboardingStore.ts
> +}
Same as the enum, dw about it

2023-02-08 05:42 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingCreatingLibrary.tsx
> +		}
The function you define further down

2023-02-08 05:43 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingMasterPassword.tsx
> +			});
Nah `mutateAsync` is great since `handleSubmit` takes an async function, we can keep the form in a disabled/loading state until the function is done.

2023-02-08 05:44 UTC, Brendonovich commented on packages/interface/src/components/onboarding/OnboardingNewLibrary.tsx
> +							size="md"
On the `React.HTMLInputAttributes` of `InputProps` in `ui/src/Input.ts`

2023-02-08 05:44 UTC, jamiepine commented on packages/interface/src/screens/settings/library/location/EditLocation.tsx
> +		});
Same as above, I'm just not used that pattern with React Query

2023-02-08 05:45 UTC, jamiepine commented on packages/ui/src/RadioGroup.tsx
> +					'focus:outline-none focus:ring-0 focus:ring-offset-0 focus-visible:ring focus-visible:ring-accent focus-visible:ring-opacity-75 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-gray-80
Copilot moment, missed that.

2023-02-08 05:46 UTC, Brendonovich commented on core/src/location/mod.rs
> +		}
I'll do it if u want, also should `location.name` really be optional? I'd imagine each location should be required to have a name, even if it is empty.

2023-02-08 05:46 UTC, jamiepine commented
CI did pass until I merged main 😭

2023-02-08 06:03 UTC, jamiepine commented on core/src/location/mod.rs
> +		}
Oh absolutely, but what if I don't want to update the name? I should submit the same name anyway?

2023-02-08 06:07 UTC, Brendonovich commented on core/src/location/mod.rs
> +		}
I mean optional in the schema, being optional in the args is fine.
<img width="283" alt="image" src="https://user-images.githubusercontent.com/14191578/217448595-98d2881f-4125-4535-b0a9-70ba70d1616f.png">

2023-02-08 08:09 UTC, utkubakir commented on packages/interface/src/components/explorer/FileItem.tsx
> +	const isVid = ObjectKind[objectData?.kind || 0] === 'Video';
FYI: Mobile needs this too, I moved most of the utils (ObjectKind, isObject, isPath etc.) desktop uses to `@sd/client` on my `mobile-inspector` branch

2023-02-08 13:46 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    pending Boolean @default(false)
I'd like if we held off on this, `pending` isn't used anywhere yet and I'd like for some more discussion around this topic.

2023-02-08 14:41 UTC, fogodev requested changes

2023-02-08 14:41 UTC, fogodev commented on core/src/location/mod.rs
> +	subpath: &PathBuf,
We're using `impl AsRef<Path>` in most places to accept any kind of type that can be a reference to a `Path`. If this function will still be used, it would be nice to change the type, otherwise just remove the unused function.

2023-02-08 16:50 UTC, Brendonovich commented on core/src/api/libraries.rs
> +						// TODO: remove unwraps
Fixed with the `AuthOptions` enum

2023-02-08 21:39 UTC, jamiepine commented on core/prisma/schema.prisma
> +    pending Boolean @default(false)
I'll write up a linear issue instead.

2023-02-08 22:07 UTC, jamiepine commented on core/prisma/schema.prisma
> +    pending Boolean @default(false)
I'm having an issue running `pnpm prisma migrate dev`: 

> Migration `20230202133507_keytype` failed to apply cleanly to the shadow database.

Could you remove this and run migrations for me? I already reverted because I want to continue.

2023-02-09 00:22 UTC, jamiepine commented on core/src/object/fs/create.rs
> +// }
Its fine to leave it there for now I'll, make a separate PR to pick up from here.

2023-02-10 18:03 UTC, fogodev submitted a review, later dismissed

2023-02-10 22:08 UTC, merged