[ENG-348] Asynchronous crypto
spacedriveapp/spacedrive pull request #549
Opened 2023-01-24 16:38 UTC by brxken128

This PR adds asynchronous crypto to the crypto crate, namely to everything that deals with streams/IO.

This also fixes broken crypto dialogs that were missing default values.

I have tested the changes, and things work as expected.

I plan to do some performance benchmarking, to see if we gain any noticeable improvement. I don't expect much, but a little boost would be nice.

2023-01-25 13:44 UTC, brxken128 commented
Marking this as ready for review. Encryption is pretty slow due to `tokio`'s internal read buffer size, but I plan to use `tokio` as a git dependency and use 2MiB internal buffers (at least until it's changed upstream) - this will require some manual testing on all platforms to make sure nothing breaks.

For now, this does successfully bring in working asynchronous crypto.

2023-01-25 18:23 UTC, fogodev requested changes

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/header/metadata.rs
> +		}
This match can also be an if let with else

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/header/preview_media.rs
> +		}
This match can also be an if let with else

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/header/preview_media.rs
> +		}
Another match on Option

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/keys/keymanager.rs
>  use crate::{Error, Result};
These `use crate` can be unified

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/keys/keymanager.rs
> +	root_key: Mutex<Option<Protected<Key>>>, // the root key for the vault
Beware that these sync Mutexes's locks mustn't be held across await points

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/keys/keymanager.rs
> +		match self.keystore.get(&uuid) {
Matching on Option instead of if let with else

2023-01-25 18:23 UTC, fogodev commented on crates/crypto/src/keys/keymanager.rs
> +		match self.keystore.get(&uuid) {
Match on Option

2023-01-25 18:24 UTC, brxken128 commented on core/src/api/keys.rs
> +						.await?;
Not wise at all, that could potentially result in 6gb+ of memory used with just 12 keys.

2023-01-25 18:33 UTC, fogodev commented on core/src/api/keys.rs
> +						.await?;
Damn boy, didn't know that lol, all good then

2023-01-26 10:43 UTC, brxken128 commented on core/src/api/keys.rs
> +						.await?;
I have thought about the idea previously, where we could potentially use `rayon` and dispatch them in batches relative to the total memory cost, although it's likely more effort than it's worth. It would probably result in faster automounting time, but at the cost of pretty high memory usage.

In prod builds on a modern machine, it happens quick enough that it's not an issue and it doesn't delay unlocking the key manager or anything like that.

2023-01-26 11:37 UTC, Brendonovich commented on core/src/api/keys.rs
>  					write_storedkey_to_db(&library.db, key).await?;
This should actually be a `create_many` so that they're all batched

2023-01-26 21:01 UTC, fogodev approved these changes

2023-01-27 07:09 UTC, Brendonovich commented on crates/crypto/src/primitives.rs
> +pub type Salt = [u8; SALT_LEN];
I'd like if newtype structs were used here, they allow for much more flexibility with traits and functions, and make types much stricter.

2023-01-27 07:15 UTC, Brendonovich requested changes

2023-01-27 07:15 UTC, Brendonovich commented on packages/interface/src/components/dialog/DecryptFileDialog.tsx
> +			output_path: data.outputPath !== '' ? data.outputPath : null,
Not a fan of this check, would much rather the core deal with a blank string than the client have to specify default values. Keep in mind you can use `required` on inputs if you really need them to specify a value.

2023-01-27 07:15 UTC, Brendonovich commented on packages/interface/src/components/dialog/MasterPasswordChangeDialog.tsx
> +			masterPassword2: ''
Same stuff about default values here, if they must have a value then try to use `required`.

2023-01-27 07:26 UTC, brxken128 commented on packages/interface/src/components/dialog/DecryptFileDialog.tsx
> +			output_path: data.outputPath !== '' ? data.outputPath : null,
It's not required though. The check is there so rspc properly sends through a `None` value.

2023-01-27 07:28 UTC, Brendonovich commented on packages/interface/src/components/dialog/DecryptFileDialog.tsx
> +			output_path: data.outputPath !== '' ? data.outputPath : null,
Ehh why not just make rspc handle the empty string and not need a `None` in the first place

2023-01-27 07:29 UTC, brxken128 commented on packages/interface/src/components/dialog/MasterPasswordChangeDialog.tsx
> +			masterPassword2: ''
Encryption and hashing algorithms need default values otherwise the Select boxes remain completely empty and broken on first launch. The first password needed a default value because the password meter crashed the entire app while it tried evaluating `password.length` with no password at all.

2023-01-29 10:39 UTC, Brendonovich commented on packages/interface/src/components/dialog/DecryptFileDialog.tsx
> +			output_path: data.outputPath !== '' ? data.outputPath : null,
gonna worry about this later

2023-01-29 10:40 UTC, Brendonovich commented on packages/interface/src/components/dialog/MasterPasswordChangeDialog.tsx
> +			masterPassword2: ''
gonna worry about this later

2023-01-29 10:40 UTC, Brendonovich approved these changes

2023-01-29 10:47 UTC, Brendonovich commented on crates/crypto/src/primitives.rs
> +pub type Salt = [u8; SALT_LEN];
can do this later

2023-01-29 11:00 UTC, merged