fix `spacedrive://` custom protocol on Windows
spacedriveapp/spacedrive pull request #550
Opened 2023-01-25 03:57 UTC by oscartbeaumont

2023-01-25 13:14 UTC, oscartbeaumont commented
@jamiepine this works and is ready for use.

I would appreciate it if @brxken128 could give it a shot on Linux because I am concerned about if video files will work on Linux. I don't think it will stream video files on Linux and as far as I'm aware this is a Tauri limitation. It should instead, I am hoping, just load it all into memory and sends it to the webview. We could build a custom protocol to work around this limitation but that is a future concern.

@james-elicx I would appreciate a test of preview media loading on Windows (although don't feel obligated to). I was unable to use the Rust code snippet you sent as it was causing issues on macOS. The system I designed converts the `spacedrive://` (Linux/macOS style) to `http://spacedrive.localhost` (Windows style) and then the code works on that. This choice was because the URL parser in the `http` crate expects a full URL. Thanks for reporting the Windows issue!

Right now I added a button to the right-click menu on an explorer item to test this feature. It does a full webview redirect which is something that @jamiepine is going to improve when the UI he is working on is ready.

2023-01-25 14:02 UTC, james-elicx commented
> @james-elicx I would appreciate a test of preview media loading on Windows (although don't feel obligated to). I was unable to use the Rust code snippet you sent as it was causing issues on macOS. The system I designed converts the `spacedrive://` (Linux/macOS style) to `http://spacedrive.localhost` (Windows style) and then the code works on that. This choice was because the URL parser in the `http` crate expects a full URL. Thanks for reporting the Windows issue!
> 

I'm happy to try it out. Thanks for looking into the issue. Unfortunately, at the moment, it throws `Bad request: Invalid operation!`.

This is because on Windows, the request URI you get in the `register_uri_scheme_protocol` handler is in the format `spacedrive://localhost/thumbnail%2F27cc1db92478b45b`. Tauri appears to internally transform the request from `spacedrive.localhost` to `spacedrive://localhost`.

This means that the replaced URI ends up being `https://spacedrive.localhost/localhost/thumbnail%2F4b6c8875aef65af3` since you replace the `spacedrive://` part, leaving the first item in the path inside your `handle_custom_uri` function as `localhost`.

In the Tauri examples, they use `.strip_prefix("spacedrive://localhost/")` to get rid of this, although if you want to go down the replace route, I imagine you could do `let uri = uri.replace("spacedrive://localhost/", "spacedrive://");` so that requests from both OS start the same.

2023-01-25 14:12 UTC, oscartbeaumont commented
@james-elicx Thanks for taking the time to check it. I just pushed a change following your recommendation and hopefully, that should do it. Let me know if you find the time to test it!

2023-01-25 14:19 UTC, james-elicx commented
> @james-elicx Thanks for taking the time to check it. I just pushed a change following your recommendation and hopefully, that should do it. Let me know if you find the time to test it!

If you swap the two replaces around, it works :p

Just gotta do the Windows one first, otherwise, it's trying to replace a `spacedrive://localhost/` that isn't there due to the Unix one replacing the `spacedrive://` part already.

Many thanks for working on this :)

2023-01-25 14:33 UTC, oscartbeaumont commented
@james-elicx hopefully 3rd times a charm. Updated it again. Thanks for all of your help!

2023-01-25 17:04 UTC, oscartbeaumont commented
I have moved this back to draft and will try and fix it tommorow.

To make the video streaming work on Linux we need to upgrade Tauri to enable to the `linux-protocol-headers` feature. Upgrading Tauri breaks rspc. Upgrading rspc stops it working PCR. Updating PCR then allows the app to build but rspc is not:
 - Formatting the bindings file (would be super bad for PRs if not fixed)
 - Is just not exporting `FileEraserJobInit`, `FilePathWithObject`, `ObjectWithFilePaths` types

I will work on fixing these tomorrow and then hopefully we will have a bit more luck with Linux support. In the meantime this PR may not work and should be able to be fixed by downgrading the Tauri version in the `src/desktop/src-tauri/Cargo.toml`

2023-02-02 07:15 UTC, oscartbeaumont commented
This PR should be working now and it would be great if @brxken128 could check if video playback is working on Linux when he gets a minute. I would also appreciate a Windows test by @james-elicx if you can find the time.

I have upgraded Tauri (which required upgrading rspc, PCR & Axum to work). This has taken a while because in doing so I have revealed a bunch of issues in the main branch of rspc and the PCR integration for rspc but they are all fixed now.

Some changes to Spacedrive in this PR related to upgrading rspc:
 - Crypto package uses `rspc::Type` instead of `specta::Type` - Minor but will make sure we are always use the Specta version supported by rspc (very soon they are gonna split into two repos and will be versioned independently)
 - All bigint types (`usize`, `isize`, `i64`, `u64`, `i128`, `u128`) are now unsupported by rspc and must be string encoded to be sent through rspc. Previously these types were supported but`JSON.parse` would have lossily decoded them so I have decided to stop supporting them in rspc until I can build a solution.

The purpose behind upgrading Tauri was to allow us to enable the Tauri `linux-protocol-headers` feature which I am hoping makes video playback work on Linux. If it doesn't we might be a little screwed.

2023-02-02 13:44 UTC, james-elicx commented
> This PR should be working now and it would be great if @brxken128 could check if video playback is working on Linux when he gets a minute. I would also appreciate a Windows test by @james-elicx if you can find the time.

Looks like the protocol and thumbnails are working correctly on Windows now! I appreciate all the work you've done to fix this :)

2023-02-02 13:56 UTC, brxken128 commented
I've already spoken to @oscartbeaumont about this, but on Linux (Gentoo) it's a mixed bag. Thumbnails work, and opening images work, but video playback does not. It could either be a Tauri thing, or something to do with our protocol - I'm not too sure here.

We're making progress though as only thumbnails worked before.

2023-02-03 05:04 UTC, Brendonovich approved these changes

2023-02-03 05:04 UTC, Brendonovich commented on crates/crypto/src/crypto/stream.rs
> +#[cfg_attr(feature = "rspc", derive(rspc::Type))]
I'm guessing this has been changed bc of dependency versioning? Would be nice if it could stay as `specta` with a workspace patch or something.

2023-02-03 06:03 UTC, oscartbeaumont commented on crates/crypto/src/crypto/stream.rs
> +#[cfg_attr(feature = "rspc", derive(rspc::Type))]
This wasn't changed because it was needed but because it's my general recommendation when using rspc and I am going to start pushing it harder in the docs soon so wanted us to align with that.

Doing it this way is different to a workspace patch because instead of using _Spacedrive's_ version of Specta, the change uses the version of Specta _rspc_ expects. This makes it impossible for the rspc and Specta versions being mismatched and causing the annoying and very unhelped `the trait IntoLayerResult<_> is not implemented for type` compile error.

I also do not see any benefit to it staying `specta::Type` but given `rspc::Type` has this benefit I think it makes sense.

2023-02-09 09:03 UTC, Brendonovich requested changes

2023-02-09 09:03 UTC, Brendonovich commented on apps/desktop/src-tauri/src/main.rs
> +	let app = {
can this be in another file

2023-02-14 05:25 UTC, Brendonovich approved these changes

2023-02-14 05:27 UTC, merged