[ENG-363] Spacedrop UI + Misc Improvements
spacedriveapp/spacedrive pull request #568
Opened 2023-02-11 01:34 UTC by jamiepine

As requested by Oscar this is the UI for the Spacedrop functionality. This branch will also include a bunch of misc improvements, as listed below: 
- Seeded tags
- New Object icons for encrypted and compressed
- Better error fallback
- Default to inspector closed
- Add inspector button
- Slightly better 404 screen
- Added `_Layout.tsx` as a standard for screens
- Added `SearchInput` component
- Improved About Spacedrive screen
- Improved `Input` component sizes to align with `Button` component

2023-02-14 08:17 UTC, Brendonovich commented on packages/interface/src/screens/index.tsx
> +		element: lazyEl(() => import('./settings/_Layout')),
not a huge fan of `_Layout`, I think a nicer pattern would be for `./settings` to export the layout as a default, and `settingsScreens` be a named export. If we're going this far we also may as well switch to [`useRoutes`](https://reactrouter.com/en/main/hooks/use-routes) instead of the hybrid we're currently using.

2023-02-21 18:49 UTC, Brendonovich commented
@jamiepine hello sir

2023-02-23 22:29 UTC, Brendonovich requested changes

2023-02-23 22:29 UTC, Brendonovich commented on packages/interface/src/components/layout/Sidebar.tsx
> +						<NavLink to="/settings/tags">
should be a relative path

2023-02-24 05:07 UTC, oscartbeaumont submitted a review, later dismissed

2023-02-24 07:06 UTC, brxken128 commented on core/src/object/fs/decrypt.rs
> +					if ext == ".bytes" {
i quite like this change, very assertive as `.bytes` is extroadinarily generic

2023-02-24 07:11 UTC, brxken128 approved these changes
i quite like the change regarding encrypted file extensions, very assertive (in a great way) as `.bytes` is extroadinarily generic.

awesome work!

2023-02-24 07:56 UTC, Brendonovich commented on core/src/object/fs/decrypt.rs
> +					if ext == ".bytes" {
i'm pretty sure this shouldn't even be `.bytes` anyway
<img width="754" alt="image" src="https://user-images.githubusercontent.com/14191578/221123635-fcfd7905-9eb6-4b9b-b6b8-b022c2a8d7dc.png">

2023-02-24 07:57 UTC, brxken128 commented on core/src/object/fs/decrypt.rs
> +					if ext == ".bytes" {
it should be, jamie mentioned the change a while back iirc

2023-02-24 08:10 UTC, Brendonovich approved these changes

2023-02-24 08:12 UTC, merged