[ENG-379] Explorer item resizer
spacedriveapp/spacedrive pull request #580
Opened 2023-02-25 00:57 UTC by jamiepine

Adds the ability to resize items in the explorer grid view
- Added item resizer
- Fixed explorer store bug
- Refactored file image component

Closes #(issue)

2023-02-25 03:37 UTC, Brendonovich requested changes

2023-02-25 03:37 UTC, Brendonovich commented on packages/interface/src/components/explorer/FileColumns.tsx
> +]);
`ensureIsCoumns` is redundant - we have `satisfies`
```suggestion
export const columns = [
	{ column: 'Name', key: 'name', width: 280 } as const,
	// { column: 'Size', key: 'size_in_bytes', width: 120 } as const,
	{ column: 'Type', key: 'extension', width: 150 } as const,
	{ column: 'Size', key: 'size', width: 100 } as const,
	{ column: 'Date Created', key: 'date_created', width: 150 } as const,
	{ column: 'Content ID', key: 'cas_id', width: 150 } as const
] as const satisfies IColumn[];
```

2023-02-25 03:37 UTC, Brendonovich commented on packages/interface/src/components/explorer/FileColumns.tsx
> +					key={col.key}
may as well key on `col.column`, `col.key` is kinda redundant

2023-02-25 03:37 UTC, Brendonovich commented on packages/interface/src/components/explorer/FileRow.tsx
> +		<ExplorerItemContextMenu className="w-full" data={data}>
I seem to recall us not wrapping `File*` stuff with individual context menus before for perf reasons - is this not the case anymore?

2023-02-25 03:37 UTC, Brendonovich commented on packages/interface/src/components/explorer/VirtualizedList.tsx
> +						marginTop: `${TOP_BAR_HEIGHT + LIST_VIEW_HEADER_HEIGHT}px`
I don't think these need to be strings, react should let them just be numbers

2023-02-25 03:55 UTC, jamiepine commented on packages/interface/src/components/explorer/FileRow.tsx
> +		<ExplorerItemContextMenu className="w-full" data={data}>
It doesn't seem to be an issue, but it was not changed in this PR, just renamed.

2023-02-25 04:13 UTC, jamiepine commented on packages/interface/src/components/explorer/FileColumns.tsx
> +]);
@Brendonovich the suggested change didn't work here, IColumn has a type error because its "readonly".

2023-02-25 04:33 UTC, Brendonovich commented on packages/interface/src/components/explorer/FileColumns.tsx
> +]);
Ah, use `satisfies Readonly<IColumn[]>` instead

2023-02-25 06:16 UTC, Brendonovich approved these changes

2023-02-25 06:17 UTC, merged

2023-05-07 06:28 UTC, SusieInPhx commented
Image Resizer Bug
powertoys windows 11 image resizer hides folder names

Power Toys was installed on my Windows 11 PC today.  I ran lots of pics thru it successfully until now.
Suddenly from the current folder down the line thru all subsequent folders, even through to the Recycle Bin, the list of file names all appear to be a 'l' or a '!'.  Subfolders are not plagued this way, pressing the arrow to open up the heirarchy looks normal..
Clicking on the folder itself shows the path the way it should, including the correct folder name.

It is as though the folder names are hidden until clicking on them.
![image](https://user-images.githubusercontent.com/132804545/236661501-f19c8e5c-f80f-4ba1-a819-e02a5401d8bc.png)

2023-05-07 06:31 UTC, brxken128 commented
> Image Resizer Bug
> powertoys windows 11 image resizer hides folder names
> 
> Power Toys was installed on my Windows 11 PC today.  I ran lots of pics thru it successfully until now.
> Suddenly from the current folder down the line thru all subsequent folders, even through to the Recycle Bin, the list of file names all appear to be a 'l' or a '!'.  Subfolders are not plagued this way, pressing the arrow to open up the heirarchy looks normal..
> Clicking on the folder itself shows the path the way it should, including the correct folder name.
> 
> It is as though the folder names are hidden until clicking on them.
> ![image](https://user-images.githubusercontent.com/132804545/236661501-f19c8e5c-f80f-4ba1-a819-e02a5401d8bc.png)
> 
> 
> 

I'm failing to see how this is relevant? Did changing some settings in PowerToys break our app (Spacedrive)?