Fix adding Locations that already have a `.spacedrive` file
spacedriveapp/spacedrive pull request #627
Opened 2023-03-20 07:51 UTC by HeavenVolkoff

Hello,

This PR addresses the issue of adding locations that already have a `.spacedrive` file, either because they belong to other Libraries or because their linked directory has been moved.

I implements logic to handle both the `NeedRelink` and `AddLibraryToMetadata` errors raised by the backend when adding a new Location. When either of these errors occurs, a form error message is displayed to the user in `AddLocationDialog`, informing them that the location they are trying to add is either from another Library or needs to be relinked:
![image](https://user-images.githubusercontent.com/9082460/226271747-6304e350-1c3a-47d5-979f-8a64f2eb2e3f.png)
![image](https://user-images.githubusercontent.com/9082460/226271968-7e986feb-5bb7-4ff1-8647-48655c920608.png)

I decided to use the form's own error UI, as this usage flow is similar to a simple form validation error as the user may have added the wrong directory and may want to change the path after receiving the error message.

If the user continues with adding the Location, the appropriate method is called on the backend: either `locations.relink` or `locations.addLibrary`. The `addLibrary` logic is working correctly, as far as I tested. However, the `relink` method has some caveats. Because I couldn't find a way to get the Id of the Location that will be relinked it was not possible to update its indexer rules after relinking. Therefore, any rule changes made by the user in the form will be ignored during a relink. Additionally, I encountered some edge cases while testing this functionality with some unusual scenarios (such as restoring a `.spacedrive` file of a removed Location or moving a Location directory with the desktop app closed). The first resulted in an error, and the second caused the desktop app to stop opening until I restored the directory to its original location. As I'm unsure what the expected behavior is for these situations, I will open separate issues for them.

In addition to these changes, I also made the following improvements:
- Fixed a bug in `AddLocationDialog` that caused the indexer rules checkboxes not to track external changes made to the form state.
- Made minor changes to the errors raised by the backend when executing `locations.create`, giving them unique codes that the frontend can use to differentiate them.
- Abstracted the duplicated `openDirectoryPickerDialog` logic in `AddLocationButton` and `AddLocationDialog` into a function.

Closes #625.

2023-03-21 07:19 UTC, HeavenVolkoff commented
While reviewing these changes, I found a bug in handling rspc errors other than 404 and 409. Currently, it does not show an alert dialog informing the user of the error and instead closes the dialog as if the location was added successfully, when in fact nothing has happened. I will send a patch to fix this later.

2023-03-24 07:37 UTC, HeavenVolkoff commented
Backend errors are now handled correctly. Any error, except those with a 500 status code, will be displayed as a form error message. Adding locations that belong to other libraries or relinking moved locations works both in the desktop app and the web version. To address issues with the old logic, I changed the error message for backend errors that require custom submit logic in the frontend, namely `NeedRelink` and `AddLibraryToMetadata`, to correctly identify them. This is not a final solution, but a temporary workaround until rspc supports sending custom data alongside error messages.

2023-03-28 04:36 UTC, Brendonovich requested changes
Nice work! I don't like the error UI but that can stay that way so that Jamie has incentive to fix it.

2023-03-28 04:36 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
>  											}}
While we're here you may as well change this from HTML's `onChange` to Radix's `onCheckedChange`

2023-03-28 04:36 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	}
I'd prefer if `form` wasn't destructed, since there's nothing wrong with putting it as a `useEffect` dependency. Then the block isn't needed either.

2023-03-28 04:36 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	const onLocationSubmit = async ({ path, indexer_rules_ids }: FormFieldValues<typeof form>) => {
Putting this in an extra variable is cool, but I'd suggest moving the `form.handleSubmit` up here too so that we can benefit from type inference for the function arguments.

2023-03-28 06:56 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	}
I see your point. My original reasoning was to try minimizing the update scope of the useEffect hook. However, looking back at it now, it seems like an unnecessary premature optimization.

2023-03-28 07:09 UTC, Brendonovich approved these changes

2023-03-28 07:10 UTC, merged