[ENG-286] Set default indexer rules for location
spacedriveapp/spacedrive pull request #690
Opened 2023-04-11 07:33 UTC by HeavenVolkoff

This PR adds a new default indexer rule called `No OS protected`, which is intended to prevent the indexing of OS-protected files. To implement this rule, I had to modify the logic of the `AcceptFilesByGlob` and `RejectFilesByGlob` rules types to accept multiple globs and use a `GlobSet` for matching. The only potential issue with these changes is the `globset_from_globs` function, which creates a new GlobSet for each indexer rule during each directory/file check. While my testing didn't show any noticeable performance impact, the best approach would be to memoize it to execute only once for each indexer rule. However, I couldn't find a simple way to do this in Rust. If anyone has a solution, it would be greatly appreciated. Otherwise, I'll create a low-priority issue to address this later.

TODO: Still needs to test on macOS ~and Windows~

2023-04-11 20:00 UTC, brxken128 approved these changes
I'm uncertain regarding many of the actual rules themselves, but the Rust here is solid! Great job again haha

2023-04-15 07:01 UTC, HeavenVolkoff commented
Tested on Windows and Linux, by adding `root`/`C:` as locations, seems to be working fine. OS files were ignored.

2023-04-17 08:05 UTC, Brendonovich requested changes

2023-04-17 08:05 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +		defaultValues: useMemo(() => defaultValue, [defaultValue])
this `useMemo` doesn't do anything - it'll update each time `defaultValue` changes

2023-04-17 08:05 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	const { data: indexRules } = useLibraryQuery(['locations.indexer_rules.list'], {});
We prefer to not destructure `useQuery` calls, it's not worth it especially once you do multiple queries in the same component.

2023-04-17 08:05 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	);
I think `useLibraryQuery`'s `initialData` argument can be used instead of doing this

2023-04-17 08:05 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	}, [form, defaultValue]);
i really don't like this but we may be able to keep it

2023-04-17 08:05 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx
> +	const { data: indexRules } = useLibraryQuery(['locations.indexer_rules.list'], {});
no destructure plz

2023-04-17 17:47 UTC, HeavenVolkoff commented on .editorconfig
> +indent_style = space
The formatting, yes, but not the editor options. If you are also using the [EditorConfig VSCode Extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig), which does change the editor options, you may experience inconsistent behavior between editing and formatting Prisma files in VSCode without this setting, as it will use the default `.editorconfig` settings (Tabs with size 2) for editing and the Prisma Extension settings for formatting.

2023-04-17 17:55 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +		defaultValues: useMemo(() => defaultValue, [defaultValue])
You're right, I missed that. This is a left-over from a previous attempt that I made, will remove it.

2023-04-17 17:59 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	}, [form, defaultValue]);
This is because just changing the `defaultValue` doesn't update the current state of the form. So, without this, on the very first use of this dialog in the app, the component would load without any default indexer rule set.

2023-04-17 19:13 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	);
I don't see how. The problem isn't that `useLibraryQuery` isn't fetching the data, but rather that `react-hook-form` ignores changes to the default value unless it's wrapped in a `useMemo`, and that it doesn't update the form state after its initial setup. Since this component is likely the first place in the app where a query for `locations.indexer_rules.list` will be requested, the value received during instantiation will be `undefined`, causing the form to be set up with an empty list for the default indexer rules. Later, when the corrected value is queried from the backend and the component is updated with the populated indexer rule list (probably during component mount), the form needs to be coaxed into updating its default state through the `useMemo` and `useEffect` hooks.

It's true that subsequent uses of this component won't have this issue since the value will already be cached. So, a potential solution would be to have a list of properties to be requested during app load so that their value is already cached before first use. However, I'm not sure if that's a better solution than simply handling this edge case here. What do you think?

2023-04-18 04:03 UTC, Brendonovich commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	);
Ah I can understand memoising the `filter().map()` for efficiency, but I think memoising the entire `defaultValue` is overdoing it a little. I guess it just depends on whether we want `path` as a dependency in `useMemo` or the `useEffect`, where if we don't then we have to memoise the object separately but if we do then we can construct the object inline in both `defaultValues` and `reset`. Either is fine I guess.

2023-04-18 05:23 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
> +	);
That is fair, I will change it, so it only affects `defaultValues` instead of the whole object

2023-04-18 06:06 UTC, Brendonovich approved these changes

2023-04-18 06:26 UTC, merged