[ENG-461] Location creation fails for '/' (root) and 'C:' ([A-Z] drives)
spacedriveapp/spacedrive pull request #710
Opened 2023-04-14 23:46 UTC by HeavenVolkoff

Fixed the failure to create a location caused by an error in extracting the name from the path. Additionally, improved the location's name extraction logic using [`localize_name`](https://docs.rs/normpath/1.1.1/normpath/trait.PathExt.html#tymethod.localize_name) and added an `Unknown` value as the default when all else fails. A panic was also fixed that occurred when the Indexer job couldn't retrieve the created/modified date of a path. This was achieved by implementing a `MetadataExt` with a default version of `created`/`modified` that returns the current time when the original time isn't available.

2023-04-15 06:42 UTC, HeavenVolkoff commented
Creating a location in `root` or `C:` is still not possible due to permission errors that cause the indexer job to panic. However, when paired with #690, it can work as the paths with permission issues are ignored. Therefore, I believe this is ready for review since it solves the original problem of creating a root location, which was the failure to name the location. The indexer panics should be addressed in another issue/PR.

2023-04-17 08:30 UTC, Brendonovich requested changes

2023-04-17 08:30 UTC, Brendonovich commented on core/src/location/mod.rs
> +	}
Maybe `name` does end up as `/` on Windows, but would it be better to use `"Root"` if `location_path` has a certain length for cross-platform compatibility?

2023-04-17 08:30 UTC, Brendonovich commented on core/src/location/mod.rs
> +	);
Is this necessary over just doing `unwrap_or_else(|| "Unknown".to_string())`?

2023-04-17 20:06 UTC, HeavenVolkoff commented on core/src/location/mod.rs
> +	}
You're right, I didn't consider that. In my opinion, I don't think `Root` is a good name for Windows because Windows users aren't accustomed to the notion of a root drive. Windows treats individual drives as their own root and assigns letters to them. Even for macOS and Linux users who have a Windows node with Spacedrive running on it, `Root` is not a good alternative because they will also expect that the `C:` drive will always show up as `C:`. I think the solution here is to check if the path given to `create_location` has a `/` prefix on Windows, and replace it with the same path under `C:`. This would also simplify the `No OS protected indexer` rule in #690 as I would not need to handle the '/' cases for Windows. What do you think?

2023-04-18 05:04 UTC, HeavenVolkoff commented
I had a discussion with @fogodev about how to handle Windows paths for new locations. We have both agreed that normalizing the path during its creation would be the best approach. Currently, the file watcher logic already assumes that each file has a path that follows the OS-specific format. So, it would be inconvenient that any future changes, or any other area that may deal with paths, to be required to account for Unix paths on Windows. Even more so, considering no user input for file paths, excluding manual entries, will return Unix paths on Windows. Therefore, I have included the logic to normalize paths on Windows in my latest commit. The normalization is done by indirectly calling `GetFullPathNameW`, which converts Unix paths to their Windows counterparts, adds the drive letter, and resolves any relative component of the path. Please note that this method only deals with the path and not the file system, and it doesn't resolve symlinks, which is consistent with our current Unix behavior.

2023-04-18 05:07 UTC, Brendonovich approved these changes

2023-04-18 06:12 UTC, merged