[ENG 485 ] Improve create library dialog
spacedriveapp/spacedrive pull request #712
Opened 2023-04-17 14:49 UTC by niikeec

Changes made:
- Moved `<Dialogs />` to router so router hooks such as `useNavigation` can be used inside a dialog. In this case, it's used so that the user is navigated to the new library once it's created.
- Prevent tab focus on input buttons, that way navigating through a form is easier.
- Added the password strength meter to the password form input. The meter can be shown with the `showStrength` prop.
- Updated the select component and added a form version.
- Updated the Create Library dialog.

<img width="1512" alt="Screenshot 2023-04-17 at 16 48 08" src="https://user-images.githubusercontent.com/43032218/232522432-45bf1c3a-3c50-433f-a641-3b63ef22f767.png">

2023-04-18 05:01 UTC, Brendonovich requested changes

2023-04-18 06:50 UTC, utkubakir commented on packages/ui/src/forms/Input.tsx
> +						{showStrength && <PasswordStrengthMeter password={watch(props.name)} />}
I think it looks clean next to the label and I doubt we will use a strength meter for every password input. It will most likely be only used for new passwords.

2023-04-18 06:53 UTC, utkubakir commented on interface/app/$libraryId/settings/node/libraries/CreateDialog.tsx
> +			}),
Let's also use camelCase here pls.

2023-04-18 07:05 UTC, utkubakir commented on packages/ui/src/forms/Input.tsx
> +	}
Why is this function here? Use client/src/lib/passwordStrength

2023-04-18 08:25 UTC, niikeec commented on packages/ui/src/Dialog.tsx
> +	const step = useMemo(() => props.steps?.[currentStep], [currentStep, props.steps]);
I had it there initially for something else, will update it. If you'd prefer I can also just revert the multi-step as it was used initially, but isn't used anymore.

2023-04-18 08:28 UTC, niikeec commented on packages/ui/src/forms/Input.tsx
> +	);
I tried useMemo and the performance was still bad, as the function is heavy. Personally, I would debounce it, we could use `use-debounce`.

2023-04-18 08:31 UTC, Brendonovich commented on packages/ui/src/forms/Input.tsx
> +	);
Oh debouncing would be good then, I just suggest `useMemo` since it's functionally the same thing as what's being done right now

2023-04-18 08:32 UTC, niikeec commented on packages/ui/src/Input.tsx
> +					tabIndex={-1}
Navigating with tab won't focus the "show password" button, so in this case, if the first password input was focused, clicking tab would focus the "confirm password" input instead of the "show password" button. That way it's easier and faster to navigate trough the form.

2023-04-18 08:32 UTC, Brendonovich commented on packages/ui/src/Dialog.tsx
> +	const step = useMemo(() => props.steps?.[currentStep], [currentStep, props.steps]);
Ah ok, may as well remove it then. Would be good to have it in another PR anyway so we can inspect it a bit easier.

2023-04-18 08:35 UTC, niikeec commented on packages/ui/src/forms/Input.tsx
> +	}
`@sd/client` isn't a dependency in `@sd/ui`. I can make it exportable from `@sd/ui` and then replace it with the one in `@sd/client`

2023-04-18 08:41 UTC, Brendonovich commented on packages/ui/src/Input.tsx
> +					tabIndex={-1}
Ohhh - I'm not sure this is a great idea then, ideally the app should be fully keyboard navigable. I think we have other inputs where tab does navigate to buttons inside inputs.
Perhaps for inputs with multiple buttons we require using tab to navigate to the button group, and then arrowkeys for switching between the buttons, that way you don't have to press tab a bunch of times.

2023-04-18 09:20 UTC, niikeec commented on packages/ui/src/Select.tsx
> +}: PropsWithChildren<SelectProps>) {
Props are passed to the Trigger, except if you want me to remove trigger props.

2023-04-18 09:21 UTC, niikeec commented on packages/ui/src/Input.tsx
> +					tabIndex={-1}
Reverted

2023-04-18 09:22 UTC, niikeec commented on interface/app/$libraryId/settings/node/libraries/CreateDialog.tsx
> +			}),
https://github.com/spacedriveapp/spacedrive/pull/712/commits/8172d9ccffa9c26cc1cd61a0ee9a3d36731c0f2f

2023-04-18 10:03 UTC, Brendonovich commented on packages/ui/src/Select.tsx
> +}: PropsWithChildren<SelectProps>) {
Yeah I don't think Trigger needs the props - can you think of any?

2023-04-18 10:26 UTC, niikeec commented on packages/ui/src/Select.tsx
> +}: PropsWithChildren<SelectProps>) {
Double checked and actually no, pushed.

2023-04-19 05:06 UTC, Brendonovich approved these changes

2023-04-19 07:55 UTC, merged