Checking if new location is nested or already exists
spacedriveapp/spacedrive pull request #716
Opened 2023-04-17 21:02 UTC by fogodev

Currently, we're not planning to support nested locations, so this PR introduce checks to validate that the location path passed to create function isn't a descendant of any location path previously in the database. Also introducing a fix when tried to add a location path already in database that was giving a relink error instead of conflicting with a location path already on database, this happens because before checking DB, we check the `.spacedrive` file. This part is double checked, as someone could just delete `.spacedrive` file and try to add an existing location, so on location create function we check the database.

2023-04-18 04:08 UTC, fogodev commented
Just thoght of some problems, putting back to draft for a bit

2023-04-18 04:09 UTC, Brendonovich requested changes

2023-04-18 04:09 UTC, Brendonovich commented on core/src/location/mod.rs
> +				let old_path = metadata.location_path(library.id).unwrap().to_path_buf();
Would be a bit nicer if `local_path` returned an `Option` so that we could `let Some` instead of unwrapping

2023-04-18 18:04 UTC, HeavenVolkoff requested changes

2023-04-18 18:58 UTC, fogodev commented on core/src/location/mod.rs
> +}
Will check for children locations too

2023-04-18 20:20 UTC, HeavenVolkoff approved these changes

2023-04-19 05:03 UTC, Brendonovich approved these changes

2023-04-19 05:03 UTC, merged