[ENG]-487: Toolbar now uses Context API
spacedriveapp/spacedrive pull request #724
Opened 2023-04-19 11:17 UTC by ameer2468

In this PR I applied Brandons recommendation of making the Toolbar use Context api and therefore each route can define its own array of tools. I thought this would make it easier to maintain. It can get messy if all these options are in one file.

2023-04-19 11:25 UTC, utkubakir commented on interface/app/$libraryId/TopBar/ToolBarProvider.tsx
> +export type ShowAtResolution = 'sm:flex' | 'md:flex' | 'lg:flex' | 'xl:flex' | '2xl:flex';
Can we remove `:flex` from this?

2023-04-19 11:27 UTC, utkubakir commented on interface/app/$libraryId/media.tsx
> +	useToolBar(toolBarOptions);
Why not inline these? It would still be typed and 1 less import is good.

2023-04-19 11:34 UTC, ameer2468 commented on interface/app/$libraryId/TopBar/ToolBarProvider.tsx
> +export type ShowAtResolution = 'sm:flex' | 'md:flex' | 'lg:flex' | 'xl:flex' | '2xl:flex';
Tailwind would have compilation issues - you cannot do something like `${resolutionhere}:flex` - it needs to be the complete class.

2023-04-19 11:35 UTC, ameer2468 commented on interface/app/$libraryId/media.tsx
> +	useToolBar(toolBarOptions);
Valid point, ill do this.

2023-04-21 05:12 UTC, Brendonovich requested changes
Great work on this!

2023-04-21 05:12 UTC, Brendonovich commented on interface/app/$libraryId/Layout/index.tsx
> +							<TopBar ref={topBarChildrenRef} />
Don't put `TopBar` here just yet, I need to rework some of the routing first to make it work

2023-04-21 05:12 UTC, Brendonovich commented on interface/app/$libraryId/TopBar/index.tsx
> +const TopBar = forwardRef<HTMLDivElement, Props>((props, ref) => {
I think you're meant to use `ref` from `forwardRef` here rather than from `props`

2023-04-21 05:12 UTC, Brendonovich commented on interface/app/$libraryId/media.tsx
> +			<TopBarChildren toolOptions={[[]]} />
Ideally `TopBarChildren` wouldn't be needed if no options need to be rendered

2023-04-21 06:57 UTC, Brendonovich approved these changes

2023-04-21 07:02 UTC, merged