[ENG-489] FileThumb uses incorrect dimensions for some thumbnails
spacedriveapp/spacedrive pull request #731
Opened 2023-04-21 02:58 UTC by HeavenVolkoff

WIP

2023-04-21 11:55 UTC, Brendonovich requested changes

2023-04-21 11:55 UTC, Brendonovich commented on packages/client/src/utils/objectKind.ts
> +export type ObjectKinds = keyof typeof ObjectKind;
I think this would be better called `ObjectKindKey` - it shouldn't be plural since union types are multiple options for a single type, and `ObjectKind` is already taken

2023-04-21 11:55 UTC, Brendonovich commented on packages/client/src/utils/index.ts
> +}
this seems redundant

2023-04-21 11:55 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/QuickPreview.tsx
> +	const fileThumb = <FileThumb size={0} data={explorerItem} cover={true} className={className} />;
```suggestion
	const fileThumb = <FileThumb size={0} data={explorerItem} cover className={className} />;
```

2023-04-21 13:18 UTC, HeavenVolkoff commented on packages/client/src/utils/index.ts
> +}
I agree XD. I just couldn't get the TS typchecker to reduce a variable type to be the `keyof` an object after some `in` checks, so I came up with this, but if you think it is too much I can remove it and place some `as keyof typeof ...` in those places, no problem

2023-04-22 00:10 UTC, jamiepine submitted a review, later dismissed

2023-04-22 06:12 UTC, Brendonovich requested changes

2023-04-22 06:12 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +function Thumb({ size, cover, ...props }: ThumbProps) {
Probably worth throwing `memo` on here just in case, we're gonna be rendering a lot of thumbs

2023-04-22 06:23 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +function Thumb({ size, cover, ...props }: ThumbProps) {
You talking about exporting the Thumb component wrapped in memo? If so, I am already doing that at the end of the file.

2023-04-22 06:42 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +function Thumb({ size, cover, ...props }: ThumbProps) {
ah didn't see that, my bad

2023-04-22 06:43 UTC, Brendonovich approved these changes

2023-04-22 06:43 UTC, merged