[ENG-472] Add a `dryRun` parameter to `locations.create`
spacedriveapp/spacedrive pull request #750
Opened 2023-04-22 05:17 UTC by HeavenVolkoff

WIP

2023-04-26 23:29 UTC, fogodev requested changes

2023-04-26 23:29 UTC, fogodev commented on core/src/location/mod.rs
> +		}
This `LocationError::DryRunError` here never happens, as you checked at `if self.dry_run` and `create_location` function can only return `None` if `dry_run` is `true`. So you can remove this error, remove this first if and put an `Ok(None)` in the `else` branch of the `if let`

2023-04-27 21:38 UTC, fogodev commented on core/src/api/locations.rs
> +					Ok(())
You changed the behavior of this route, now it doesn't return the newly created indexer rule anymore, the front-end isn't expecting it?

2023-04-28 00:04 UTC, HeavenVolkoff commented on core/src/api/locations.rs
> +					Ok(())
No, this change doesn't affect the front-end since it's not using the returned indexer rule. Additionally, the `locations.create` endpoint also doesn't return the created location, so I think this change brings the `locations.indexer_rule.create` endpoint in line with it.

2023-04-29 06:33 UTC, fogodev approved these changes

2023-04-29 10:49 UTC, Brendonovich approved these changes

2023-04-29 10:50 UTC, merged