Spacedrop
spacedriveapp/spacedrive pull request #761
Opened 2023-04-26 06:13 UTC by oscartbeaumont

2023-04-26 08:32 UTC, Brendonovich requested changes

2023-04-26 23:11 UTC, fogodev commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
Makes sense to use a `DashMap` here?

2023-04-27 01:19 UTC, brxken128 commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
I'm inclined to agree also, dashmap would fit perfectly

2023-04-27 01:50 UTC, oscartbeaumont commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
I’m inclined to not agree because we don’t want eventual consistency we want strong consistency. The map also has very little contention. I could use the ‘evmap’ crate given I think it has the ability to synchronise readers but with low contention I don’t think it’s going to be of any performance gain.

I have and generally will avoid ‘DashMap’ for most P2P stuff because I have experienced problems with its eventually consistent nature before in this application of it. I suspect this is more of a dev only thing but still. With two nodes running on the same computer they can connect on the scale of milliseconds instead of tens or hundreds of milliseconds like it would between physical machines.

2023-04-27 02:22 UTC, fogodev commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
If it has little contention, I don't oppose to`Mutex<HashMap<K, V>>` then, but `evmap` actually has eventual consistency. I haven't checked `DashMap` source code, but the author says that it uses shards and each shard is behind a `RwLock` internally, but I can't guarantee anything about its consistency model anyway.

2023-04-27 02:49 UTC, oscartbeaumont commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
`evmap` and `DashMap` are a bit different in implementation by my understanding which is why I bring it up. `evmap` has a `.refresh` call which swaps the read/write pointers allowing you to control a switch from eventual consistency to strong consistency by my understanding.

2023-04-27 02:51 UTC, fogodev commented on core/src/p2p/p2p_manager.rs
> +	spacedrop_pairing_reqs: Arc<Mutex<HashMap<Uuid, oneshot::Sender<Option<String>>>>>,
Oh now I got your point then

2023-04-27 02:52 UTC, fogodev approved these changes
I wish it had less `unwraps` but I understand that it's an initial implementation of the feature that will still be refined, so LGTM for now

2023-04-27 04:35 UTC, Brendonovich approved these changes

2023-04-27 04:41 UTC, merged