[ENG-270] macOS install requires ffmpeg to be bundled
spacedriveapp/spacedrive pull request #768
Opened 2023-04-27 08:56 UTC by HeavenVolkoff

WIP

Attempt at building our own ffmpeg dylibs for macOS
 - Create dockerfile to setup osxcross and required host dependencies for cross-compiling ffmpeg for macOS
 - Create script to setup required macOS dependencies and build ffmpeg for both x86_64 and aarch64
 
X86_64 compiles. ARM64 still requires some adjusts to the build script due to ffmpeg having problems with the assembler. 
Still needs to review the logic for remapping and copying the dylibs dependencies to make sure

2023-05-12 05:34 UTC, Brendonovich requested changes

2023-05-12 05:34 UTC, Brendonovich commented on .github/workflows/cache-factory.yaml
> +          token: ${{ secrets.GITHUB_TOKEN }}
I don't think this is necessary, the cache factory is just for Rust dependencies since they take ages

2023-05-12 17:16 UTC, utkubakir submitted a review, later dismissed

2023-05-13 20:08 UTC, Brendonovich approved these changes

2023-05-15 18:03 UTC, merged