[ENG-551] - Jobs grouping and UI improvements
spacedriveapp/spacedrive pull request #771
Opened 2023-04-28 16:32 UTC by ameer2468

**This is an upgrade to the Job manager UI, jobs are now being grouped.** 

- Jobs with assosicated parents are grouped.
- Individual running jobs and individual jobs are displayed alone.
- If any grouped jobs have running jobs, and their children are removed, the running job is displayed alone.

**Videos**:

https://user-images.githubusercontent.com/33054370/235203181-f63a7651-dbb6-4524-a334-2e31462f1aef.mov

https://user-images.githubusercontent.com/33054370/235203560-f980241c-4843-47f2-9899-3d2b5729c8f6.mov

2023-04-30 16:11 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +						onClick={() => setToggleJobs(!toggleJobs)}
`setToggleJobs((v) = > !v))`

2023-04-30 16:15 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/Job.tsx
>  });
Why do we have `filesDiscovered` here? Maybe change it to data or some other name because if we follow this syntax, it will get ugly pretty quickly.

2023-04-30 16:21 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +									clearAJob={(arg) => clearJobHandler(arg)}
`clearAJob={clearJobHandler}` also renaming `clearAJob` to `clearJob` might be better here.

2023-04-30 16:22 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +									isGroup={true}
replace i`sGroup={true}` with `isGroup`

2023-04-30 16:25 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +											total={getTotalTasks(data.childJobs).total}
Maybe make this `getTotalTasks(data.childJobs)` into a constant, you seem to use it a lot and loops are bad 🤔

2023-04-30 16:25 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +	clearAJob?: (arg: string) => void;
How can this be undefined?

2023-04-30 21:33 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +	clearAJob?: (arg: string) => void;
> How and why can this be undefined?

It's not because of it being undefined, the intention is to make the prop optional.

When we map the running jobs, we don't need the clearAJob handler function. Also wouldn't make sense to make a new component just to skip the idea of not making the prop optional.

2023-04-30 21:34 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +									isGroup={true}
> replace `isGroup={true}` with `isGroup`

This wouldn't be a good idea from a readability perspective, the component has multiple props, therefore it would be better to keep it like this for consistency.

If it was just one prop, id put isGroup alone.

2023-04-30 21:35 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/Job.tsx
>  });
> Why do we have `filesDiscovered` here? Maybe change it to data or some other name because if we follow this syntax, it will get ugly pretty quickly.

Renaming it to Data implies that there are multiple variables or data, it doesn't show it's a single value.

Meanwhile, filesDiscovered is clearer naming and I would know there is only one value here.

2023-04-30 21:36 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +						onClick={() => setToggleJobs(!toggleJobs)}
Will apply this to guarantee state updates, although this doesn't really make a difference in this context.

2023-04-30 21:37 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +											total={getTotalTasks(data.childJobs).total}
You're right, ill do this when I wake up tomorrow.

2023-04-30 21:37 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +									clearAJob={(arg) => clearJobHandler(arg)}
This is correct, no need to write an arrow function, can just put it in there.

2023-04-30 21:41 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +	clearAJob?: (arg: string) => void;
Un-intended, this is a mistake actually. Shouldn't be an optional value nor it can be undefined.

2023-05-01 06:41 UTC, Brendonovich commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +									isGroup={true}
I'm with Utku on this one, `isGroup` looks nicer

2023-05-01 07:21 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +						onClick={() => setToggleJobs(!toggleJobs)}
it's also cleaner imo

2023-05-01 09:30 UTC, utkubakir reviewed
The code looks good imo, it's just nitpicking the code style atm. Great job man!

2023-05-01 09:30 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +							onClick={() => clearJob?.(data.id as string)}
`?.` can be removed

2023-05-01 09:30 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/Job.tsx
> +	clearAJob?: (arg: string) => void;
How about this? why is this undefined and can also be renamed to "clearJob"

2023-05-01 09:30 UTC, utkubakir commented on interface/app/style.scss
> +}
Can we do without these? If not, let's move it to where are they used as they are too specific

2023-05-01 09:30 UTC, utkubakir commented on interface/app/style.scss
> +
Instead of hardcoding, adding it to `colors` and the tailwind config is better (for theming)

2023-05-01 09:30 UTC, utkubakir commented on interface/app/$libraryId/Layout/Sidebar/JobManager.tsx
> +	const clearAJob = useLibraryMutation(['jobs.clear'], {
clearJob

2023-05-01 09:38 UTC, Brendonovich requested changes

2023-05-01 09:38 UTC, Brendonovich commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +	}, []);
Why is there both `useState` and `useRef`? `toggleRef` is never updated and will always be `false`, and the `useEffect` doesn't do anything since `toggleJobs` will always be initialised as `false`

2023-05-01 09:38 UTC, Brendonovich commented on interface/app/style.scss
> +.groupjobul {
idk if it's possible but it'd be great if this was implemented in tailwind with our theme's colours and `rem` sizing rather than `px`

2023-05-01 10:09 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/Job.tsx
> +	clearAJob?: (arg: string) => void;
This is needed, when we map the running jobs we don't want to pass a clearJob function.

2023-05-01 10:11 UTC, ameer2468 commented on interface/app/$libraryId/Layout/Sidebar/GroupedJob.tsx
> +	}, []);
I forgot to remove this, in a previous commit this was needed.

2023-05-01 12:56 UTC, utkubakir approved these changes

2023-05-01 13:04 UTC, utkubakir approved these changes

2023-05-01 13:11 UTC, Brendonovich approved these changes

2023-05-01 13:12 UTC, merged