Improve error handling
spacedriveapp/spacedrive pull request #802
Opened 2023-05-08 02:18 UTC by oscartbeaumont

Changes:
 - [x] Log to disk
 - [x] Add some more Clippy lints to enforce error handling.
 - [ ] Button to export logs in the UI
 - [ ] Removing `unwrap` and `panic` calls

2023-05-08 22:21 UTC, fogodev commented
Just a quick note in this regard. But I had to change a bunch of error handling stuff on #781, like introducing a new `FileIOError` instead of plain `io::Error` for errors handling files, as using `?` on `io::Error` we have no data on the file that got the error.  Which is something crucial for my new walker implementation, given that instead of stopping on error, I collect every error that happen while indexing. I also changed many places to use this new error.

2023-05-09 03:54 UTC, oscartbeaumont commented
@fogodev How long until that other PR is going to be ready/merged? If it can be done as soon as possible that would be great and I will put this PR on hold until that then so we aren't modifying the same code.

2023-05-16 20:05 UTC, fogodev commented
Finally got #781 merged

2023-05-20 07:47 UTC, utkubakir commented
Are we going to use sentry to catch rust errors? I think we talked about it in Slack but not sure what you decided on

2023-05-21 18:13 UTC, brxken128 submitted a review, later dismissed
Everything looks awesome to me! Super happy about these changes, better error handling (and additional safety) is always welcome.

2023-05-29 17:41 UTC, Brendonovich requested changes

2023-05-29 17:41 UTC, Brendonovich commented on core/src/api/files.rs
> +								)),
```suggestion
								Utc::now().into()
```

2023-05-30 08:24 UTC, Brendonovich submitted a review, later dismissed

2023-05-30 09:23 UTC, Brendonovich approved these changes

2023-05-30 09:29 UTC, merged