[ENG-528] QuickPreview isn't correctly handling errors for video/audio playback
spacedriveapp/spacedrive pull request #815
Opened 2023-05-13 05:11 UTC by HeavenVolkoff

WIP

Having some issue with QuickPreview affecting Inspector for some reason

2023-05-16 05:02 UTC, Brendonovich requested changes

2023-05-16 05:02 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +	const [loadThumb, setLoadThumb] = useState<boolean>(false);
Could these and some of the above be merged into one `useState`? Would be much nicer to have a single union type than 4 separate values that could get into invalid states. Idk exactly how it all works so fairo if not.

2023-05-17 07:17 UTC, Brendonovich requested changes

2023-05-17 07:17 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
Destructure `getExplorerItemData` inside the effect and you should be able to reduce 4 of these to 1 right?

2023-05-17 19:34 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
`kind`, `extension`, `hasThumbnail` are used in other parts of the code. But if you don't mind repeating the call for `getExplorerItemData` I can do something like this:

```diff
diff --git a/interface/app/$libraryId/Explorer/File/Thumb.tsx b/interface/app/$libraryId/Explorer/File/Thumb.tsx
index 7283df86..f464a20e 100644
--- a/interface/app/$libraryId/Explorer/File/Thumb.tsx
+++ b/interface/app/$libraryId/Explorer/File/Thumb.tsx
@@ -121,10 +121,7 @@ function FileThumb({ size, cover, ...props }: ThumbProps) {
 	const [src, setSrc] = useState<string>('#');
 	const [thumbType, setThumbType] = useState(ThumbType.Icon);
 	const { locationId, newThumbnails } = useExplorerStore();
-	const { kind, extension, hasThumbnail, cas_id, isDir } = getExplorerItemData(
-		props.data,
-		newThumbnails
-	);
+	const { kind, extension, hasThumbnail } = getExplorerItemData(props.data, newThumbnails);
 
 	useEffect(() => {
 		if (props.loadOriginal) {
@@ -137,6 +134,8 @@ function FileThumb({ size, cover, ...props }: ThumbProps) {
 	}, [props.loadOriginal, props.data, hasThumbnail]);
 
 	useEffect(() => {
+		const { kind, extension, cas_id, isDir } = getExplorerItemData(props.data, newThumbnails);
+
 		switch (thumbType) {
 			case ThumbType.Original:
 				if (locationId) {
@@ -156,18 +155,7 @@ function FileThumb({ size, cover, ...props }: ThumbProps) {
 				setSrc(getIcon(kind, isDir, isDark, extension));
 				break;
 		}
-	}, [
-		kind,
-		props.data.item.id,
-		isDir,
-		isDark,
-		cas_id,
-		library.uuid,
-		platform,
-		thumbType,
-		extension,
-		locationId
-	]);
+	}, [props.data, newThumbnails, isDark, library.uuid, platform, thumbType, locationId]);
 
 	const childClassName = 'max-h-full max-w-full object-contain';
 	return (
```

2023-05-17 20:15 UTC, utkubakir commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
7 instead of 10, doesn't matter that much and calling the same function twice just seems unnecessary. You could probably combine them all if you didn't destructure them but meh

2023-05-17 20:15 UTC, utkubakir submitted a review, later dismissed

2023-05-17 20:27 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
I don't think not destructuring it would work as intended, considering `useExplorerData` always returns a new object in every call, which, if I am not mistaken, would result in react running the hook on every render, due to the object changing

2023-05-18 02:44 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
If it were me I'd change `getExplorerItemData` to `useExplorerItemData` and do a `useMemo` internally to avoid running the effect on every render but ehh it's not necessary

2023-05-18 03:03 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/File/Thumb.tsx
> +		locationId
Did something like that in my last commit, but I didn't change `getExplorerItemData` directly, just used a `useMemo` on it inside the component.

2023-05-18 03:29 UTC, Brendonovich approved these changes

2023-05-18 03:31 UTC, merged