[ENG-577 + ENG 608] - Index Rules UI Editor + Job Manager small tweaks
spacedriveapp/spacedrive pull request #822
Opened 2023-05-15 08:58 UTC by ameer2468

This PR applies the new design and update of Index rules UI editor.

For the changes, please watch the video below:

**Notes**:

- The previous code was all in one file, mostly, so I also broke down the work into separate components.
- We now have a IndexerRuleEditor directory with the different components, cleaner structure.
- My goal was to also make this implementation easier to understand than the previous.

https://github.com/spacedriveapp/spacedrive/assets/33054370/660d6e81-b1c4-48cb-bd7c-1fbc68c10d6b

2023-05-15 17:41 UTC, utkubakir requested changes

2023-05-15 17:41 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/index.tsx
> +import clsx from 'clsx';
Rename this file to `IndexerRuleEditor`. Index styling should be for pages not for components. (@Brendonovich can you confirm?)

2023-05-15 17:41 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RuleButton.tsx
> +				});
Can we do this properly? (with await and try-catch)

2023-05-15 17:41 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +					value: value ? true : false,
Maybe replace `value ? true : false` with `Boolean(value)` here?

2023-05-15 18:05 UTC, ameer2468 commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/index.tsx
> +import clsx from 'clsx';
If you take JobManager as an example, theres an index file there. I used that as reference.

2023-05-15 18:06 UTC, ameer2468 commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RuleButton.tsx
> +				});
I was going to do this, but looking at previous examples theres no async and await. Not sure why tho.

2023-05-15 18:14 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +			createIndexerRules.mutateAsync(formatData);
This promise should be either awaited or returned, as it is right now backend errors will be ignored by the frontend

2023-05-15 18:27 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +	};
If we're going to use our own custom validation logic, I think it would be better to migrate all the HTML native pattern validation to this function and remove it from RuleInput. Additionally, it might be better to export this function from RuleInput since it specifically handles validation for it.

2023-05-15 18:31 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +			{createPortal(
I think there should be a comment here explaining why the portal is needed, just like in the previous version:
```
// The portal is required for Form because this component can be nested inside another form element
```

2023-05-15 18:38 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx
> -								/>
Same as above, this showed backend errors

2023-05-16 02:08 UTC, HeavenVolkoff commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +							</label>
Maybe this can be removed? I think the new toggle communicates its intent better than the previous checkbox, so this text has become quite redundant and may confuse users more than it helps.

2023-05-16 03:10 UTC, jamiepine commented
looking better for sure, can we clean up the look of the rule groups? hate the red X and the white border

2023-05-16 08:30 UTC, ameer2468 commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +							</label>
You're right, i'll remove it.

2023-05-16 08:31 UTC, ameer2468 commented
> 

I honestly don't like it either, ill see what I can do, maybe apply the design from the figma instead of this.

2023-05-16 08:31 UTC, ameer2468 commented
> looking better for sure, can we clean up the look of the rule groups? hate the red X and the white border

2023-05-16 10:59 UTC, ameer2468 commented
Latest @jamiepine  and everyone else. I'd like to propose this route, looks better and does whats needed. Also added a delete confirmation, because users could accidently click.

<img width="848" alt="Screenshot 2023-05-16 at 1 57 36 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/de4ad8e3-119d-45c3-9516-e041bf979459">

<img width="416" alt="Screenshot 2023-05-16 at 1 57 44 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/f115b96a-449f-45c2-ab27-eb1fd305f498">

2023-05-17 06:09 UTC, HeavenVolkoff submitted a review, later dismissed

2023-05-17 06:32 UTC, utkubakir commented
- I don't like the whitelist/blacklist thing in the middle but we will soon have this moved to per rule basis so that can stay.
- Padding/spacing looks off with the save button
- `+ New` button is poorly positioned (the top of it should align with the indexer rules text)
- ^ and it's too wide
- Why do we have a permanent delete button? It can overlay when hovered.

And I think the rules look poor. You know we can make it a more significant component with an icon and with Info Pills which shows if it's a System tag and if it's enabled etc. It can also say how many rules are in it.

2023-05-17 07:57 UTC, ameer2468 commented
> - I don't like the whitelist/blacklist thing in the middle but we will soon have this moved to per rule basis so that can stay.
> 
> - Padding/spacing looks off with the save button
> 
> - `+ New` button is poorly positioned (the top of it should align with the indexer rules text)
> 
> - ^ and it's too wide
> 
> - Why do we have a permanent delete button? It can overlay when hovered.
> 
> 
> 
> And I think the rules look poor. You know we can make it a more significant component with an icon and with Info Pills which shows if it's a System tag and if it's enabled etc. It can also say how many rules are in it.

The padding and spacing of the save button is correct. It is equal from the bottom and the top.

2023-05-17 08:59 UTC, utkubakir commented
> > * I don't like the whitelist/blacklist thing in the middle but we will soon have this moved to per rule basis so that can stay.
> > * Padding/spacing looks off with the save button
> > * `+ New` button is poorly positioned (the top of it should align with the indexer rules text)
> > * ^ and it's too wide
> > * Why do we have a permanent delete button? It can overlay when hovered.
> > 
> > And I think the rules look poor. You know we can make it a more significant component with an icon and with Info Pills which shows if it's a System tag and if it's enabled etc. It can also say how many rules are in it.
> 
> The padding and spacing of the save button is correct. It is equal from the bottom and the top.

<img width="131" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/74243531/2301b228-4507-4a7a-b268-a920abe52564">

as you can see, it's double here. Can you move the save button inside the divided box then?

2023-05-17 09:05 UTC, jamiepine commented
I think the padding is overall too much, it could comfortably be half around the outside. It doesn't need to match the padding of the location editor.

2023-05-17 20:23 UTC, utkubakir requested changes

2023-05-17 20:23 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RuleInput.tsx
> +								);
try-catch await please.

2023-05-17 20:23 UTC, utkubakir commented on interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
> +	} = form;
This looks weird, just destructure above or do `form.formState.errors`

2023-05-18 04:48 UTC, utkubakir approved these changes

2023-05-18 04:48 UTC, merged