[ENG-623] - List view obstruction fix
spacedriveapp/spacedrive pull request #839
Opened 2023-05-20 20:22 UTC by ameer2468

This fixes the list view, so that it sticks and doesn't go through.

Screenshot:

<img width="1388" alt="Screenshot 2023-05-20 at 11 19 31 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/dfc4bada-0509-41db-98b0-03a3d7045740">

2023-05-21 06:37 UTC, utkubakir commented on interface/app/$libraryId/Explorer/ListView.tsx
> +					props.listViewHeadersClassName
why pass it 2 components up? just put it here. Also didn't Jamie's last pr fix this issue?

2023-05-21 07:53 UTC, Brendonovich requested changes

2023-05-21 07:53 UTC, Brendonovich commented on packages/client/src/core.ts
> -export type ObjectWithFilePaths = { id: number; pub_id: number[]; kind: number; key_id: number | null; hidden: boolean; favorite: boolean; important: boolean; has_thumbnail: boolean; has_thumbstrip:
this file is autogenerated by the core, you can't just change it. `location_id` isn't available on objects.

2023-05-21 07:53 UTC, Brendonovich commented on interface/app/$libraryId/Explorer/index.tsx
> +	});
this only works bc of the addition to `core.ts`, run `pnpm prep` and then `pnpm typecheck` and this will not be valid.
this was in `/location/$id` before and not `/Explorer` exactly because it's location-specific, maybe if we turn it into a custom hook that takes in `location_id` and reuse it in both `/location/$id` and `/overview`?

2023-05-21 16:14 UTC, utkubakir commented on interface/hooks/useKeyDeleteFile.tsx
> +export default useKeyDeleteFile;
Can we make this more generalized? I think `useKeyboardShortcuts` would be nice. Depending on what's passed we can enable/disable certain shortcuts here.

2023-05-21 16:33 UTC, Brendonovich commented on interface/hooks/useKeyDeleteFile.tsx
> +export default useKeyDeleteFile;
Are there many other shortcuts that could be generalized? Imo this is the only one that makes sense to generalise at the moment. Besides, I think importing multiple hooks and configuring them individually would be nicer than importing one big hook and passing in a big config object

2023-05-21 19:34 UTC, ameer2468 commented on interface/hooks/useKeyDeleteFile.tsx
> +export default useKeyDeleteFile;
I think if there are multiple shortcuts then perhaps generalizing would be a good idea,5+ min. But currently there isnt. I think down the road tho I do see us taking inspiration from existing products and doing something great.

2023-05-22 04:26 UTC, merged

2023-05-22 06:22 UTC, utkubakir commented on interface/hooks/useKeyDeleteFile.tsx
> +export default useKeyDeleteFile;
@Brendonovich you wouldn't pass a big config object, ideally this hook would enable certain shortcuts depending on what's passed and what screen are you on. Importing (and also having) 5-10 hooks to a component just seems dumb. Anyway, we have 10 `useKey` uses, so probably not a big deal now as you guys mentioned.