[ENG-635] Job time estimation
spacedriveapp/spacedrive pull request #842
Opened 2023-05-21 05:10 UTC by jamiepine

2023-05-21 13:27 UTC, ameer2468 commented
Love how this is actually being done by Rust, the backend.

2023-05-23 01:04 UTC, brxken128 approved these changes
the math and rust looks good to me! great job - hopefully it's a lot more accurate now haha

2023-05-23 04:25 UTC, Brendonovich requested changes

2023-05-23 04:25 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
I really don't feel good about having these in the DB, _especially_ `estimated_remaining_seconds`. It is purely ephemeral state that only exists while the job is running, I don't think it's the type of thing that needs to be persisted or synced via the regular sync system.

2023-05-23 05:30 UTC, jamiepine commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
The whole point is that the user can view the job manager in real-time from all devices. This change does not change the frequency events are pushed, we're just adding data to it. The Job report is updated every task regardless of this PR, we can discuss improving it in the future.

2023-05-23 05:37 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
I'm not saying that `estimated_remaining_seconds` shouldn't be synced between nodes, i'm saying that I don't think it's the kind of thing that belongs in the regular sync system. I'd much prefer we send the value out-of-band via a separate system and don't store it in the database, also don't store how many seconds are left but rather what the estimated ending time is so that the frontend can calculate its own countdown. I guess the OOB stuff can happen later, but I'd definitely like to see it changed to use a timestamp rather than a count.

2023-05-23 06:40 UTC, jamiepine commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
what's the difference between a timestamp and a count? both achieve the exact same result.

2023-05-23 06:42 UTC, jamiepine commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
I suppose if a sync message is received late the time would still be accurate if it's a timestamp.

2023-05-23 06:58 UTC, Brendonovich commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
I've expanded on my thoughts on job sync in #engineering, but yeah change it to a timestamp at least.

2023-05-23 07:07 UTC, oscartbeaumont commented on core/prisma/schema.prisma
> +    estimated_remaining_seconds  Int @default(0)// Estimated remaining time in seconds
A timestamp's are wayyy better for anything time-related. If we use a timestamp any React rerender will render the time between now and the timestamp and can display it. Trying to make a function that fires every exactly one second on the frontend to update the second count is surprisingly hard and will have drift (also React's strict mode and stuff are a thing). I also think the frontend should be updating the displayed value to the last known estimate in case the Tauri IPC bridge is lagging behind.

2023-05-23 22:10 UTC, Brendonovich approved these changes

2023-05-23 22:22 UTC, merged