[ENG-534] Themes UI & appearance
spacedriveapp/spacedrive pull request #896
Opened 2023-05-31 15:29 UTC by ameer2468

Took design from mobile and applied to the appearance UI aswell.

- Enabled appearance page
- Theme cards
- Adjusted File icon size so it looks correct
- A few elements required using colors from the theme.
- Hue slider, changes the hue of theme.

**Tweaks not related to this PR, but minor**:

- Feedback dialog, emoji de-selection since it's optional.

<img width="1461" alt="Screenshot 2023-06-05 at 9 44 18 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/9135647a-f9e2-4d7c-b489-4c3910e04de4">

<img width="836" alt="Screenshot 2023-05-31 at 6 31 27 PM" src="https://github.com/spacedriveapp/spacedrive/assets/33054370/78df87cb-69aa-4ef0-9b74-5d94839c3473">

2023-06-05 18:57 UTC, utkubakir requested changes

2023-06-05 18:57 UTC, utkubakir commented on interface/app/$libraryId/settings/client/appearance.tsx
> +									themeStore.theme === 'dark' && themeStore.hueValue[0] === 235
Why the 0 here? `themeStore.hueValue[0]`

2023-06-05 18:57 UTC, utkubakir commented on packages/client/src/stores/themeStore.ts
> +	hueValue: [235],
again why is this an array?

2023-06-05 19:02 UTC, ameer2468 commented on packages/client/src/stores/themeStore.ts
> +	hueValue: [235],
The slider component expects a number within an array.

2023-06-05 19:02 UTC, ameer2468 commented on interface/app/$libraryId/settings/client/appearance.tsx
> +									themeStore.theme === 'dark' && themeStore.hueValue[0] === 235
So we can take the first value within the array, in this case 235.

2023-06-06 02:48 UTC, brxken128 approved these changes
I'm happy with it and all changes work great, even changing system appearance works instantly. Also tested the file icon size changes, and the new feedback stuff is awesome.

Great work, as usual!

2023-06-06 04:41 UTC, utkubakir approved these changes

2023-06-06 04:45 UTC, merged