[ENG-381] Update context menufs actions to support multiple source
spacedriveapp/spacedrive pull request #927
Opened 2023-06-07 13:22 UTC by fogodev

This PR introduces the feature to pass multiple file at same time to the backend for multiple purposes, like opening, copying, moving, renaming, encrypting and decrypt files. Still needs some frontend support.

2023-06-09 12:31 UTC, Brendonovich commented on apps/desktop/src/commands.ts
> +	return invoke()<null>("open_file_path_with", { library, fileIdsAndUrls: [[id, withUrl]] })
was this done manually? i'm pretty sure tauri-specta isn't smart enough to do this, and this file shouldn't be edited

2023-06-11 20:28 UTC, fogodev commented on apps/desktop/src/commands.ts
> +	return invoke()<null>("open_file_path_with", { library, fileIdsAndUrls: [[id, withUrl]] })
Yeah, I did this change manually, haven't noted the comment in the file's beginning LMAO. Sorry about that, will fix ASAP. Which command I have to run to generate this file again, and if tauri-specta couldn't handle the types, how I can have proper typing in this file?

2023-06-12 04:34 UTC, Brendonovich commented on apps/desktop/src/commands.ts
> +	return invoke()<null>("open_file_path_with", { library, fileIdsAndUrls: [[id, withUrl]] })
All good, just run the desktop app and it'll generate new types. If `tauri-specta` can't handle the types then Specta needs more work haha.

2023-06-12 18:43 UTC, utkubakir commented
This will most likely break the app and as far as I know, multi-select isn't fully ready yet (right @niikeec ?) so maybe we should postpone this to after alpha release.

2023-06-14 12:06 UTC, Brendonovich requested changes
not a fan of `= { workspace = true }` but ehh

2023-06-14 12:06 UTC, Brendonovich commented on core/src/library/library.rs
> +			});
would be cool to `map` the results of the query and `chain` onto the iterator that makes the `HashMap`

2023-06-14 14:24 UTC, fogodev commented
> not a fan of `= { workspace = true }` but ehh

My linter here gets really mad at `.workspace = true` lol

2023-06-14 16:57 UTC, fogodev commented on core/src/library/library.rs
> +			});
No can do. The `ids` vec stays borrowed if you don't consume the first iterator so `ids` can be moved into the query, otherwise we have to clone the vec which is even worse

2023-06-14 18:42 UTC, Brendonovich commented on core/src/library/library.rs
> +			});
I think cloning the vec is fine but if you really don't want to do that then `out.extend` combined with using `map` instead of `for_each` works too

2023-06-14 22:55 UTC, HeavenVolkoff commented
> > not a fan of `= { workspace = true }` but ehh
> 
> My linter here gets really mad at `.workspace = true` lol

We could use this form instead:
```
[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true
```

Should work the same, and be more in line with the YAML syntax

2023-06-14 23:05 UTC, merged