Update typescript dependencies
spacedriveapp/spacedrive pull request #93
Opened 2022-05-02 20:24 UTC by Harry-Hopkinson

Update typescript dependencies

2022-05-11 19:11 UTC, maxichrome commented
This PR's description is vague and does not address any existing issues — also seems to address multiple categories of things that would be better addressed via separate PRs, with more explanations on each change's rationale.

2022-05-11 21:00 UTC, Harry-Hopkinson commented
My PR attempted to update typescript dependecies across multiple package.json's which were nested inside the project root. The fixes work and does not implement a breaking change.

2022-05-11 21:42 UTC, maxichrome requested changes
Overall I don't see issues with updating packages here but I don't believe this solves any issue we were previously having. There are a handful of changes in this PR that are not described anywhere in the PR title or body. Please see these comments and resolve before we reconsider merging this PR.

2022-05-11 21:42 UTC, maxichrome commented on apps/desktop/package.json
> +    "react-dom": "^18"
Why remove the specific minor and patch number from this version?

2022-05-11 21:42 UTC, maxichrome commented on apps/desktop/src-tauri/tauri.conf.json
> -        "useBootstrapper": false,
What's the purpose of removing this here and in `tauri.linux.conf.json` (below)?

https://github.com/spacedriveapp/spacedrive/pull/93/files#diff-bc3bedeefe4789dd31ee82df12b779e15d6b11f48f851a62b37c529d2f61b817L24-L30

2022-05-11 21:42 UTC, maxichrome commented on apps/desktop/src/index.tsx
> +      }): Promise<string | string[] | any> {
What does this fix?

2022-05-11 21:42 UTC, maxichrome commented on apps/landing/package.json
> +    "react-dom": "^18",
Why remove version specificity here?

2022-05-11 21:42 UTC, maxichrome commented on apps/landing/package.json
> +    "vite-plugin-svgr": "^2.0.0"
This updates goes across major version numbers. Are you sure there are no breaking changes that affect Spacedrive?

2022-05-11 21:42 UTC, maxichrome commented on apps/web/package.json
> +    "react-dom": "^18"
Again, why remove the version-number specificity here?

2022-05-11 21:42 UTC, maxichrome commented on package.json
> +    "react-dom": "^18"
Why are we _adding_ dependencies to the root `package.json`? What problem does this solve?

2022-05-11 21:42 UTC, maxichrome commented on packages/interface/src/assets/icons/index.ts
> +
This double newline should have been caught and removed by `prettier`. Are you sure you formatted the code per project settings?

2022-05-11 21:42 UTC, maxichrome commented on packages/interface/src/assets/icons/index.ts
> +}
Why was this change included in a PR titled "Update typescript dependencies"?

2022-05-11 21:42 UTC, maxichrome commented on packages/interface/src/components/file/Sidebar.tsx
> +        buttonText={clientState?.client_name || 'Private Landing'}
Why was this change included in a PR titled "Update typescript dependencies"?

2022-05-11 21:42 UTC, maxichrome commented on packages/interface/src/screens/settings/LibrarySettings.tsx
> +          <Toggle initialState={true} size={'sm'} type={''} />
This type is out of date. Please merge changes with current `main` for reconsideration of this PR.

2022-05-11 21:47 UTC, maxichrome commented on packages/interface/src/assets/icons/index.ts
> +}
Also, I'm not sure this is consistent with how `prettier` would have formatted it per our project settings. Please double check that this is formatted properly.

2022-05-11 22:02 UTC, maxichrome commented
I pushed some changes to revert some of the things I commented on above

2022-05-12 06:30 UTC, Harry-Hopkinson commented on apps/desktop/src-tauri/tauri.conf.json
> -        "useBootstrapper": false,
When I updated some packages, it caused some breaking changes due to failing installs as ```"useBootstrapper": false,``` was not a valid argument. I can not exactly remember the error I had recieved though.

2022-05-12 22:37 UTC, maxichrome requested changes
These changes are looking much better but a few updates are still needed. Please make sure to use the `pnpm` CLI when updating packages so they get sorted properly and consistently and avoid extra changes in commits later on.

2022-05-12 22:37 UTC, maxichrome commented on packages/interface/package.json
> +    "postcss": "^8.1.0"
when installing with pnpm these imports get auto-sorted. these were clearly added manually, and therefore would cause constant nags to commit a change to this if it were merged upstream. I'm pushing a change to organize, but please when installing packages in a commit ACTUALLY USE PNPM

2022-05-12 22:37 UTC, maxichrome commented on packages/interface/package.json
> +    "react-dom": "^18.0.0",
why are you adding ReactDOM as a dev dependency here when it's already a dependency?

2022-05-12 22:37 UTC, maxichrome commented on apps/landing/package.json
> +    "@types/node": "*",
why * here???

2022-05-12 22:37 UTC, maxichrome commented on apps/landing/package.json
> +    "@babel/core": "^7.0.0-0",
why add babel core? I'm in support given there's a proper reason but this is not just a types-package update. you NEED to enumerate these things in your PR description.

2022-05-12 22:37 UTC, maxichrome commented on apps/desktop/package.json
> +    "react-dom": "^18.0.0"
Thank you for changing this as requested!

2022-05-12 22:37 UTC, maxichrome commented on package.json
> -    "react-dom": "^18"
Thank you!

2022-05-12 22:37 UTC, maxichrome commented on packages/client/package.json
> +    "react-dom": "^18.0.0"
ReactDOM does not belong as a dependency here. We are not using it in the client package.

2022-05-12 22:37 UTC, maxichrome commented on packages/client/package.json
> +    "react": "^18.0.0"
React does not belong as a direct devDependency here. It's a peerDependency for a reason — we call upon it to render a single data provider component that's accessible to packages that call it. Please remove. Also, where React _is_ a direct dependency, it belongs in `dependencies` and not `devDependencies`.

2022-05-12 22:37 UTC, maxichrome commented on packages/ui/package.json
> +    "react-dom": "^18.0.0"
This is a good change — but it should be a dependency and not a devDependency.

2022-05-13 22:44 UTC, maxichrome commented
Thanks so much for your eagerness to contribute, but the changes you're making in requests to the provided comments just aren't satisfying the requests they're being made in response to. Closing this PR and will implement scoped-down, individually documented changes as necessary.

2022-05-13 22:44 UTC, closed without merging