[ENG-770 / ENG-773] Copy/paste / Explorer context menu duplicate
spacedriveapp/spacedrive pull request #992
Opened 2023-06-21 18:05 UTC by fogodev

This PR fixes issues 770 and 773

2023-06-21 19:07 UTC, utkubakir commented
Just tested this and it seems to work, we need to hide FS actions on Overview though.

2023-06-22 00:45 UTC, HeavenVolkoff commented
> Just tested this and everything seems to work. We do need to hide FS actions on Overview though.

I am working on it, also fixing a small bug I found in this PR. Will commit all the changes here as they are related

2023-06-22 00:47 UTC, HeavenVolkoff requested changes

2023-06-22 00:47 UTC, HeavenVolkoff commented on interface/app/$libraryId/Explorer/ContextMenu.tsx
> +						store.locationId && store.cutCopyState.sourceParentPath !== params.path &&
This check is missing a default value for path (I am fixing it)

2023-06-22 00:51 UTC, fogodev commented on interface/app/$libraryId/Explorer/ContextMenu.tsx
> +						store.locationId && store.cutCopyState.sourceParentPath !== params.path &&
Damn good catch, I noted that after writing both checks, but only fixed on the first one

2023-06-22 02:27 UTC, HeavenVolkoff commented
So, I added the checks for hiding the FS actions in the Overview and the MediaView. I also added error handling to all the actions in the context menus, so that the user has some feedback when things fail. The actions seem to be working as intended from what I could observe from my tests. However, there are 3 points we should look into (don't know if in this PR or another):

 1. Errors that occur in the paste action are not raised to the front. This happens due to the action running inside a job, which the API route does not wait for (which I think is on purpose). Maybe we should change this in the front to be some kind of subscription, so the user has some feedback if any error occurs when pasting files.

 2. Cutting files does not automatically update the file list in the destination. The file is removed from the origin, but only shows up in the destination after a re-scan

 3. Duplicate / Copying a file to the same folder, creates a suffixed copy of the file, however that only work once, as the suffix is hard-coded and it doesn't take into account other previous copies of the same file already present.

2023-06-22 08:27 UTC, utkubakir requested changes

2023-06-22 08:27 UTC, utkubakir commented on interface/app/$libraryId/Explorer/File/ContextMenu.tsx
> +	const isOverview = location.pathname.endsWith('/overview');
As mentioned on Slack, this should cover tags too. I think we can just do `isLocation` instead of filtering those 2 separately.

2023-06-22 18:42 UTC, fogodev commented
I tried pretty hard to reproduce this faulty cut behavior but failed hard lol. Both on my Linux and Mac machines it works as expected. 

Regarding the other points, they're more improvements than problems so we can address them later and we sholdn't postpone our alpha release anymore.

2023-06-22 19:20 UTC, fogodev commented
Actually just found out, just happens on Linux if you cut and paste between different locations. It's a watcher bug

2023-06-22 23:41 UTC, jamiepine approved these changes

2023-06-22 23:44 UTC, merged